#!/usr/bin/env bash
# HISTORICAL (S12/S13 era, already ran): the epilogue URLs below reference the
# RETIRED old box 185.167.119.59; the live box is omega-new = 45.85.3.79.
# S12 Tier 1 PowerShell consolidation -- single-shot commit & push.
# Generated by Cowork; mirrors DEPLOY_S12_FINDING_A.sh structure.
#
# What this does:
#   1. Sanity-check: confirm we're on `main` and that the working tree only
#      contains the expected adds (2) + deletes (11) from this consolidation.
#   2. Show diff stat + the actual diff for the renamed/new files.
#   3. Skip local build (PS1 changes don't affect the C++ backtest target).
#   4. Stage everything, commit with a detailed message, push.
#
# What this does NOT do:
#   - Run the VPS deploy. After this push:
#         (on the VPS)  cd C:\Omega
#                       .\OMEGA.ps1 deploy
#     the new OMEGA.ps1 will be the deploy script itself, so a one-time
#     manual checkout-and-run is the bridge step. Detailed VPS instructions
#     are printed at the end of this script.
#
# Scope of this commit (2 added, 11 deleted, 0 modified):
#   - ADD     OMEGA.ps1
#       Unified control script: subcommands `deploy / restart / start / stop`
#       (and an internal `watchdog` subcommand used by INSTALL_OMEGA -InstallWatchdog).
#       Replaces QUICK_RESTART.ps1 v3.5 + DEPLOY_OMEGA.ps1 + START_OMEGA.ps1
#       + OMEGA_WATCHDOG.ps1 v2.0. Preserves every hardening fix verbatim:
#         * v3.0 service-based stop/start (Stop-Service / Start-Service only)
#         * v3.1 $LASTEXITCODE guards + previous-binary recovery on build fail
#         * v3.2 wipe-race fix (5-attempt exponential backoff + kill-between)
#         * v3.3 Format-NativeOutputLine (ErrorRecord -> RemoteException unwrap)
#         * v3.4 -Branch parameter
#         * v3.5 omega-terminal UI auto-build before C++ build
#         * SOURCE_HASH walk (skip log-only commits)
#         * EXE_SHA256 stamp self-validation + version_generated.hpp cross-check
#         * symbols.ini per-symbol numeric verification
#         * Watermark + mode hard block (LIVE + watermark=0)
#         * Stale-binary detection: timestamp diff <=10s + git hash in log
#         * Watchdog SAFE-TO-RESTART (defer if open positions or telemetry unknown)
#         * Deploy sentinel (deploy_in_progress.flag)
#
#   - ADD     INSTALL_OMEGA.ps1
#       NSSM service installer: -CleanService / -InstallService / -InstallWatchdog
#       / -All / -Uninstall. Replaces INSTALL_SERVICE.ps1 + INSTALL_WATCHDOG.ps1.
#       The watchdog body is now `powershell.exe -File OMEGA.ps1 watchdog`
#       instead of the deleted OMEGA_WATCHDOG.ps1 file.
#
#   - DELETE  QUICK_RESTART.ps1               (consolidated -> OMEGA.ps1 deploy)
#   - DELETE  DEPLOY_OMEGA.ps1                (consolidated -> OMEGA.ps1 deploy)
#   - DELETE  START_OMEGA.ps1                 (consolidated -> OMEGA.ps1 start)
#   - DELETE  INSTALL_SERVICE.ps1             (consolidated -> INSTALL_OMEGA.ps1)
#   - DELETE  INSTALL_WATCHDOG.ps1            (consolidated -> INSTALL_OMEGA.ps1)
#   - DELETE  OMEGA_WATCHDOG.ps1              (consolidated -> OMEGA.ps1 watchdog)
#   - DELETE  OmegaWatchdog.ps1               (obsolete direct-process watchdog;
#                                              previously deferred per Finding A
#                                              commit message -- this commit
#                                              resolves it. The two were NOT
#                                              duplicates by architecture, but
#                                              the camelCase one was the
#                                              direct-process variant for the
#                                              old non-service deploy path,
#                                              which OMEGA.ps1 supersedes
#                                              entirely.)
#   - DELETE  RESTART_OMEGA.ps1               (obsolete -- OMEGA.ps1 restart)
#   - DELETE  REBUILD_AND_START.ps1           (obsolete -- OMEGA.ps1 deploy)
#   - DELETE  START.ps1                       (obsolete -- OMEGA.ps1 start)
#   - DELETE  BASELINE_REPORT.ps1             (obsolete reporting helper)
#
# Files that are KEPT untouched (diagnostic + build-utility):
#   VERIFY_STARTUP.ps1, VERIFY_ALL_ENGINES.ps1, OMEGA_STATUS.ps1, MONITOR.ps1,
#   SEARCH_LOG.ps1, CLEAR_AND_VERIFY.ps1, OMEGA_DIAGNOSE.ps1,
#   PRE_DELIVERY_CHECK.ps1, cmake-discover.ps1, backtest/fetch_l2_data.ps1.
#
# Why this matters:
#   The PS1 surface area went from 21 root scripts (including 8 diagnostic and
#   2 build/backtest helpers) to 12 (8 diagnostic + 2 helpers + OMEGA.ps1 +
#   INSTALL_OMEGA.ps1). The deploy/restart/start/stop entry points are all
#   one script away from a fresh clone. Watchdog logic lives where the deploy
#   logic lives, so a change in one is impossible to forget in the other.
#
# Rollback path if anything breaks post-deploy:
#       git revert HEAD
#       git push origin main
#       # On VPS, re-run with the reverted scripts:
#       cd C:\Omega
#       git pull
#       # Old QUICK_RESTART.ps1 etc. are back; OMEGA.ps1 / INSTALL_OMEGA.ps1
#       # are gone. Re-install services if needed:
#       .\INSTALL_SERVICE.ps1
#       .\INSTALL_WATCHDOG.ps1
#
# Symptoms that would indicate rollback:
#   - .\OMEGA.ps1 deploy fails on the VPS with a parse error or missing
#     dependency that wasn't caught by ASCII-border encoding.
#   - The watchdog NSSM service won't start after .\INSTALL_OMEGA.ps1
#     -InstallWatchdog (check logs\watchdog.log + Windows Event Log).
#
# Symptoms that would indicate it's working:
#   - .\OMEGA.ps1 deploy on the VPS produces the same final banner
#     (COMMIT/BUILT/MODE/GUI/UI lines) as QUICK_RESTART.ps1 v3.5 did.
#   - .\OMEGA.ps1 start verifies the stamp and starts the service.
#   - The OmegaWatchdog NSSM service runs `OMEGA.ps1 watchdog` and produces
#     identical heartbeat lines in logs\watchdog.log.
#
# Usage:
#   cd /Users/jo/omega_repo
#   chmod +x DEPLOY_S12_PS1_CONSOLIDATION.sh
#   ./DEPLOY_S12_PS1_CONSOLIDATION.sh
#
# Abort safely on any error.
set -euo pipefail

cd "$(dirname "$0")"

EXPECTED_ADDED=(
  "OMEGA.ps1"
  "INSTALL_OMEGA.ps1"
)
EXPECTED_DELETED=(
  "QUICK_RESTART.ps1"
  "DEPLOY_OMEGA.ps1"
  "START_OMEGA.ps1"
  "INSTALL_SERVICE.ps1"
  "INSTALL_WATCHDOG.ps1"
  "OMEGA_WATCHDOG.ps1"
  "OmegaWatchdog.ps1"
  "RESTART_OMEGA.ps1"
  "REBUILD_AND_START.ps1"
  "START.ps1"
  "BASELINE_REPORT.ps1"
)

echo "==================================================================="
echo "  S12 Tier 1 PowerShell Consolidation"
echo "==================================================================="
echo "  +2 added:    OMEGA.ps1, INSTALL_OMEGA.ps1"
echo "  -11 deleted: QUICK_RESTART, DEPLOY_OMEGA, START_OMEGA,"
echo "               INSTALL_SERVICE, INSTALL_WATCHDOG,"
echo "               OMEGA_WATCHDOG, OmegaWatchdog,"
echo "               RESTART_OMEGA, REBUILD_AND_START,"
echo "               START, BASELINE_REPORT"
echo "==================================================================="
echo

echo "[1/6] Confirming branch + base state..."
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
CURRENT_HEAD=$(git rev-parse --short HEAD)
echo "      branch: $CURRENT_BRANCH"
echo "      HEAD:   $CURRENT_HEAD"
if [[ "$CURRENT_BRANCH" != "main" ]]; then
  echo "      WARNING: not on 'main'."
  read -r -p "      Continue anyway? (y/yes/n/no): " ANSWER
  case "$ANSWER" in
    y|Y|yes|YES|Yes) ;;
    *) echo "      Aborting. Switch to main first."; exit 1 ;;
  esac
fi
echo

echo "[2/6] Verifying expected adds + deletes..."
# Sanity: every expected ADD must exist on disk (we wrote them this session).
for f in "${EXPECTED_ADDED[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "      ERROR: expected new file '$f' not present on disk."
    echo "      The OMEGA.ps1 / INSTALL_OMEGA.ps1 write step must have failed."
    exit 1
  fi
done
# Sanity: every expected DELETE must still be tracked by git -- otherwise the
# consolidation already happened (re-running this script would be a no-op,
# which is fine, but worth surfacing).
ALREADY_GONE=()
for f in "${EXPECTED_DELETED[@]}"; do
  if [[ ! -e "$f" ]]; then
    if ! git ls-files --error-unmatch "$f" >/dev/null 2>&1; then
      ALREADY_GONE+=("$f")
    fi
  fi
done
if [[ ${#ALREADY_GONE[@]} -gt 0 ]]; then
  echo "      Note: ${#ALREADY_GONE[@]} expected-delete file(s) already absent and untracked:"
  for f in "${ALREADY_GONE[@]}"; do echo "        $f"; done
  echo "      (Possibly a partial earlier run. Continuing.)"
fi
echo

echo "[3/6] Removing the 11 obsolete scripts..."
for f in "${EXPECTED_DELETED[@]}"; do
  if git ls-files --error-unmatch "$f" >/dev/null 2>&1; then
    git rm -- "$f"
    echo "      removed (tracked) : $f"
  elif [[ -e "$f" ]]; then
    rm -f "$f"
    echo "      removed (untracked): $f"
  fi
done
echo

echo "[4/6] Staging the 2 new scripts + showing diff stat..."
git add -- "${EXPECTED_ADDED[@]}"
git status --short
echo
echo "      git diff --cached --stat:"
git --no-pager diff --cached --stat
echo

echo "[5/6] Local build sanity check..."
echo "      (PS1 changes don't affect any C++ target -- skipping cmake build.)"
echo "      (PowerShell parse-check would require pwsh on Mac, which is optional.)"
if command -v pwsh >/dev/null 2>&1; then
  echo "      pwsh found -- running parse-only check on the new scripts:"
  for f in "${EXPECTED_ADDED[@]}"; do
    if pwsh -NoProfile -NonInteractive -Command "[void][System.Management.Automation.Language.Parser]::ParseFile('$PWD/$f', [ref]\$null, [ref]\$null)"; then
      echo "        OK -- $f parsed clean"
    else
      echo "        ERROR: $f failed to parse"
      read -r -p "      Continue with commit anyway? (y/yes/n/no): " ANSWER
      case "$ANSWER" in
        y|Y|yes|YES|Yes) ;;
        *) echo "      Aborting."; exit 1 ;;
      esac
    fi
  done
else
  echo "      (pwsh not on PATH -- VPS will catch any parse error on first run.)"
fi
echo

echo "[6/6] Committing + pushing..."
git commit -m "S12 Tier 1: PS1 consolidation (21 -> 12 scripts)

Adds OMEGA.ps1 and INSTALL_OMEGA.ps1; removes the 11 obsolete scripts
that they replace. Net effect: every Omega lifecycle action (deploy /
restart / start / stop / install / watchdog) is now reachable through
exactly two scripts at the repo root.

Added:
  OMEGA.ps1
    Unified control script. Subcommands:
      deploy   -- full pipeline (stop, git pull, build UI + C++, write +
                  validate stamp, verify symbols/watermark, start, stale-
                  binary checks). Replaces QUICK_RESTART.ps1 v3.5 +
                  DEPLOY_OMEGA.ps1.
      restart  -- stop + start service (no rebuild). Stamp-verifies the
                  on-disk Omega.exe before starting; hard-blocks on
                  mismatch. Replaces RESTART_OMEGA.ps1.
      start    -- start service (or attach if running). Stamp-verifies
                  first; warns if origin/<Branch> has new source commits
                  beyond stamp. Replaces START_OMEGA.ps1 + START.ps1.
      stop     -- graceful Stop-Service with -ForceKill fallback. CFE-open
                  warning prompt before stopping a Running service.
      watchdog -- long-running monitor loop with SAFE-TO-RESTART logic
                  (defer any restart while open positions are detected
                  or telemetry is unknown). Used internally by
                  INSTALL_OMEGA.ps1 -InstallWatchdog as the NSSM service
                  body. Replaces OMEGA_WATCHDOG.ps1 v2.0.

    Hardening preserved verbatim from sources:
      * v3.0 service-based stop/start (NSSM-wrapped 'Omega' service;
        Stop-Service / Start-Service only -- no Start-Process).
      * v3.1 \$LASTEXITCODE guards after every git/cmake call; build
        failure auto-restarts the service with the previous Omega.exe so
        live trading is never left silently down.
      * v3.2 \$zombieNames hoisted to script scope; defensive pre-wipe
        re-kill; both wipe paths (full + per-file) wrapped in 5-attempt
        exponential backoff (200/400/800/1600/3200 ms) with kill-between.
      * v3.3 Format-NativeOutputLine unwraps ErrorRecord ->
        RemoteException so MSBuild stderr (C2065/LNK#### etc) is no
        longer mangled to '[System.Management.Automation.RemoteException]'.
      * v3.4 -Branch parameter (default 'main'); all three Step-2 git
        references use \$Branch / origin/\$Branch.
      * v3.5 omega-terminal UI auto-build (npm ci + npm run build) before
        the C++ build; UI failures route through the same [RECOVERY] path
        as a C++ build failure.
      * SOURCE_HASH walk (skip commits whose only changes are under
        logs/) so the GUI version badge and omega_build.stamp agree even
        when a CMake POST_BUILD push_log step has moved HEAD past the
        source commit.
      * EXE_SHA256 stamp self-validation + version_generated.hpp
        OMEGA_GIT_HASH cross-check.
      * symbols.ini per-symbol numeric verification (XAUUSD 6.00/12.00 etc).
      * Watermark + mode hard block (mode=LIVE with watermark=0).
      * Stale-binary detection: process EXE LastWriteTimeUtc within 10s
        of the freshly-built Omega.exe AND [Omega] Git hash: line in
        stderr matches.
      * Watchdog SAFE-TO-RESTART telemetry probe + heartbeat + GitHub
        HEAD auto-update (5min cadence) + L2 CSV staleness alert (during
        market hours).
      * Deploy sentinel (deploy_in_progress.flag) so the watchdog stays
        in re-attach mode instead of treating a deploy stop as a crash.

  INSTALL_OMEGA.ps1
    NSSM service installer:
      -CleanService     remove any stale 'Omega' service (default if no
                        flags given, matching INSTALL_SERVICE.ps1 default).
      -InstallService   install Omega.exe as NSSM service 'Omega' with
                        stdout/stderr rotation, AppRestartDelay=5s,
                        AppThrottle=30s, LocalSystem auto-start.
      -InstallWatchdog  install OmegaWatchdog as NSSM service that runs
                        powershell.exe -File OMEGA.ps1 watchdog.
                        (Replaces the old OMEGA_WATCHDOG.ps1 service body.)
      -All              shorthand for -CleanService -InstallService
                        -InstallWatchdog. Common one-shot setup.
      -Uninstall        removes BOTH services. C:\\Omega and NSSM are
                        untouched.
    Auto-downloads NSSM 2.24 to C:\\nssm\\ if missing.

Removed (11 scripts; 5 consolidated + 6 obsolete):
  QUICK_RESTART.ps1, DEPLOY_OMEGA.ps1, START_OMEGA.ps1,
  INSTALL_SERVICE.ps1, INSTALL_WATCHDOG.ps1, OMEGA_WATCHDOG.ps1,
  OmegaWatchdog.ps1, RESTART_OMEGA.ps1, REBUILD_AND_START.ps1,
  START.ps1, BASELINE_REPORT.ps1.

The Finding A commit message previously deferred the
OmegaWatchdog.ps1 / OMEGA_WATCHDOG.ps1 cleanup, noting the two are
different architectures (direct-process vs service) rather than
duplicates. This commit resolves that: the service-architecture
watchdog (OMEGA_WATCHDOG.ps1 v2.0) becomes the body of
'OMEGA.ps1 watchdog'; the direct-process variant
(OmegaWatchdog.ps1) is dropped because the deploy path is now
service-only.

Kept untouched (diagnostic + build-utility):
  VERIFY_STARTUP, VERIFY_ALL_ENGINES, OMEGA_STATUS, MONITOR,
  SEARCH_LOG, CLEAR_AND_VERIFY, OMEGA_DIAGNOSE, PRE_DELIVERY_CHECK,
  cmake-discover.ps1, backtest/fetch_l2_data.ps1.

Verification path (post-VPS-deploy):
  1. cd C:\\Omega ; git pull
  2. (one-time) .\\INSTALL_OMEGA.ps1 -InstallService -InstallWatchdog
     This re-creates the 'Omega' and 'OmegaWatchdog' NSSM services
     pointing at the new OMEGA.ps1.
  3. .\\OMEGA.ps1 deploy
     Should produce a final banner identical to what QUICK_RESTART.ps1
     v3.5 produced (COMMIT/BUILT/MODE/GUI/UI lines).
  4. .\\OMEGA.ps1 start should be a no-op when the service is already
     running, and should warn if origin/main has newer source commits.
  5. The OmegaWatchdog service should produce its first
     === WATCHDOG STARTED === line in logs\\watchdog.log within 5s of
     the InstallWatchdog install, followed by HEARTBEAT lines every
     5 minutes.

Rollback:
  Symptoms that would indicate rollback: .\\OMEGA.ps1 deploy fails on
  the VPS with a parse error or missing dependency; OmegaWatchdog
  service won't start after install; deploy succeeds but watchdog log
  shows no HEARTBEAT lines.
  Rollback procedure:
      git revert HEAD
      git push origin main
      # on VPS:
      cd C:\\Omega ; git pull
      .\\INSTALL_SERVICE.ps1
      .\\INSTALL_WATCHDOG.ps1
      .\\QUICK_RESTART.ps1"
echo

echo "Pushing to origin/main..."
git push origin main
echo

NEW_HEAD=$(git rev-parse --short HEAD)

echo "==================================================================="
echo "  COMMIT + PUSH COMPLETE"
echo "==================================================================="
echo
echo "  Commit hash: $NEW_HEAD"
echo
echo "  Next steps (manual, on Windows VPS):"
echo "    cd C:\\Omega"
echo "    git pull"
echo "    # Re-install the NSSM services so they point at OMEGA.ps1"
echo "    # (one-time bridge; both old and new install scripts are present"
echo "    # in the working tree until git pull, after which only the new"
echo "    # one is):"
echo "    .\\INSTALL_OMEGA.ps1 -InstallService -InstallWatchdog"
echo
echo "    # Verify the watchdog service is healthy:"
echo "    Get-Service Omega, OmegaWatchdog"
echo "    Get-Content C:\\Omega\\logs\\watchdog.log -Tail 20"
echo
echo "    # First deploy via the new script:"
echo "    .\\OMEGA.ps1 deploy"
echo
echo "  Expected (unchanged from previous deploy banner):"
echo "      COMMIT : <sourceHashShort>"
echo "      BUILT  : <HH:MM:SS UTC>"
echo "      MODE   : <LIVE | SHADOW | NOT_FOUND>"
echo "      GUI    : http://185.167.119.59:7779"
echo "      UI     : http://185.167.119.59:7781"
echo
echo "  And in logs\\watchdog.log within ~5s of -InstallWatchdog:"
echo "      [WATCHDOG] === WATCHDOG STARTED === version=OMEGA.ps1 watchdog (v3.0 / S12 ...)"
echo "      [WATCHDOG] STARTUP-OK: telemetry probe succeeded, open_positions=<N>"
echo
echo "  Watch over the next 24-48h:"
echo "      Get-Content C:\\Omega\\logs\\watchdog.log -Wait |"
echo "          Select-String -Pattern 'HEARTBEAT|SAFE-TO-RESTART|AUTO-UPDATE|GITHUB-POLL'"
echo
echo "  If anything looks wrong, roll back per the rollback section in the"
echo "  commit message above."
echo
