#!/usr/bin/env bash
# S12 Issue 3a -- shutdown-cause diagnostic markers.
# Generated by Cowork; mirrors DEPLOY_S12_PHASE_CD.sh structure.
#
# What this does:
#   1. Sanity-check: confirm we're on `main` and that ONLY trade_lifecycle.hpp
#      is modified (no other tracked changes besides our target).
#   2. Show diff stat + the actual diff for the changed regions.
#   3. Build the backtest target as a syntactic check (Mac can't link Omega
#      because it requires ws2_32, but it can compile-check headers via the
#      backtest harness, which #includes most of the same files).
#   4. Stage + commit + push.
#
# What this does NOT do:
#   - Run the VPS deploy. That's a separate manual step on the Windows VPS:
#         cd C:\Omega
#         .\DEPLOY_OMEGA.ps1
#   - Install the OmegaWatchdog service. That's a SECOND manual step on the
#     VPS (run as Administrator):
#         cd C:\Omega
#         .\INSTALL_WATCHDOG.ps1
#     The script registers OmegaWatchdog as a Windows SERVICE via NSSM
#     (Start=SERVICE_AUTO_START), so after this runs once the watchdog will
#     auto-start on every boot independent of any user RDP session.
#
# Scope of THIS commit (1 file modified):
#   - MODIFY include/trade_lifecycle.hpp
#       * sig_handler(int sig)                    [POSIX  -- line ~494]
#         Adds named-signal print before g_running.store(false). Maps
#         SIGINT/SIGTERM/SIGABRT/SIGSEGV/SIGFPE/SIGILL to their string
#         names so latest.log identifies the cause.
#       * console_ctrl_handler(DWORD event)       [Win32  -- line ~501]
#         Adds named-event print before g_running.store(false). Maps
#         CTRL_C_EVENT / CTRL_BREAK_EVENT / CTRL_CLOSE_EVENT /
#         CTRL_LOGOFF_EVENT / CTRL_SHUTDOWN_EVENT.
#         Wraps the case-block in `{ ... }` to allow the new local var.
#         Wait-loop, return-value semantics, and comments unchanged.
#
# Why this matters:
#   The 00:51:28 UTC pre-deploy shutdown coincided with a FIX disconnect
#   but the actual trigger was a Windows console event. With these markers,
#   the next surprise shutdown logs which event fired (RDP disconnect =
#   CTRL_LOGOFF_EVENT, OS update = CTRL_SHUTDOWN_EVENT, X-button =
#   CTRL_CLOSE_EVENT, Ctrl+C = CTRL_C_EVENT), removing an entire class of
#   "why did it shut down" mystery.
#
# Format note:
#   Uses std::fprintf(stderr, ...) + std::fflush(stderr) to match the
#   existing [OMEGA] banner pattern at omega_main.hpp:34. <cstdio> reaches
#   trade_lifecycle.hpp transitively via main.cpp. <csignal> is included
#   at main.cpp:37 so SIGINT/SIGTERM/etc. constants are in scope.
#
# Rollback path if anything breaks post-deploy:
#       git revert HEAD
#       git push origin main
#       (then re-run DEPLOY_OMEGA.ps1 on VPS)
#
# Usage:
#   cd /Users/jo/omega_repo
#   chmod +x DEPLOY_S12_ISSUE_3A.sh
#   ./DEPLOY_S12_ISSUE_3A.sh
#
# Abort safely on any error.
set -euo pipefail

cd "$(dirname "$0")"

EXPECTED_MODIFIED=(
  "include/trade_lifecycle.hpp"
)

echo "==================================================================="
echo "  S12 Issue 3a -- shutdown-cause diagnostic markers"
echo "==================================================================="
echo

echo "[1/6] Confirming branch + clean-ish base..."
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
CURRENT_HEAD=$(git rev-parse --short HEAD)
echo "      branch: $CURRENT_BRANCH"
echo "      HEAD:   $CURRENT_HEAD"
if [[ "$CURRENT_BRANCH" != "main" ]]; then
  echo "      WARNING: not on 'main'."
  read -r -p "      Continue anyway? (y/yes/n/no): " ANSWER
  case "$ANSWER" in
    y|Y|yes|YES|Yes) ;;
    *) echo "      Aborting. Switch to main first."; exit 1 ;;
  esac
fi
echo

echo "[2/6] Verifying working-tree state matches expectations..."
# Filter out untracked files (porcelain prefix '??') -- only care about
# tracked files with M/D/A/R/C status.
DIRTY_TRACKED=$(git status --porcelain | grep -Ev '^\?\?' || true)
if [[ -z "$DIRTY_TRACKED" ]]; then
  echo "      ERROR: no tracked files modified. Nothing to commit."
  echo "      (Either issue 3a was already committed, or the Edit never landed.)"
  exit 1
fi

ACTUAL_TRACKED=$(echo "$DIRTY_TRACKED" | awk '{print $2}' | sort)
EXPECTED_ALL=$(printf '%s\n' "${EXPECTED_MODIFIED[@]}" | sort)
UNEXPECTED_TRACKED=$(comm -23 <(echo "$ACTUAL_TRACKED") <(echo "$EXPECTED_ALL") || true)
MISSING=$(comm -13 <(echo "$ACTUAL_TRACKED") <(echo "$EXPECTED_ALL") || true)

UNTRACKED=$(git status --porcelain | grep -E '^\?\?' | awk '{print $2}' | sort || true)
if [[ -n "$UNTRACKED" ]]; then
  echo "      (Note: $(echo "$UNTRACKED" | wc -l | tr -d ' ') untracked files in tree -- ignored, will NOT be committed.)"
fi

if [[ -n "$UNEXPECTED_TRACKED" ]]; then
  echo "      WARNING: tracked files modified outside the expected set:"
  echo "$UNEXPECTED_TRACKED" | sed 's/^/        /'
fi
if [[ -n "$MISSING" ]]; then
  echo "      WARNING: expected files NOT modified:"
  echo "$MISSING" | sed 's/^/        /'
fi
if [[ -n "$UNEXPECTED_TRACKED" || -n "$MISSING" ]]; then
  read -r -p "      Continue anyway? (y/yes/n/no): " ANSWER
  case "$ANSWER" in
    y|Y|yes|YES|Yes) ;;
    *) echo "      Aborting. Investigate manually."; exit 1 ;;
  esac
fi
echo "      Tracked changes (will be committed):"
echo "$DIRTY_TRACKED" | sed 's/^/        /'
echo

echo "[3/6] git diff --stat (sanity check)..."
git diff --stat -- "${EXPECTED_MODIFIED[@]}" || true
echo
echo "      Showing actual diff for changed file:"
git --no-pager diff -- "${EXPECTED_MODIFIED[@]}"
echo

echo "[4/6] Local build sanity check (Mac)..."
# The Omega target is Windows-only (links ws2_32) -- can't build on Mac.
# What we CAN build on Mac: a backtest target that #includes much of the
# same support code (NOT trade_lifecycle.hpp directly though -- that's
# main.cpp-only per its top-of-file comment "SINGLE-TRANSLATION-UNIT
# include -- only include from main.cpp"). So this build only catches
# unrelated regressions; trade_lifecycle.hpp itself is validated on the
# Windows VPS during DEPLOY_OMEGA.ps1.
#
# Visual sanity-check pre-pushed:
#   - sig_handler signature went from (int) to (int sig)        OK
#   - SIGINT/SIGTERM/SIGABRT/SIGSEGV/SIGFPE/SIGILL referenced
#     -- these need <csignal>, which is included at main.cpp:37 OK
#   - std::fprintf(stderr, ...) + std::fflush(stderr) used
#     -- these need <cstdio>, in scope via main.cpp transitive   OK
#   - console_ctrl_handler added a `{ ... }` block after the
#     last fall-through case label -- syntactically valid       OK
if [[ -d build ]]; then
  for tgt in OmegaBacktest IndexBacktest; do
    echo "      Building $tgt ..."
    if ! cmake --build build --target "$tgt" 2>&1 | tail -10; then
      echo "      ERROR: target $tgt failed to build."
      echo "      Roll back with:  git checkout -- ."
      read -r -p "      Continue with commit anyway? (y/yes/n/no): " ANSWER
      case "$ANSWER" in
        y|Y|yes|YES|Yes) ;;
        *) echo "      Aborting."; exit 1 ;;
      esac
    else
      echo "      OK -- $tgt built clean."
    fi
  done
else
  echo "      (No build/ directory. Skipping build check; VPS will catch any issue.)"
fi
echo

echo "[5/6] Staging + committing..."
git add -A "${EXPECTED_MODIFIED[@]}"
git commit -m "S12 issue 3a: log shutdown cause in signal + console handlers

Adds a one-line marker print in both g_running.store(false) writers so
the next surprise shutdown identifies its trigger from latest.log.

Background:
  The 00:51:28 UTC pre-deploy shutdown was investigated in
  S12_INVESTIGATIONS.md (committed 2026-05-07). Finding: there is no
  broker-FIX-disconnect path that exits the process. The shutdown was
  triggered by a Windows console event that COINCIDED with the FIX
  disconnect. Plausible candidates: RDP disconnect, host sleep/wake,
  scheduled OS update, manual close. Without identification at the
  source, every surprise shutdown is a guessing game.

This commit:
  - sig_handler(int sig)
      POSIX path. Maps SIGINT/SIGTERM/SIGABRT/SIGSEGV/SIGFPE/SIGILL
      to their string names. Prints to stderr before flipping the
      atomic. Codebase is Windows-only; on MSVC, std::signal handlers
      for SIGINT/SIGTERM run on a separate thread, so std::fprintf is
      safe (this is NOT a true POSIX async-signal context).
  - console_ctrl_handler(DWORD event)
      Win32 console-control path. Maps CTRL_C_EVENT, CTRL_BREAK_EVENT,
      CTRL_CLOSE_EVENT, CTRL_LOGOFF_EVENT, CTRL_SHUTDOWN_EVENT to their
      string names. Wraps the existing case-block in { ... } to host
      the new local var. Wait-loop (4s) and return-value semantics
      (g_shutdown_done.load() ? TRUE : FALSE) are unchanged.

Format:
  Uses std::fprintf(stderr, ...) + std::fflush(stderr) to match the
  existing [OMEGA] banner pattern at omega_main.hpp:34. Prints exactly
  one extra line per shutdown event; no high-frequency or steady-state
  emission. Zero performance impact.

Operational follow-up (NOT in this commit):
  Run INSTALL_WATCHDOG.ps1 on the VPS as Administrator to register
  OmegaWatchdog as a Windows service (NSSM SERVICE_AUTO_START). Without
  this, the watchdog isn't running on the host even though the watchdog
  code itself is healthy. Pair this commit with that ops step to fully
  close issue 3a.

Verification path:
  After this lands and DEPLOY_OMEGA.ps1 runs, the next time Omega
  shuts down for any reason, latest.log will contain a line like:
      [OMEGA] g_running=false from console event CTRL_LOGOFF_EVENT (5)
  or
      [OMEGA] g_running=false from signal SIGINT (2)
  immediately before the existing [OMEGA] Shutdown line. Search for
  'g_running=false from' to identify the cause."
echo

echo "[6/6] Pushing to origin/main..."
git push origin main
echo

NEW_HEAD=$(git rev-parse --short HEAD)

echo "==================================================================="
echo "  COMMIT + PUSH COMPLETE"
echo "==================================================================="
echo
echo "  Commit hash: $NEW_HEAD"
echo
echo "  Next step (manual, on Windows VPS) -- TWO actions:"
echo
echo "    (1) Build + deploy the new binary:"
echo "          cd C:\\Omega"
echo "          .\\DEPLOY_OMEGA.ps1"
echo
echo "    (2) Install the watchdog as an autostart service (Administrator)."
echo "        Only required if you haven't run this before; check first:"
echo "          Get-Service OmegaWatchdog"
echo "        If it exists and Status=Running, skip this step."
echo "        If it doesn't exist, run from elevated PowerShell:"
echo "          cd C:\\Omega"
echo "          .\\INSTALL_WATCHDOG.ps1"
echo "        Sets up NSSM service with SERVICE_AUTO_START so it survives"
echo "        host reboots independent of any RDP session."
echo
echo "  Then verify post-deploy markers are in place:"
echo "      Get-Content C:\\Omega\\logs\\latest.log -Tail 200 |"
echo "          Select-String -Pattern 'OmegaApi.*g_engines registered|"
echo "          g_engine_heartbeat registered|"
echo "          g_open_positions sources|FATAL'"
echo
echo "  Expected (unchanged from previous deploy):"
echo "      [OmegaApi] g_engines registered (16 engines)"
echo "      [HEARTBEAT] g_engine_heartbeat registered (37 ...)"
echo "      [OmegaApi] g_open_positions sources registered (7)"
echo "      No new FATALs"
echo
echo "  To test the markers (gentle): in a NEW elevated PowerShell on the"
echo "  VPS, send Ctrl+C to the Omega console window. Then check:"
echo "      Get-Content C:\\Omega\\logs\\latest.log -Tail 20 |"
echo "          Select-String -Pattern 'g_running=false from'"
echo "  Expected: a single line like"
echo "      [OMEGA] g_running=false from console event CTRL_C_EVENT (0)"
echo
echo "  If anything looks wrong, roll back:"
echo "      git revert HEAD"
echo "      git push origin main"
echo "      (then re-run DEPLOY_OMEGA.ps1 on VPS)"
echo
