#!/usr/bin/env bash
# S11 P3 Phase B -- automated commit + push from local Mac.
# Generated by Cowork at end of S11 session.
#
# What this does:
#   1. Sanity-check that exactly the 6 expected files have local modifications
#   2. Run git diff --stat for visibility
#   3. Stage + commit + push the 6 files
#
# What this does NOT do:
#   - Run the VPS deploy. That's a separate manual step on the Windows VPS:
#         cd C:\Omega
#         .\DEPLOY_OMEGA.ps1
#
# Usage:
#   cd /Users/jo/omega_repo
#   chmod +x DEPLOY_P3B.sh
#   ./DEPLOY_P3B.sh
#
# Abort safely on any error.
set -euo pipefail

cd "$(dirname "$0")"

EXPECTED_FILES=(
  "include/globals.hpp"
  "include/engine_init.hpp"
  "include/tick_gold.hpp"
  "include/tick_indices.hpp"
  "include/on_tick.hpp"
  "include/quote_loop.hpp"
)

echo "==================================================================="
echo "  S11 P3 Phase B -- commit + push"
echo "==================================================================="
echo

echo "[1/5] Checking working tree state..."
DIRTY=$(git status --porcelain)
if [[ -z "$DIRTY" ]]; then
  echo "      ERROR: working tree is clean. No changes to commit."
  echo "      (Either Phase B was already committed, or the edits never landed.)"
  exit 1
fi

echo "      Modified files (porcelain):"
echo "$DIRTY" | sed 's/^/        /'
echo

echo "[2/5] Verifying only the expected 6 files are modified..."
UNEXPECTED=$(git status --porcelain | awk '{print $2}' | sort)
EXPECTED=$(printf '%s\n' "${EXPECTED_FILES[@]}" | sort)
DIFF=$(comm -23 <(echo "$UNEXPECTED") <(echo "$EXPECTED") || true)
if [[ -n "$DIFF" ]]; then
  echo "      WARNING: unexpected files in working tree:"
  echo "$DIFF" | sed 's/^/        /'
  echo
  read -r -p "      Continue anyway? (yes/no): " ANSWER
  if [[ "$ANSWER" != "yes" ]]; then
    echo "      Aborting. Investigate the unexpected files manually."
    exit 1
  fi
fi
echo "      OK"
echo

echo "[3/5] git diff --stat (line count sanity check)..."
git diff --stat -- "${EXPECTED_FILES[@]}"
echo

echo "[4/5] Staging + committing..."
git add "${EXPECTED_FILES[@]}"
git commit -m "S11 P3b: cull HBG/HBI globals + init + heartbeat + gate-reads

Builds on S10 P3a (commit ba5f0e9, dispatch removal). This commit fully
removes GoldHybridBracketEngine + the four IndexHybridBracketEngine
instances from runtime:

  - 5 static decls in globals.hpp (g_hybrid_gold + 4 g_hybrid_*)
  - 4 OR-terms from index_any_open() predicate
  - 5 shadow_mode init pins in engine_init.hpp
    (S8 RR-asymmetric-bleed rationale preserved as tombstone comments)
  - 5 g_engines.register_engine() blocks
  - 5 g_engine_heartbeat.register_engine() calls
  - HybridGold g_open_positions.register_source() lambda block
  - 5 g_engine_heartbeat.pulse() calls
    (1 in tick_gold.hpp, 4 in tick_indices.hpp)
  - 7 .has_open_position() / .phase / .pos gate-reads
    across tick_gold.hpp, tick_indices.hpp, on_tick.hpp, quote_loop.hpp
  - HybridBracketGold OPEN-POS 5-second log block in quote_loop.hpp

Verification grep at HEAD:
  - Zero g_hybrid_*.member references in code (only comments retain names)
  - Zero \"HybridGold\"/\"HybridSP\"/\"HybridNQ\"/\"HybridUS30\"/\"HybridNAS100\"
    registration string literals in include/
  - Zero static omega::*HybridBracketEngine decls

Phase C (next): delete GoldHybridBracketEngine.hpp +
IndexHybridBracketEngine.hpp source files + their #include references."
echo

echo "[5/5] Pushing to origin/main..."
git push origin main
echo

echo "==================================================================="
echo "  COMMIT + PUSH COMPLETE"
echo "==================================================================="
echo
echo "  Commit hash: $(git rev-parse --short HEAD)"
echo
echo "  Next step (manual, on Windows VPS):"
echo "      cd C:\\Omega"
echo "      .\\DEPLOY_OMEGA.ps1"
echo
echo "  Then verify post-deploy banner deltas:"
echo "      Get-Content C:\\Omega\\logs\\latest.log -Tail 200 |"
echo "          Select-String -Pattern 'g_engines registered|"
echo "          g_engine_heartbeat registered|"
echo "          g_open_positions sources|HEARTBEAT-INIT.*Hybrid'"
echo
echo "  Expected:"
echo "      [OmegaApi] g_engines registered (16 engines)        (was 21)"
echo "      [HEARTBEAT] g_engine_heartbeat registered (37 ...)  (was 42)"
echo "      [OmegaApi] g_open_positions sources registered (7)  (was 8)"
echo "      No [HEARTBEAT-INIT] HybridGold/SP/NQ/US30/NAS100 lines"
echo
