#!/usr/bin/env bash
# S12 P3 Phase C + D combined -- automated commit + push from local Mac.
# Generated by Cowork at the start of S12 session.
#
# What this does:
#   1. Sanity-check: confirm we're on `main` at the expected base commit a6e3403
#   2. Delete the 3 culled files (Hybrid headers + HBG-only backtest harness)
#   3. Verify the working-tree state matches expectations
#      (7 modifications + 3 deletions = 10 changes)
#   4. Show diff stat
#   5. Stage + commit + push
#
# What this does NOT do:
#   - Run the VPS deploy. That's a separate manual step on the Windows VPS:
#         cd C:\Omega
#         .\DEPLOY_OMEGA.ps1
#
# Phase C scope (production source):
#   - DELETE include/GoldHybridBracketEngine.hpp
#   - DELETE include/IndexHybridBracketEngine.hpp
#   - MODIFY include/globals.hpp        (strip 2 #include lines + update tombstones)
#   - MODIFY include/tick_gold.hpp      (update tombstone)
#   - MODIFY include/tick_indices.hpp   (update 4 tombstones for HBI-SP/NQ/US30/NAS)
#   - MODIFY include/engine_init.hpp    (extend HBG + HBI tombstones with P3c line)
#
# Phase D scope (backtest):
#   - DELETE backtest/hbg_duka_bt.cpp   (entire file is HBG-only harness)
#   - MODIFY backtest/IndexBacktest.cpp (drop HBI from 3-engine harness -> 2-engine)
#   - MODIFY backtest/OmegaBacktest.cpp (strip HybridGoldRunner + dispatch)
#   - MODIFY backtest/omega_bt.cpp      (strip HBERunner + dispatch)
#
# VPS deploy impact:
#   - DEPLOY_OMEGA.ps1 builds `--target Omega` only; backtest targets are NOT
#     part of the production build. Production deploy is unaffected by the
#     backtest changes.
#   - Local `cmake --build build` (no --target) was previously broken between
#     Phase C and Phase D; combining them avoids that transient state.
#
# Rollback path if anything breaks post-deploy:
#       git reset --hard a6e3403
#       git push --force-with-lease origin main
#       (then re-run DEPLOY_OMEGA.ps1 on VPS)
#
# Usage:
#   cd /Users/jo/omega_repo
#   chmod +x DEPLOY_S12_PHASE_CD.sh
#   ./DEPLOY_S12_PHASE_CD.sh
#
# Abort safely on any error.
set -euo pipefail

cd "$(dirname "$0")"

EXPECTED_BASE_COMMIT="a6e3403"

EXPECTED_DELETED=(
  "include/GoldHybridBracketEngine.hpp"
  "include/IndexHybridBracketEngine.hpp"
  "backtest/hbg_duka_bt.cpp"
)

EXPECTED_MODIFIED=(
  "include/globals.hpp"
  "include/tick_gold.hpp"
  "include/tick_indices.hpp"
  "include/engine_init.hpp"
  "backtest/IndexBacktest.cpp"
  "backtest/OmegaBacktest.cpp"
  "backtest/omega_bt.cpp"
)

echo "==================================================================="
echo "  S12 P3 Phase C + D -- combined commit + push"
echo "==================================================================="
echo

echo "[1/7] Confirming base commit..."
CURRENT_HEAD=$(git rev-parse --short HEAD)
if [[ "$CURRENT_HEAD" != "$EXPECTED_BASE_COMMIT" ]]; then
  echo "      WARNING: HEAD is at $CURRENT_HEAD, expected $EXPECTED_BASE_COMMIT"
  echo "      (S11 P3b deploy hash). If you've pulled newer changes the diff"
  echo "      below may include unexpected files."
  read -r -p "      Continue anyway? (y/yes/n/no): " ANSWER
  case "$ANSWER" in
    y|Y|yes|YES|Yes) ;;
    *)
      echo "      Aborting. Investigate manually."
      exit 1
      ;;
  esac
else
  echo "      OK -- HEAD = $CURRENT_HEAD"
fi
echo

echo "[2/7] Deleting culled files..."
for f in "${EXPECTED_DELETED[@]}"; do
  if [[ -f "$f" ]]; then
    rm -v "$f"
  else
    echo "      (already absent: $f)"
  fi
done
echo

echo "[3/7] Verifying working-tree state matches expectations..."
# Filter out untracked files (porcelain prefix '??') -- pre-existing untracked
# files in the repo (sweep scripts, docs, build artifacts) are irrelevant to
# this commit. We only care about TRACKED files with M/D/A/R/C status.
DIRTY_TRACKED=$(git status --porcelain | grep -Ev '^\?\?')
if [[ -z "$DIRTY_TRACKED" ]]; then
  echo "      ERROR: no tracked files modified. No changes to commit."
  echo "      (Either Phase C+D was already committed, or the edits never landed.)"
  exit 1
fi

ACTUAL_TRACKED=$(echo "$DIRTY_TRACKED" | awk '{print $2}' | sort)
EXPECTED_ALL=$(printf '%s\n' "${EXPECTED_DELETED[@]}" "${EXPECTED_MODIFIED[@]}" | sort)
UNEXPECTED_TRACKED=$(comm -23 <(echo "$ACTUAL_TRACKED") <(echo "$EXPECTED_ALL") || true)
MISSING=$(comm -13 <(echo "$ACTUAL_TRACKED") <(echo "$EXPECTED_ALL") || true)

# Untracked files (informational only -- not committed, won't fail the script)
UNTRACKED=$(git status --porcelain | grep -E '^\?\?' | awk '{print $2}' | sort || true)
if [[ -n "$UNTRACKED" ]]; then
  echo "      (Note: $(echo "$UNTRACKED" | wc -l | tr -d ' ') untracked files in tree -- ignored, will NOT be committed.)"
fi

if [[ -n "$UNEXPECTED_TRACKED" ]]; then
  echo "      WARNING: tracked files modified outside the expected set:"
  echo "$UNEXPECTED_TRACKED" | sed 's/^/        /'
fi
if [[ -n "$MISSING" ]]; then
  echo "      WARNING: expected files NOT modified:"
  echo "$MISSING" | sed 's/^/        /'
fi
if [[ -n "$UNEXPECTED_TRACKED" || -n "$MISSING" ]]; then
  read -r -p "      Continue anyway? (y/yes/n/no): " ANSWER
  case "$ANSWER" in
    y|Y|yes|YES|Yes) ;;
    *)
      echo "      Aborting. Investigate manually."
      exit 1
      ;;
  esac
fi
echo "      Tracked changes (will be committed):"
echo "$DIRTY_TRACKED" | sed 's/^/        /'
echo

echo "[4/7] git diff --stat (sanity check)..."
git diff --stat -- "${EXPECTED_MODIFIED[@]}" || true
echo "      Deleted files (3):"
for f in "${EXPECTED_DELETED[@]}"; do
  echo "        D $f"
done
echo

echo "[5/7] Local build sanity check (Mac)..."
# The Omega target is Windows-only (links ws2_32) -- can't build on Mac.
# What we CAN check on Mac: the backtest targets we modified in Phase D
# (OmegaBacktest + IndexBacktest). If those compile clean, the Phase D
# edits are syntactically OK; production target only depends on Phase C
# header strips which compile-or-don't independent of Mac/Windows.
if [[ -d build ]]; then
  BUILD_OK=true
  for tgt in OmegaBacktest IndexBacktest; do
    echo "      Building $tgt ..."
    if ! cmake --build build --target "$tgt" 2>&1 | tail -10; then
      echo "      ERROR: target $tgt failed to build."
      BUILD_OK=false
    else
      echo "      OK -- $tgt built clean."
    fi
  done
  if [[ "$BUILD_OK" == "false" ]]; then
    echo "      One or more backtest targets failed."
    echo "      Roll back with:  git checkout -- ."
    echo "                       git reset HEAD ."
    read -r -p "      Continue with commit anyway? (y/yes/n/no): " ANSWER
    case "$ANSWER" in
      y|Y|yes|YES|Yes) ;;
      *) echo "      Aborting."; exit 1 ;;
    esac
  fi
else
  echo "      (No build/ directory. Skipping build check; VPS will catch any issue.)"
fi
echo

echo "[6/7] Staging + committing..."
git add -A "${EXPECTED_DELETED[@]}" "${EXPECTED_MODIFIED[@]}"
git commit -m "S12 P3c+P3d: delete Hybrid headers + cull backtest refs

Builds on S11 P3b (commit a6e3403). This commit completes the
GoldHybridBracketEngine + IndexHybridBracketEngine retirement
trail by deleting the two header files and removing the residual
#include refs from production + backtest code.

Phase C (production):
  - DELETE include/GoldHybridBracketEngine.hpp
  - DELETE include/IndexHybridBracketEngine.hpp
  - globals.hpp:  strip 2 #include lines (lines 351-352 pre-edit) + update
                  tombstones at lines 441-443 + 451-453 to mark Phase C done
  - tick_gold.hpp:    extend HBG tombstone at line ~2105 with P3c line +
                      retire stale 'g_hybrid_gold parallel' note at ~1323
  - tick_indices.hpp: update 4 HBI-SP/NQ/US30/NAS tombstones (lines ~247,
                      ~506, ~610, ~830) with P3c line
  - engine_init.hpp:  extend HBG + HBI tombstones with P3c line

Phase D (backtest):
  - DELETE backtest/hbg_duka_bt.cpp (entire file was HBG-only harness)
  - backtest/IndexBacktest.cpp: drop HBI from the 3-engine cross-engine
                                gate harness; reduce to IFlow + IMC
                                2-engine gate validator
  - backtest/OmegaBacktest.cpp: strip HybridGoldRunner struct + cfg flag +
                                CLI parse + master-flag enable + unique_ptr
                                + construction + tick dispatch + report column
  - backtest/omega_bt.cpp:      strip HBERunner struct + en_hbe flag + CLI
                                parse + master-flag enable + console banner +
                                instance + tick dispatch

Verification grep at HEAD:
  - Zero #include lines for GoldHybridBracketEngine.hpp anywhere
  - Zero #include lines for IndexHybridBracketEngine.hpp anywhere
  - Zero live class references to GoldHybridBracketEngine
  - Zero live class references to IndexHybridBracketEngine
  - All remaining mentions are tombstone comments only

VPS deploy impact:
  - DEPLOY_OMEGA.ps1 builds '--target Omega' only; production binary
    is unaffected by the backtest changes. Phase C strip in globals.hpp
    is the only production-binary-relevant edit.
  - Expected post-deploy banner deltas vs a6e3403: NONE. Engine count,
    heartbeat count, open-positions sources count all unchanged (HBG/HBI
    were already 0 at a6e3403). Production runtime behaviour identical."
echo

echo "[7/7] Pushing to origin/main..."
git push origin main
echo

echo "==================================================================="
echo "  COMMIT + PUSH COMPLETE"
echo "==================================================================="
echo
echo "  Commit hash: $(git rev-parse --short HEAD)"
echo
echo "  Next step (manual, on Windows VPS):"
echo "      cd C:\\Omega"
echo "      .\\DEPLOY_OMEGA.ps1"
echo
echo "  Then verify post-deploy state:"
echo "      Get-Content C:\\Omega\\logs\\latest.log -Tail 200 |"
echo "          Select-String -Pattern 'g_engines registered|"
echo "          g_engine_heartbeat registered|"
echo "          g_open_positions sources|FATAL|HEARTBEAT-INIT.*Hybrid'"
echo
echo "  Expected:"
echo "      [OmegaApi] g_engines registered (16 engines)        (unchanged from P3b)"
echo "      [HEARTBEAT] g_engine_heartbeat registered (37 ...)  (unchanged from P3b)"
echo "      [OmegaApi] g_open_positions sources registered (7)  (unchanged from P3b)"
echo "      No new FATALs"
echo "      No [HEARTBEAT-INIT] HybridGold/SP/NQ/US30/NAS100 lines"
echo
echo "  If anything looks wrong, roll back:"
echo "      git reset --hard $EXPECTED_BASE_COMMIT"
echo "      git push --force-with-lease origin main"
echo "      (then re-run DEPLOY_OMEGA.ps1 on VPS)"
echo
