#!/usr/bin/env python3
"""Regenerate include/OmegaIndexHtml.hpp from tools/gui/omega_desk.html.

Splits the HTML into raw-string chunks under the MSVC 16 KB
per-literal limit and verifies no chunk body collides with its own
raw-string delimiter.

Usage: python3 tools/gui/gen_index_html.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "tools", "gui", "omega_desk.html")
DST = os.path.join(ROOT, "include", "OmegaIndexHtml.hpp")
LIMIT = 14000  # bytes per chunk, safely under MSVC 16384 limit


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        lines = f.read().splitlines(keepends=True)

    chunks = []
    cur = ""
    for ln in lines:
        if len(cur) + len(ln) > LIMIT and cur:
            chunks.append(cur)
            cur = ""
        cur += ln
    if cur:
        chunks.append(cur)

    out = []
    out.append("#pragma once\n")
    out.append("// AUTO-GENERATED by tools/gui/gen_index_html.py from tools/gui/omega_desk.html\n")
    out.append("// -- split into chunks to stay under MSVC 16KB string literal limit.\n")
    out.append("// Edit the .html source and re-run the generator; do not hand-edit this file.\n")
    out.append("namespace omega_gui {\n")
    out.append("static const char* INDEX_HTML =\n")
    for i, ch in enumerate(chunks):
        delim = "OMEGAD%d" % i
        if (")%s\"" % delim) in ch:
            sys.exit("delimiter collision in chunk %d -- pick a new delimiter" % i)
        out.append('R"%s(%s)%s"\n' % (delim, ch, delim))
    out.append(";\n} // namespace omega_gui\n")

    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(out))
    total = sum(len(c) for c in chunks)
    print("wrote %s: %d chunks, %d bytes html, max chunk %d" %
          (DST, len(chunks), total, max(len(c) for c in chunks)))


if __name__ == "__main__":
    main()
