#!/usr/bin/env python3
"""
analyze_rt.py — Walkforward trade analyzer.

Reads walkforward_b_<SYM>_trades.csv and walkforward_b_long_<SYM>_trades.csv
(generated by the patched walkforward harnesses, schema with trailing
atr_at_entry column) and computes per-(symbol, mode, month) statistics
across multiple dimensions to characterise how trade behaviour evolved
through the W1 -> W2 -> W3 -> W4 OOS sequence.

Pure stdlib. Run from ~/Omega/backtest after walkforwards have populated
the trades.csv files.

Outputs:
  rt_summary.txt          — human-readable per-dimension report
  rt_monthly.csv          — flat per-(symbol, mode, month) table, all dims
  rt_window_summary.csv   — per-(symbol, mode, window) aggregates
  rt_dim_<NAME>.csv       — wide pivots, one per dimension
"""

import csv
import os
import sys
from collections import defaultdict, OrderedDict
from datetime import datetime

SYMBOLS = ["XAUUSD", "NAS100", "US500", "GER40", "EURUSD"]
MODES = [("base", "walkforward_b_{sym}_trades.csv"),
         ("long", "walkforward_b_long_{sym}_trades.csv")]


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------
def load_trades(path):
    """Return list of dicts. Skips file if missing."""
    if not os.path.exists(path):
        return None
    rows = []
    with open(path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            try:
                ts = datetime.strptime(r["entry_ts"], "%Y-%m-%d %H:%M:%S")
            except (KeyError, ValueError):
                continue
            try:
                pnl = float(r["pnl"])
                entry_px = float(r["entry_px"])
                exit_px = float(r["exit_px"])
                bars_held = int(r["bars_held"])
                # atr_at_entry may be missing on old trades.csv files
                atr_str = r.get("atr_at_entry", "")
                atr = float(atr_str) if atr_str not in ("", None) else 0.0
            except (KeyError, ValueError):
                continue
            rows.append({
                "window": r.get("window", ""),
                "direction": r.get("direction", ""),
                "entry_ts": ts,
                "month": ts.strftime("%Y-%m"),
                "entry_px": entry_px,
                "exit_px": exit_px,
                "pnl": pnl,
                "exit_reason": r.get("exit_reason", ""),
                "bars_held": bars_held,
                "atr_at_entry": atr,
                # signed direction
                "dir_sign": +1 if r.get("direction") == "long" else -1,
            })
    return rows


# ---------------------------------------------------------------------------
# Bucket helpers
# ---------------------------------------------------------------------------
def group_by(rows, key_fn):
    g = defaultdict(list)
    for r in rows:
        g[key_fn(r)].append(r)
    return g


def safe_mean(xs):
    xs = [x for x in xs if x is not None]
    return (sum(xs) / len(xs)) if xs else 0.0


def safe_pct(num, denom):
    return (num / denom) if denom > 0 else 0.0


# ---------------------------------------------------------------------------
# Per-bucket stat computation
# ---------------------------------------------------------------------------
def compute_stats(trades):
    """Compute every dimension on a list of trades. Returns dict."""
    n = len(trades)
    if n == 0:
        return None

    # R(t) = TP rate
    n_tp = sum(1 for t in trades if t["exit_reason"] == "TP")
    n_sl = sum(1 for t in trades if t["exit_reason"] == "SL")
    n_we = sum(1 for t in trades if t["exit_reason"] == "WEEKEND")
    n_eof = sum(1 for t in trades if t["exit_reason"] == "EOF")

    # Wins / losses (by pnl sign)
    wins = [t for t in trades if t["pnl"] > 0]
    losses = [t for t in trades if t["pnl"] <= 0]

    # Bars held
    bh_win = safe_mean([t["bars_held"] for t in wins])
    bh_loss = safe_mean([t["bars_held"] for t in losses])

    # Win/loss size in ATR units.
    # |exit_px - entry_px| / atr_at_entry, signed by pnl direction.
    # If atr_at_entry is 0 (legacy data), fall back to raw points.
    def trade_atr_size(t):
        atr = t["atr_at_entry"]
        if atr <= 0:
            return None
        return abs(t["exit_px"] - t["entry_px"]) / atr

    win_sizes_atr = [trade_atr_size(t) for t in wins]
    loss_sizes_atr = [trade_atr_size(t) for t in losses]
    mean_win_atr = safe_mean([x for x in win_sizes_atr if x is not None])
    mean_loss_atr = safe_mean([x for x in loss_sizes_atr if x is not None])

    # Direction skew
    n_long = sum(1 for t in trades if t["dir_sign"] == +1)
    n_short = sum(1 for t in trades if t["dir_sign"] == -1)

    # Aggregate pnl
    sum_pnl = sum(t["pnl"] for t in trades)

    return {
        "n_trades": n,
        "rt": safe_pct(n_tp, n),
        "pct_tp": safe_pct(n_tp, n),
        "pct_sl": safe_pct(n_sl, n),
        "pct_weekend": safe_pct(n_we, n),
        "pct_eof": safe_pct(n_eof, n),
        "bars_held_win": bh_win,
        "bars_held_loss": bh_loss,
        "mean_win_atr": mean_win_atr,
        "mean_loss_atr": mean_loss_atr,
        "long_share": safe_pct(n_long, n),
        "short_share": safe_pct(n_short, n),
        "sum_pnl": sum_pnl,
        "n_wins": len(wins),
        "n_losses": len(losses),
    }


# ---------------------------------------------------------------------------
# Main: build per-(symbol, mode, month) and per-(symbol, mode, window) tables
# ---------------------------------------------------------------------------
def main():
    monthly_rows = []     # list of dicts for rt_monthly.csv
    window_rows = []      # list of dicts for rt_window_summary.csv
    summary_buf = []      # text lines for rt_summary.txt
    missing = []

    for sym in SYMBOLS:
        for mode_label, fmt in MODES:
            path = fmt.format(sym=sym)
            trades = load_trades(path)
            if trades is None:
                missing.append(path)
                continue

            # Detect schema: do any rows have non-zero atr_at_entry?
            has_atr = any(t["atr_at_entry"] > 0 for t in trades)

            # Per-month stats
            for month, mtrades in sorted(group_by(trades, lambda t: t["month"]).items()):
                s = compute_stats(mtrades)
                if not s:
                    continue
                row = {"symbol": sym, "mode": mode_label, "month": month, **s}
                monthly_rows.append(row)

            # Per-window stats
            for win, wtrades in sorted(group_by(trades, lambda t: t["window"]).items()):
                s = compute_stats(wtrades)
                if not s:
                    continue
                row = {"symbol": sym, "mode": mode_label, "window": win, **s}
                window_rows.append(row)

            # summary block
            summary_buf.append(f"=== {sym} {mode_label} ===")
            summary_buf.append(f"  total trades: {len(trades)}")
            if not has_atr:
                summary_buf.append("  WARNING: atr_at_entry not present; "
                                   "ATR-normalised sizes will be 0.")
            for win in sorted({t["window"] for t in trades}):
                wt = [t for t in trades if t["window"] == win]
                ws = compute_stats(wt)
                if ws is None:
                    continue
                summary_buf.append(
                    f"  {win}: n={ws['n_trades']:3d}  "
                    f"R(t)={ws['rt']:.3f}  "
                    f"TP/SL/WE/EOF={ws['pct_tp']:.2f}/"
                    f"{ws['pct_sl']:.2f}/{ws['pct_weekend']:.2f}/"
                    f"{ws['pct_eof']:.2f}  "
                    f"BH win/loss={ws['bars_held_win']:.1f}/"
                    f"{ws['bars_held_loss']:.1f}  "
                    f"size_ATR win/loss={ws['mean_win_atr']:.2f}/"
                    f"{ws['mean_loss_atr']:.2f}  "
                    f"long%={ws['long_share']:.2f}  "
                    f"pnl=${ws['sum_pnl']:.0f}"
                )
            summary_buf.append("")

    # ----- write outputs -----
    if monthly_rows:
        with open("rt_monthly.csv", "w", newline="") as f:
            fns = ["symbol", "mode", "month",
                   "n_trades", "n_wins", "n_losses",
                   "rt", "pct_tp", "pct_sl", "pct_weekend", "pct_eof",
                   "bars_held_win", "bars_held_loss",
                   "mean_win_atr", "mean_loss_atr",
                   "long_share", "short_share", "sum_pnl"]
            w = csv.DictWriter(f, fieldnames=fns)
            w.writeheader()
            for r in monthly_rows:
                w.writerow({k: r.get(k, "") for k in fns})

    if window_rows:
        with open("rt_window_summary.csv", "w", newline="") as f:
            fns = ["symbol", "mode", "window",
                   "n_trades", "n_wins", "n_losses",
                   "rt", "pct_tp", "pct_sl", "pct_weekend", "pct_eof",
                   "bars_held_win", "bars_held_loss",
                   "mean_win_atr", "mean_loss_atr",
                   "long_share", "short_share", "sum_pnl"]
            w = csv.DictWriter(f, fieldnames=fns)
            w.writeheader()
            for r in window_rows:
                w.writerow({k: r.get(k, "") for k in fns})

    # ----- per-dimension wide pivots: rows=month, cols=symbol_mode -----
    pivot_dims = ["rt", "pct_tp", "pct_sl", "pct_weekend", "pct_eof",
                  "bars_held_win", "bars_held_loss",
                  "mean_win_atr", "mean_loss_atr",
                  "long_share", "n_trades", "sum_pnl"]
    months_all = sorted({r["month"] for r in monthly_rows})
    cols = []
    for sym in SYMBOLS:
        for mode_label, _ in MODES:
            cols.append(f"{sym}_{mode_label}")
    by_key = {(r["symbol"], r["mode"], r["month"]): r for r in monthly_rows}

    for dim in pivot_dims:
        out_path = f"rt_dim_{dim}.csv"
        with open(out_path, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["month"] + cols)
            for m in months_all:
                row = [m]
                for sym in SYMBOLS:
                    for mode_label, _ in MODES:
                        rec = by_key.get((sym, mode_label, m))
                        row.append(f"{rec[dim]:.4f}" if rec else "")
                w.writerow(row)

    # ----- write rt_summary.txt -----
    with open("rt_summary.txt", "w") as f:
        f.write("Walkforward extended trade analysis\n")
        f.write("=" * 70 + "\n\n")
        if missing:
            f.write("Missing trade files (skipped):\n")
            for p in missing:
                f.write(f"  - {p}\n")
            f.write("\n")
        f.write("Per-window stats (W1 not present here — only OOS rows are written):\n")
        f.write("Schema: pct_tp / pct_sl / pct_weekend / pct_eof exit-reason mix.\n")
        f.write("        bars_held_win / bars_held_loss = mean bars held by P&L sign.\n")
        f.write("        mean_win_atr / mean_loss_atr   = |move| / atr_at_entry.\n")
        f.write("        long_share = fraction of trades that were long.\n\n")
        for line in summary_buf:
            f.write(line + "\n")

        # ----- cross-symbol pattern detection -----
        f.write("\n" + "=" * 70 + "\n")
        f.write("Cross-symbol comparison: W2 vs W4 OOS, base mode\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"{'symbol':<8} {'dim':<18} {'W2':>10} {'W3':>10} {'W4':>10} {'Δ(W4-W2)':>10}\n")
        dims_to_track = ["rt", "pct_tp", "pct_sl", "pct_weekend", "pct_eof",
                         "bars_held_win", "bars_held_loss",
                         "mean_win_atr", "mean_loss_atr", "long_share"]
        # build window lookup
        win_by_key = {(r["symbol"], r["mode"], r["window"]): r for r in window_rows}
        for sym in SYMBOLS:
            for dim in dims_to_track:
                w2 = win_by_key.get((sym, "base", "W2"), {}).get(dim)
                w3 = win_by_key.get((sym, "base", "W3"), {}).get(dim)
                w4 = win_by_key.get((sym, "base", "W4"), {}).get(dim)
                if w2 is None or w4 is None:
                    continue
                delta = w4 - w2
                f.write(f"{sym:<8} {dim:<18} "
                        f"{w2:>10.3f} {(w3 if w3 is not None else 0.0):>10.3f} "
                        f"{w4:>10.3f} {delta:>+10.3f}\n")
            f.write("\n")

        f.write("\n" + "=" * 70 + "\n")
        f.write("Cross-symbol comparison: W2 vs W4 OOS, long mode\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"{'symbol':<8} {'dim':<18} {'W2':>10} {'W3':>10} {'W4':>10} {'Δ(W4-W2)':>10}\n")
        for sym in SYMBOLS:
            for dim in dims_to_track:
                w2 = win_by_key.get((sym, "long", "W2"), {}).get(dim)
                w3 = win_by_key.get((sym, "long", "W3"), {}).get(dim)
                w4 = win_by_key.get((sym, "long", "W4"), {}).get(dim)
                if w2 is None or w4 is None:
                    continue
                delta = w4 - w2
                f.write(f"{sym:<8} {dim:<18} "
                        f"{w2:>10.3f} {(w3 if w3 is not None else 0.0):>10.3f} "
                        f"{w4:>10.3f} {delta:>+10.3f}\n")
            f.write("\n")

    print("Wrote:")
    print("  rt_summary.txt")
    print("  rt_monthly.csv")
    print("  rt_window_summary.csv")
    for d in pivot_dims:
        print(f"  rt_dim_{d}.csv")
    if missing:
        print(f"\nSkipped {len(missing)} missing files.")


if __name__ == "__main__":
    main()
