#pragma once
// AUTO-GENERATED by tools/gui/gen_index_html.py from tools/gui/omega_desk.html
// -- split into chunks to stay under MSVC 16KB string literal limit.
// Edit the .html source and re-run the generator; do not hand-edit this file.
namespace omega_gui {
static const char* INDEX_HTML =
R"OMEGAD0(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Cache-Control" content="no-store,no-cache,must-revalidate">
<title>OMEGA desk</title>
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%230B0F14'/%3E%3Crect x='2' y='2' width='60' height='60' rx='10' fill='none' stroke='%232EBD85' stroke-width='3'/%3E%3Ctext x='32' y='46' font-size='38' text-anchor='middle' fill='%232EBD85' font-family='Georgia,serif' font-weight='bold'%3E%CE%A9%3C/text%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
:root{
  --bg:#0B0F14;--pan:#0E141B;--pan2:#111826;--bd:#1F2937;--bd2:#2b3440;
  --t:#C9D1D9;--t2:#6B7785;--t3:#3d4854;--w:#E6EDF3;
  --grn:#2EBD85;--grnD:#0a4434;--grnB:#9FE1CB;
  --red:#E2484D;--redD:#5c1f1f;--redB:#F7C1C1;
  --amb:#F0B90B;--ambD:#3a2c08;--ambB:#FAC775;
  --blu:#85B7EB;
}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--t);font:12px 'IBM Plex Mono',Menlo,Consolas,monospace;padding:8px}
.num{font-variant-numeric:tabular-nums}
.lbl{font-size:10.5px;color:var(--t2);letter-spacing:.05em}
.pan{background:var(--pan);border:1px solid var(--bd);border-radius:6px;padding:9px 11px;min-width:0}
.grid{display:grid;gap:8px;margin-top:8px}
.chip{display:inline-block;font-size:10.5px;padding:1px 8px;border-radius:3px}
.g{color:var(--grn)}.r{color:var(--red)}.a{color:var(--ambB)}.d{color:var(--t2)}.w{color:var(--w)}
table{width:100%;border-collapse:collapse}
td,th{padding:2px 7px;text-align:right;font-size:11.5px;white-space:nowrap}
#lt td,#lt th{padding:0 6px;font-size:9.5px;line-height:1.45}  /* compact live-open-trades to free vertical space (capped + scroll) */
td:first-child,th:first-child,td.l,th.l{text-align:left}
th{color:var(--t2);font-weight:400}
tr:nth-child(even) td{background:rgba(255,255,255,0.015)}
canvas{display:block;width:100%}
button{background:var(--pan2);color:var(--t);border:1px solid var(--bd2);border-radius:3px;font:11px 'IBM Plex Mono',monospace;padding:3px 10px;cursor:pointer}
button:hover{background:#16202e}
button.on{border-color:var(--grn);color:var(--grnB)}
select{background:var(--pan2);color:var(--t);border:1px solid var(--bd2);border-radius:3px;font:11px 'IBM Plex Mono',monospace;padding:2px 6px}
a{color:var(--blu);text-decoration:none}
.dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:4px;vertical-align:0}
.tile{border-radius:3px;height:34px;display:flex;flex-direction:column;justify-content:center;padding:2px 6px;overflow:hidden}
.tile b{font-size:9.5px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.tile span{font-size:9px;opacity:.9}
.bar{position:relative;height:8px;background:#1d2733;border-radius:2px;overflow:hidden}
.bar>i{position:absolute;left:0;top:0;bottom:0;border-radius:2px}
.pan{transition:border-color .25s ease}
@keyframes flashG{0%{box-shadow:0 0 0 1px var(--grn),0 0 22px rgba(46,189,133,.35)}100%{box-shadow:none}}
.flashg{animation:flashG 1.4s ease-out}
#prtip{position:fixed;display:none;z-index:50;pointer-events:none;background:rgba(14,20,27,.96);border:1px solid var(--bd2);border-radius:5px;padding:6px 9px;font-size:11px;line-height:1.55;box-shadow:0 8px 24px rgba(0,0,0,.55)}
#prc{cursor:crosshair}
.ops .pan{padding:6px 9px}
.ops .lbl{font-size:9.5px}
.ops .num{font-size:10.5px}
.ops #dom{font-size:10px}
@media(max-width:980px){.g2,.g3{grid-template-columns:1fr !important}}
</style>
</head>
<body>

<!-- ═══ RIBBON ═══ -->
<div class="pan" style="display:flex;align-items:center;gap:14px;flex-wrap:wrap;background:var(--pan2);padding:7px 12px;border-radius:6px 6px 0 0">
  <span style="display:inline-flex;align-items:center;gap:8px">
    <span style="width:22px;height:22px;border-radius:5px;background:#0a4434;border:1px solid #0F6E56;color:#9FE1CB;display:inline-flex;align-items:center;justify-content:center;font-size:15px;font-weight:600;font-family:Georgia,serif">&#937;</span>
    <span style="font-size:14px;font-weight:600;color:var(--w)">OMEGA <span style="color:var(--t2);font-weight:400">desk</span></span>
  </span>
  <span id="mode" class="chip" style="background:var(--ambD);color:var(--ambB)">MODE …</span>
  <span class="lbl"><span class="dot" id="fixq" style="background:var(--t3)"></span>FIX-Q</span>
  <span class="lbl"><span class="dot" id="fixt" style="background:var(--t3)"></span>FIX-T</span>
  <span class="lbl"><span class="dot" id="l2d" style="background:var(--t3)"></span>L2</span>
  <span class="lbl"><span class="dot" id="domd" style="background:var(--t3)"></span>GOLD-DOM</span>
  <span class="lbl" id="uptime">up …</span>
  <span class="lbl" id="build"></span>
  <span style="margin-left:auto;display:inline-flex;align-items:baseline;gap:6px"><span class="lbl">TODAY</span><span id="daypnl" class="num" style="font-size:18px;font-weight:600;color:var(--w)">…</span><span id="daypnln" class="lbl"></span></span>
  <span style="display:inline-flex;align-items:baseline;gap:6px"><span class="lbl">ALL-TIME</span><span id="totpnl" class="num" style="font-size:14px;font-weight:600;color:var(--t2)">…</span></span>
  <button id="snd">SND OFF</button>
  <span class="num" id="clk" style="color:var(--w)">--:--:-- UTC</span>
  <span class="lbl"><span class="dot" id="conn" style="background:var(--t3)"></span><span id="connlbl">connecting</span></span>
</div>

<!-- ═══ SESSION STRIP (in top block) ═══ -->
<div style="border:1px solid var(--bd);border-top:none;border-radius:0 0 6px 6px;background:var(--pan);padding:7px 12px;margin-top:-6px">
  <div id="sessbar" style="position:relative;height:14px;border-radius:3px;overflow:hidden;display:flex"></div>
  <div style="display:flex;justify-content:space-between" class="lbl"><span>00 Asia</span><span>05 pre-Ldn</span><span>07 London</span><span>13:30 NY-KZ</span><span>15 NY</span><span>20 late</span><span>22 Asia</span></div>
  <div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:5px">
    <span id="sesstrade" class="chip" style="background:var(--pan2);color:var(--t2)">…</span>
    <span id="healthBadge" class="chip" title="system health (click to (un)mute audible alert)" style="background:var(--pan2);color:var(--t2);cursor:pointer">HEALTH …</span>
    <span id="phases" style="display:flex;gap:6px;flex-wrap:wrap"></span>
    <span class="lbl" style="margin-left:auto">REGIME</span>
    <span id="macro" class="chip" style="background:var(--pan2);color:var(--t2)">…</span>
    <span class="lbl">VIX <span id="vix" class="num w">…</span></span>
  </div>
</div>

<!-- ═══ TICKER ═══ -->
<div id="ticker" style="display:flex;border:1px solid var(--bd);border-radius:6px;margin-top:8px;overflow-x:auto;background:var(--pan)"></div>

<!-- ═══ LIVE OPEN TRADES (always visible) ═══ -->
<div class="pan" id="ltpan" style="margin-top:8px">
  <div style="display:flex;align-items:baseline;gap:10px">
    <span class="lbl">LIVE OPEN TRADES</span>
    <span id="ltcount" class="lbl"></span>
    <span id="ltpnl" class="num" style="margin-left:auto;font-size:13px"></span>
  </div>
  <div style="max-height:132px;overflow-y:auto;margin-top:4px"><table id="lt"><tr><td class="l d">FLAT — no open positions</td></tr></table></div>
</div>

<!-- ═══ PREDICTIVE RANGES ═══ -->
<div class="pan" style="margin-top:8px">
  <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
    <span class="lbl">PREDICTIVE RANGES</span>
    <span class="lbl" style="color:var(--t3)">stepped · non-repainting</span>
    <span id="prinfo" class="lbl num"></span>
    <span style="margin-left:auto;display:flex;gap:8px;align-items:center;flex-wrap:wrap">
      <span id="prlast" class="num" style="font-size:13px;color:var(--w)"></span>
      <span id="prtrend" class="chip" style="background:var(--pan2)"></span>
      <span id="prsyms" style="display:flex;gap:4px"></span>
      <span id="prtfs" style="display:flex;gap:4px"></span>
    </span>
  </div>
  <canvas id="prc" height="430" style="margin-top:6px"></canvas>
  <div class="lbl" style="margin-top:4px">
    <span style="color:var(--blu)">━ PR average</span> ·
    <span style="color:var(--redB)">━ R2  /  ┄ R1 resistance</span> ·
    <span style="color:var(--grnB)">━ S2  /  ┄ S1 support</span> ·
    ▲▼ breakout / reversal · <span style="color:var(--w)">▲/▼ entry → ● exit our trades (win green, loss red, $ pill = PnL)</span> · hover marker for detail · newest exit pulses · levels hold flat until the center steps
  </div>
</div>

<!-- ═══ EQUITY + RISK ═══ -->
<div class="grid g2" style="grid-template-columns:minmax(0,1.7fr) minmax(0,1fr)">
  <div class="pan">
    <div style="display:flex;align-items:baseline;gap:10px;flex-wrap:wrap">
      <span class="lbl">SHADOW EQUITY (paper, all engines)</span>
      <span id="eqtot" class="num" style="font-size:16px;color:var(--grn)">…</span>
      <span style="margin-left:auto;display:flex;gap:5px">
        <button id="w1" class="on">1d</button><button id="w7">7d</button><button id="w30">30d</button><button id="wall">all</button>
      </span>
    </div>
    <canvas id="eqc" height="110" style="margin-top:6px"></canvas>
    <div id="eqstats" class="lbl num" style="display:flex;gap:14px;flex-wrap:wrap;margin-top:5px"></div>
  </div>
  <div class="pan" style="padding:6px 0 4px;display:flex;flex-direction:column">
    <div style="display:flex;align-items:baseline;gap:8px;padding:0 11px 4px">
      <span class="lbl">TRADE HISTORY — all shadow closes (newest first)</span>
      <span id="histn" class="lbl"></span>
    </div>
    <div style="max-height:300px;overflow-y:auto;flex:1">
      <table id="hist"><tr><td class="l d">loading…</td></tr></table>
    </div>
  </div>
</div>

<!-- ═══ ENGINE LEDGER (running totals) + PROMOTION ═══ -->
<div class="grid g2" style="grid-template-columns:minmax(0,1.3fr) minmax(0,1fr)">
  <div class="pan">
    <div style="display:flex;align-items:baseline;gap:8px;margin-bottom:5px">
      <span class="lbl">ENGINE LEDGER — running total, ALL TIME (what makes / loses money)</span>
      <span id="ledgern" class="lbl" style="margin-left:auto"></span>
    </div>
    <div style="max-height:280px;overflow-y:auto">
      <table id="ledger"><tr><td class="l d">loading…</td></tr></table>
    </div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:6px">PROMOTION TRACKER — shadow n vs gate (30) · expectancy</div>
    <div id="promo" style="font-size:11px;max-height:280px;overflow-y:auto"></div>
  </div>
</div>

<!-- ═══ ENGINE HEAT ═══ -->
<div class="pan" style="margin-top:8px">
  <div style="display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;margin-bottom:6px">
    <span class="lbl">ENGINE HEAT — shadow paper PnL, window matches equity · tile = engine</span>
    <span class="lbl" style="margin-left:auto">
      <span style="display:inline-block;width:8px;height:8px;background:var(--grnD);border-radius:2px"></span> +
      <span style="display:inline-block;width:8px;height:8px;background:var(--redD);border-radius:2px;margin-left:8px"></span> −
      <span style="display:inline-block;width:8px;height:8px;background:#1d2733;border-radius:2px;margin-left:8px"></span> flat
    </span>
  </div>
  <div id="heat"></div>
</div>

<!-- ═══ MAE/MFE + TOD ═══ -->
<div class="grid g2" style="grid-template-columns:minmax(0,1fr) minmax(0,1fr)">
  <div class="pan">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px">
      <span class="lbl">MAE / MFE — exit audit (pts)</span>
      <select id="mmsym" style="margin-left:auto"></select>
    </div>
    <canvas id="mmc" height="190"></canvas>
    <div class="lbl" style="margin-top:4px">green = win, red = loss · high-MFE losses → trail/BE too tight</div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:6px">TIME-OF-DAY EDGE — WR% hour × weekday (all shadow)</div>
    <div id="tod"></div>
    <div class="lbl" style="margin-top:4px">hover cell for n / WR / pnl · dark red = hour-kill candidate</div>
  </div>
</div>

<!-- ═══ OPS STRIP — risk / cluster / DOM / micro / signals (compact) ═══ -->
<div class="grid g3 ops" style="grid-template-columns:minmax(0,1.1fr) minmax(0,0.9fr) minmax(0,1.2fr)">
  <div class="pan">
    <div class="lbl" style="margin-bottom:4px">RISK &amp; GOVERNOR — blocks this session</div>
    <div id="gov" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:1px"></div>
    <div class="lbl" style="margin:6px 0 3px">CLUSTER EXPOSURE $</div>
    <div id="expo" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:1px"></div>
    <div id="cooldowns" style="margin-top:5px"></div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:4px">DOM — XAUUSD L2</div>
    <div id="dom" class="num"></div>
    <div style="margin-top:5px">
      <div class="lbl">OBI top-5 <span id="obiv" class="num w"></span></div>
      <div class="bar" style="margin-top:3px"><i id="obib" style="background:var(--grn);left:50%;width:0"></i></div>
    </div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:4px">MICROSTRUCTURE · BROKER · SIGNALS</div>
    <div id="micro" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:1px"></div>
    <div id="broker" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:1px;margin-top:5px"></div>
    <div class="lbl" style="margin:6px 0 2px">SIGNAL TAPE</div>
    <div id="sigs" style="font-size:10px;line-height:1.55;max-height:84px;overflow-y:auto"></div>
  </div>
</div>

<div style="display:flex;gap:14px;align-items:center;margin-top:8px" class="lbl">
  <a href="/legacy">legacy GUI</a>
  <span id="csvinfo"></span>
  <button style="margin-left:auto" onclick="if(confirm('Clear ledger?'))fetch('/api/clear_ledger',{method:'POST'})">clear ledger</button>
</div>

<div id="prtip"></div>

)OMEGAD0"
R"OMEGAD1(<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
<script>
'use strict';
function safe(v,d){d=d===undefined?0:d;var n=Number(v);return isNaN(n)?d:n;}
function fmt$(v){var s=v<0?'-':'+';return s+'$'+Math.abs(v).toLocaleString(undefined,{maximumFractionDigits:0});}
function fmt2(v,n){return safe(v).toFixed(n===undefined?2:n);}
function lots(v){v=safe(v);return v>0?String(+v.toFixed(4)):'—';}
function el(id){return document.getElementById(id);}
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
/* DPR-aware canvas setup: crisp on retina/4K (old code hardcoded 2x). Returns
   a ctx pre-scaled so all drawing happens in CSS pixels. */
function prep(cv,h){var dpr=window.devicePixelRatio||1,w=cv.clientWidth||300;
 cv.width=Math.round(w*dpr);cv.height=Math.round(h*dpr);cv.style.height=h+'px';
 var ctx=cv.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return ctx;}
/* GSAP-backed number tween (falls back to instant set when CDN unavailable) */
var _tw={};
function tweenNum(id,val,fmtFn){var e=el(id);if(!e)return;
 var prev=_tw[id];
 if(prev===undefined||!window.gsap||Math.abs(val-prev)<0.5){_tw[id]=val;e.textContent=fmtFn(val);return;}
 if(prev===val)return;
 _tw[id]=val;var st={v:prev};
 gsap.to(st,{v:val,duration:0.6,ease:'power2.out',overwrite:true,
  onUpdate:function(){e.textContent=fmtFn(st.v);},
  onComplete:function(){e.textContent=fmtFn(val);}});}
function flashPan(id){var p=el(id);if(!p)return;p.classList.remove('flashg');void p.offsetWidth;p.classList.add('flashg');}

/* ── clock ── */
function tickClk(){var d=new Date();el('clk').textContent=
 String(d.getUTCHours()).padStart(2,'0')+':'+String(d.getUTCMinutes()).padStart(2,'0')+':'+String(d.getUTCSeconds()).padStart(2,'0')+' UTC';
 var mk=el('sessmk');if(mk)mk.style.left=(((d.getUTCHours()+d.getUTCMinutes()/60)/24)*100)+'%';}
setInterval(tickClk,1000);
/* ---- HEALTH MONITOR (ported from legacy GUI 2026-06-24; dropped in the 06-12 rewrite).
   Polls /api/health (status.json from healthcheck.ps1). Badge green/amber/red.
   Audible beep + desktop notification ON TRANSITION into FAIL (not first-load, so the
   daily-restart feed-down window doesn't beep on every page open). Click badge to mute. */
var __lastHealth=null, __healthMute=false;
function __healthBeep(){ if(__healthMute) return; try{
  var c=new (window.AudioContext||window.webkitAudioContext)();
  var o=c.createOscillator(),g=c.createGain(); o.type='sine'; g.gain.value=0.25;
  o.connect(g);g.connect(c.destination);o.start();
  o.frequency.setValueAtTime(880,c.currentTime); o.frequency.setValueAtTime(660,c.currentTime+0.18); o.frequency.setValueAtTime(880,c.currentTime+0.36);
  setTimeout(function(){o.stop();c.close();},700);
}catch(e){} }
function __healthNotify(t,b){ if(!('Notification' in window)) return;
  if(Notification.permission==='granted') new Notification(t,{body:b});
  else if(Notification.permission!=='denied') Notification.requestPermission(); }
document.addEventListener('click',function(){ if('Notification' in window && Notification.permission==='default') Notification.requestPermission(); },{once:true});
(function(){ var hb=document.getElementById('healthBadge'); if(hb) hb.addEventListener('click',function(){ __healthMute=!__healthMute; hb.style.opacity=__healthMute?'0.45':'1'; }); })();
async function pollHealth(){
  var b=document.getElementById('healthBadge'); if(!b) return;
  var h; try{ h=await fetch('/api/health',{cache:'no-store'}).then(function(r){return r.json();}); }
  catch(e){ h={overall:'FAIL',fail_count:1,warn_count:0}; }
  var o=(h.overall||'FAIL').toUpperCase(), fc=h.fail_count||0, wc=h.warn_count||0;
  if(o==='OK'){ b.style.color='var(--grn)'; b.textContent='HEALTH OK'; }
  else if(o==='WARN'){ b.style.color='var(--ambB)'; b.textContent='HEALTH '+wc+'W'; }
  else { b.style.color='var(--red)'; b.textContent='HEALTH '+fc+'F'+(wc?(' '+wc+'W'):''); }
  if(o==='FAIL' && __lastHealth && __lastHealth!=='FAIL'){ __healthBeep(); __healthNotify('OMEGA HEALTH FAIL', fc+' failure(s)'); }
  __lastHealth=o;
}
setInterval(pollHealth,15000); pollHealth();

/* ── sounds ── */
var SND=localStorage.getItem('omega_snd')==='1',ACTX=null;
function sndBtn(){var b=el('snd');b.textContent=SND?'SND ON':'SND OFF';b.className=SND?'on':'';}
function ensureCtx(){if(!ACTX){try{ACTX=new (window.AudioContext||window.webkitAudioContext)();}catch(e){}}
 if(ACTX&&ACTX.state==='suspended')ACTX.resume();}
el('snd').onclick=function(){SND=!SND;localStorage.setItem('omega_snd',SND?'1':'0');sndBtn();
 if(SND){ensureCtx();chime([[0,880,0.5],[0.12,1320,0.4]]);}};
sndBtn();
function chime(notes){if(!SND)return;ensureCtx();if(!ACTX)return;var t=ACTX.currentTime;
 notes.forEach(function(n){var o=ACTX.createOscillator(),g=ACTX.createGain();
  o.connect(g);g.connect(ACTX.destination);o.type='sine';o.frequency.value=n[1];
  var st=t+n[0];g.gain.setValueAtTime(0,st);g.gain.linearRampToValueAtTime(n[2],st+0.01);
  g.gain.exponentialRampToValueAtTime(0.001,st+0.5);o.start(st);o.stop(st+0.55);});}
function winBell(){chime([[0,880,0.6],[0.15,1100,0.5],[0.3,1320,0.5]]);}
function lossBell(){chime([[0,440,0.6],[0.18,330,0.5],[0.36,262,0.5]]);}
function sigTick(){chime([[0,660,0.25]]);}
function entryBell(){chime([[0,740,0.5],[0.12,988,0.45]]);}
/* browsers suspend AudioContext until a user gesture -- with SND persisted ON a
   reloaded page was SILENT until the user happened to click. Resume on first
   gesture so persisted-ON actually rings. */
['click','keydown','touchstart'].forEach(function(ev){
 document.addEventListener(ev,function(){if(SND)ensureCtx();},{once:true,capture:true});});

/* ── session strip ── */
(function(){var z=[[0,5,'#1d2733'],[5,7,'#143042'],[7,13,'#155446'],[13,13.5,'#0F6E56'],[13.5,15,'#7a5a14'],[15,20,'#155446'],[20,22,'#143042'],[22,24,'#1d2733']];
 var h='';z.forEach(function(s){h+='<span style="flex:'+(s[1]-s[0])+';background:'+s[2]+'"></span>';});
 el('sessbar').innerHTML=h+'<div id="sessmk" style="position:absolute;top:0;bottom:0;width:2px;background:#E6EDF3"></div>';tickClk();})();

/* ── ticker defs ── */
var TKS=[['gold','XAUUSD','xau'],['sp','US500','sp'],['nq','USTEC','nq'],['nas','NAS100','nas'],['dj','DJ30','dj'],
 ['ger30','GER40','ger40'],['uk100','UK100','uk100'],['cl','USOIL','cl'],['xag','XAGUSD','xag'],['vix','VIX',null]];
(function(){var h='';TKS.forEach(function(t){
 h+='<div style="padding:6px 12px;border-right:1px solid var(--bd);min-width:104px">'
  +'<div class="lbl">'+t[1]+'</div><div class="num" id="tk_'+t[0]+'" style="font-size:13px;color:var(--w)">—</div>'
  +'<div class="lbl num" id="tks_'+t[0]+'"></div>'
  +(t[2]?'<div class="bar" style="height:4px;margin-top:3px"><i id="tkr_'+t[0]+'" style="background:var(--blu);width:0"></i></div>':'')
  +'</div>';});
 el('ticker').innerHTML=h;})();

/* ── position registry fallback (read-API :7781, CORS-open) ── */
var REGPOS=[];
function pollReg(){fetch('http://'+location.hostname+':7781/api/v1/omega/positions')
 .then(function(r){return r.json();})
 .then(function(j){REGPOS=Array.isArray(j)?j:[];if(lastJ)render(lastJ);})
 .catch(function(){});}
setInterval(pollReg,30000);pollReg();

/* ── telemetry render ── */
var lastJ=null;
function render(J){lastJ=J;
 var shadowMode=(J.mode||'').toUpperCase()!=='LIVE';
 var m=el('mode');m.textContent=shadowMode?'SHADOW — 0 live engines':'LIVE';
 m.style.background=shadowMode?'var(--ambD)':'var(--grnD)';m.style.color=shadowMode?'var(--ambB)':'var(--grnB)';
 function dot(id,ok){el(id).style.background=ok?'var(--grn)':'var(--red)';}
 dot('fixq',(J.fix_quote_status||'').indexOf('CONNECT')>=0||(J.fix_quote_status||'').indexOf('UP')>=0||J.quote_msg_rate>0);
 dot('fixt',(J.fix_trade_status||'').indexOf('CONNECT')>=0||(J.fix_trade_status||'').indexOf('UP')>=0);
 dot('l2d',safe(J.ctrader_l2_live)>0);dot('domd',safe(J.gold_l2_real)>0);
 var up=safe(J.uptime_sec);el('uptime').textContent='up '+Math.floor(up/86400)+'d'+Math.floor(up%86400/3600)+'h'+Math.floor(up%3600/60)+'m';
 el('build').textContent=(J.build_version||'').slice(0,12);
 var st=el('sesstrade');st.textContent=(J.session_name||'?')+(safe(J.session_tradeable)?' · tradeable':' · blocked');
 st.style.color=safe(J.session_tradeable)?'var(--grnB)':'var(--redB)';
 el('macro').textContent=J.macro_regime||'?';
 el('macro').style.color=(J.macro_regime||'')==='RISK_OFF'?'var(--redB)':'var(--grnB)';
 el('vix').textContent=fmt2(J.vix_level,1);

 TKS.forEach(function(t){var b=safe(J[t[0]+'_bid']),a=safe(J[t[0]+'_ask']);
  if(t[0]==='vix'){b=safe(J.vix_level)||b;}
  el('tk_'+t[0]).textContent=b>0?b.toLocaleString(undefined,{maximumFractionDigits:b>100?1:4}):'—';
  if(b>0&&a>0&&t[0]!=='vix')el('tks_'+t[0]).textContent='s '+fmt2(a-b,a-b<0.01?5:2);
  if(t[2]){var lo=safe(J[t[2]+'_curl']),hi=safe(J[t[2]+'_curh']);
   if(hi>lo&&b>0){var p=Math.max(0,Math.min(1,(b-lo)/(hi-lo)));var r=el('tkr_'+t[0]);r.style.width=(p*100)+'%';
    r.style.background=p>0.85||p<0.15?'var(--amb)':'var(--blu)';}}});

 var govRows=[['Spread gate',J.gov_spread],['Latency gate',J.gov_latency],['PnL governor',J.gov_pnl],
  ['Position cap',J.gov_positions],['Consec-loss',J.gov_consec_loss],
  ['Cost guard blocked',J.cost_guard_blocked],['Cost guard passed',J.cost_guard_passed]];
 el('gov').innerHTML=govRows.map(function(r){var v=safe(r[1]);
  var c=r[0].indexOf('passed')>=0?'g':(v>0?'a':'d');
  return '<span>'+r[0]+'</span><span class="'+c+'">'+v+'</span>';}).join('')
  +(safe(J.multiday_throttle_active)?'<span class="r">Multiday throttle</span><span class="r">×'+fmt2(J.multiday_scale)+'</span>':'');
 var ex=[['US equity',J.exposure_us_equity],['EU equity',J.exposure_eu_equity],['Oil',J.exposure_oil],
  ['Metals',J.exposure_metals],['JPY risk',J.exposure_jpy_risk],['EUR/GBP',J.exposure_eur_gbp],['TOTAL',J.exposure_total]];
 el('expo').innerHTML=ex.map(function(r){var v=safe(r[1]);
  return '<span'+(r[0]==='TOTAL'?' class="w"':'')+'>'+r[0]+'</span><span class="'+(v>0?'w':'d')+'">$'+Math.round(v)+'</span>';}).join('');
 var cd=(J.sl_cooldowns||[]).map(function(c){return '<span class="chip" style="background:var(--redD);color:var(--redB)">'+esc(c.symbol)+' '+c.secs_remaining+'s</span>';}).join(' ');
 el('cooldowns').innerHTML=cd?'<div class="lbl" style="margin-bottom:3px">SL COOLDOWNS</div>'+cd:'';

 var ph=[['XAU','xau'],['SP','sp'],['NQ','nq'],['OIL','cl'],['XAG','xag'],['BRENT','brent']];
 el('phases').innerHTML=ph.map(function(p){var v=safe(J[p[1]+'_phase']);
  var t=v===3?'TRADE':v===2?'BRK':v===1?'COMP':'FLAT';
  var bg=v===3?'var(--grnD)':v===2?'#7a5a14':v===1?'#143042':'var(--pan2)';
  var fg=v===3?'var(--grnB)':v===2?'var(--ambB)':v===1?'var(--blu)':'var(--t2)';
  return '<span class="chip" style="background:'+bg+';color:'+fg+'">'+p[0]+' '+t+'</span>';}).join('');

 var bids=J.gold_bids||[],asks=J.gold_asks||[];
 var mx=1;bids.concat(asks).forEach(function(l){if(l.s>mx)mx=l.s;});
 var dh='<div style="display:grid;grid-template-columns:1fr 70px 1fr;gap:1px;font-size:11px">';
 for(var i=Math.min(4,asks.length-1);i>=0;i--){var l=asks[i];
  dh+='<span></span><span style="text-align:right;color:var(--redB);padding:0 4px">'+fmt2(l.p)+'</span>'
   +'<span style="position:relative"><i style="position:absolute;left:0;top:2px;bottom:2px;width:'+(l.s/mx*100)+'%;background:rgba(226,72,77,.25);border-radius:1px"></i><i style="position:relative;color:var(--redB);padding-left:4px;font-style:normal">'+fmt2(l.s,1)+'</i></span>';}
 var spd=(asks[0]&&bids[0])?(asks[0].p-bids[0].p):0;
 dh+='<span></span><span style="text-align:right;color:var(--t2);border-top:1px solid var(--bd2);border-bottom:1px solid var(--bd2);padding:1px 4px">'+fmt2(spd)+'</span><span style="border-top:1px solid var(--bd2);border-bottom:1px solid var(--bd2)"></span>';
 for(var i=0;i<Math.min(5,bids.length);i++){var l=bids[i];
  dh+='<span style="position:relative"><i style="position:absolute;right:0;top:2px;bottom:2px;width:'+(l.s/mx*100)+'%;background:rgba(46,189,133,.22);border-radius:1px"></i></span>'
   +'<span style="text-align:right;color:var(--grnB);padding:0 4px">'+fmt2(l.p)+'</span><span style="color:var(--grnB);padding-left:4px">'+fmt2(l.s,1)+'</span>';}
 dh+='</div>';el('dom').innerHTML=(bids.length||asks.length)?dh:'<span class="d">no depth (L2 quiet)</span>';
 var imb=safe(J.l2_gold,0.5);el('obiv').textContent=fmt2(imb,3);
 var ob=el('obib'),dev=imb-0.5;ob.style.left=dev>=0?'50%':(50+dev*100)+'%';ob.style.width=Math.abs(dev)*100+'%';
 ob.style.background=dev>=0?'var(--grn)':'var(--red)';

 el('micro').innerHTML=[['Quote msg/s',safe(J.quote_msg_rate),'w'],['Seq gaps',safe(J.sequence_gaps),safe(J.sequence_gaps)>0?'r':'g'],
  ['RTT last ms',fmt2(J.fix_rtt_last,1),'w'],['RTT p50',fmt2(J.fix_rtt_p50,1),'w'],['RTT p95',fmt2(J.fix_rtt_p95,1),safe(J.fix_rtt_p95)>120?'a':'w'],
  ['L2 books live',safe(J.l2_active),'w']].map(function(r){return '<span>'+r[0]+'</span><span class="'+r[2]+'">'+r[1]+'</span>';}).join('');
 var bk=J.broker||{};
 el('broker').innerHTML=[['Engine PnL',fmt$(safe(bk.engine_pnl)),'w'],['Broker realised',fmt$(safe(bk.realised_pnl)),'w'],
  ['Disparity',fmt$(safe(bk.disparity)),Math.abs(safe(bk.disparity))>50?'r':'g'],
  ['Orphans',safe(bk.orphan_count),safe(bk.orphan_count)>0?'r':'d'],['Rejects',safe(bk.reject_count),safe(bk.reject_count)>0?'a':'d'],
  ['Confirmed',safe(bk.confirmed_count),'d']].map(function(r){return '<span>'+r[0]+'</span><span class="'+r[2]+'">'+r[1]+'</span>';}).join('');

 var sig0=(J.signal_history||[])[0];
 if(sig0){var sk=sig0.symbol+'|'+sig0.engine+'|'+sig0.price;
  if(window._lastSig===undefined)window._lastSig=sk;
  else if(window._lastSig!==sk){window._lastSig=sk;sigTick();}}
 var sh=(J.signal_history||[]).slice(0,9).map(function(s){
  var c=s.side==='LONG'||s.side==='BUY'?'g':'r';
  return '<div><span class="'+c+'">'+esc(s.side||'')+'</span> <span class="w">'+esc(s.symbol||'')+'</span> '
   +'<span class="num">'+fmt2(s.price,2)+'</span> <span class="d">'+esc(s.engine||'')+'</span> <span class="d">'+esc(s.reason||'').slice(0,28)+'</span></div>';}).join('');
 el('sigs').innerHTML=sh||'<span class="d">no signals yet this session</span>';

 var lts=J.live_trades||[];
 /* entry bell -- identity-based (engine|symbol|side|entry), NOT count-based.
    Count-based rang on restarts + source flicker (2026-06-11 phantom-bell bug).
    Guards: first render baselines silently; uptime drop (restart) re-baselines
    silently; a key re-appearing within 90s does not re-ring. */
 (function(){var now=Date.now();
  if(window._seenTr===undefined){window._seenTr={};window._trBase=true;}
  var up=safe(J.uptime_sec);
  if(window._lastUp!==undefined&&up<window._lastUp-5)window._trBase=true;
  window._lastUp=up;
  var fresh=0;
  lts.forEach(function(t){var k=(t.engine||'')+'|'+(t.symbol||'')+'|'+(t.side||'')+'|'+fmt2(t.entry,4);
   if(!(k in window._seenTr)||(now-window._seenTr[k])>90000){if(!window._trBase)fresh++;}
   window._seenTr[k]=now;});
  for(var k in window._seenTr){if(now-window._seenTr[k]>600000)delete window._seenTr[k];}
  if(fresh>0&&!window._trBase){entryBell();flashPan('ltpan');}
  window._trBase=false;})();
 if(!lts.length){
  /* tick-driven publisher goes quiet when the market is closed -- positions can
     still be OPEN (held over the weekend). Fall back to the position REGISTRY
     served by the read-API on :7781 so the desk never shows a phantom FLAT. */
  if(REGPOS.length){var sum2=0;var rows2=REGPOS.map(function(t){sum2+=safe(t.unrealized_pnl);
   return '<tr><td class="l">'+esc(t.symbol)+'</td><td class="l">'+esc((t.engine||'').replace(/Engine$/,''))+'</td><td class="'+(t.side==='LONG'?'g':'r')+'">'+esc(t.side)+'</td>'
    +'<td class="num d">'+lots(t.size)+'</td>'
    +'<td class="num">'+fmt2(t.entry)+'</td><td class="num d">'+fmt2(t.current)+'</td>'
    +'<td class="num '+(safe(t.unrealized_pnl)>=0?'g':'r')+'">'+fmt$(safe(t.unrealized_pnl))+'</td></tr>';}).join('');
   el('lt').innerHTML='<tr><th class="l">sym</th><th class="l">engine</th><th>side</th><th>lots</th><th>entry</th><th>last</th><th>unreal</th></tr>'+rows2;
   el('ltcount').textContent=REGPOS.length+' open · from registry (feed quiet — prices stale)';
   el('ltpnl').textContent='';}
)OMEGAD1"
R"OMEGAD2(  else{el('lt').innerHTML='<tr><td class="l d">FLAT — no open positions</td></tr>';el('ltpnl').textContent='';el('ltcount').textContent='';}}
 else{el('ltcount').textContent=lts.length+' open';
  var sum=0;var rows=lts.map(function(t){sum+=safe(t.live_pnl);
  return '<tr><td class="l">'+esc(t.symbol)+'</td><td class="l">'+esc(t.engine)+'</td><td class="'+(t.side==='LONG'?'g':'r')+'">'+esc(t.side)+'</td>'
   +'<td class="num d">'+lots(t.size)+'</td>'
   +'<td class="num">'+fmt2(t.entry)+'</td><td class="num">'+fmt2(t.current)+'</td>'
   +'<td class="num '+(t.live_pnl>=0?'g':'r')+'">'+fmt$(safe(t.live_pnl))+'</td>'
   +'<td class="num">'+Math.floor(safe(t.held_sec)/60)+'m</td><td class="num">'+fmt2(t.dist_sl,1)+'</td><td class="num">'+fmt2(t.dist_tp,1)+'</td></tr>';}).join('');
  el('lt').innerHTML='<tr><th class="l">sym</th><th class="l">engine</th><th>side</th><th>lots</th><th>entry</th><th>now</th><th>pnl</th><th>held</th><th>→SL</th><th>→TP</th></tr>'+rows;
  el('ltpnl').textContent=fmt$(sum)+' unrealised';el('ltpnl').style.color=sum>=0?'var(--grn)':'var(--red)';}
}

/* ── ws + poll ── */
var wsOk=false;
function setConn(ok,via){el('conn').style.background=ok?'var(--grn)':'var(--red)';el('connlbl').textContent=ok?via:'offline';}
(function ws(){try{var s=new WebSocket('ws://'+location.hostname+':7780');
 s.onmessage=function(e){try{render(JSON.parse(e.data));wsOk=true;setConn(true,'ws');}catch(x){}};
 s.onclose=function(){wsOk=false;setConn(false);setTimeout(ws,3000);};
 s.onerror=function(){wsOk=false;};}catch(e){wsOk=false;}})();
function poll(){if(wsOk)return;fetch('/api/telemetry').then(function(r){return r.json();}).then(function(j){render(j);setConn(true,'http');}).catch(function(){setConn(false);});}
setInterval(poll,1000);poll();

/* ── shadow csv analytics ── */
var ROWS=[],WIN=1;
function parseShadow(txt){
 /* HEADER-DRIVEN parse of omega_shadow.csv. The 06-12 rewrite hardcoded a
    12-column layout that never matched the real 41-column file (col 0 is
    trade_id, not ts) -> parseInt('0') falsy -> EVERY row skipped -> all
    analytics showed "$0 / no shadow closes". Map columns by header name. */
 var out=[];var ls=txt.split('\n');if(ls.length<2)return out;
 var hdr=ls[0].split(','),ix={};
 for(var h=0;h<hdr.length;h++)ix[hdr[h].trim()]=h;
 function need(n){return ix[n]!==undefined;}
 if(!need('exit_ts_unix')||!need('symbol')||!need('engine')||!need('net_pnl'))return out;
 function unq(v){v=(v||'').trim();return v[0]==='"'?v.slice(1,-1):v;}
 for(var i=1;i<ls.length;i++){var L=ls[i];if(!L)continue;var f=L.split(',');
  if(f.length<hdr.length-2)continue;
  var ts=parseInt(f[ix.exit_ts_unix],10);if(!ts)continue;
  var sym=unq(f[ix.symbol]),eng=unq(f[ix.engine]);
  if(sym==='__BOOT__'||eng==='boot_writetest')continue;
  var side=unq(f[ix.side]);if(side==='BUY')side='LONG';if(side==='SELL')side='SHORT';
  out.push({ts:ts,sym:sym,side:side,eng:eng,
   ets:ix.entry_ts_unix!==undefined?(parseInt(f[ix.entry_ts_unix],10)||0):0,
   epx:ix.entry_px!==undefined?(parseFloat(f[ix.entry_px])||0):0,
   xpx:ix.exit_px!==undefined?(parseFloat(f[ix.exit_px])||0):0,
   pnl:parseFloat(f[ix.net_pnl])||0,
   size:ix.size!==undefined?(parseFloat(f[ix.size])||0):0,
   mfe:ix.mfe!==undefined?(parseFloat(f[ix.mfe])||0):0,
   mae:ix.mae!==undefined?(parseFloat(f[ix.mae])||0):0,
   hold:ix.hold_sec!==undefined?(parseInt(f[ix.hold_sec],10)||0):0,
   reason:ix.exit_reason!==undefined?unq(f[ix.exit_reason]):'',
   spread:ix.spread_at_entry!==undefined?(parseFloat(f[ix.spread_at_entry])||0):0,
   lat:ix.latency_ms!==undefined?(parseFloat(f[ix.latency_ms])||0):0});}
 out.sort(function(a,b){return a.ts-b.ts;});return out;}
function winRows(){if(WIN>=9999)return ROWS;
 var cut=WIN===1?(Math.floor(Date.now()/86400000)*86400):(Date.now()/1000-WIN*86400);
 return ROWS.filter(function(r){return r.ts>=cut;});}
function updDayPnl(){var cut=Math.floor(Date.now()/86400000)*86400;var n=0,p=0,tot=0;
 ROWS.forEach(function(r){tot+=r.pnl;if(r.ts>=cut){n++;p+=r.pnl;}});
 tweenNum('daypnl',p,fmt$);el('daypnl').style.color=p>=0?'var(--grn)':'var(--red)';
 el('daypnln').textContent=n+' closes today (UTC)';
 tweenNum('totpnl',tot,fmt$);el('totpnl').style.color=tot>=0?'var(--grn)':'var(--red)';}

/* ── engine ledger: ALL-TIME running totals per engine (window-independent) ── */
function drawLedger(){var t=el('ledger');if(!ROWS.length){t.innerHTML='<tr><td class="l d">no closes in ledger</td></tr>';el('ledgern').textContent='';return;}
 var by={};
 ROWS.forEach(function(r){var k=r.eng||'?';if(!by[k])by[k]={n:0,pnl:0,w:0,sym:r.sym,last:0};
  var e=by[k];e.n++;e.pnl+=r.pnl;if(r.pnl>0)e.w++;if(r.ts>e.last){e.last=r.ts;e.sym=r.sym;}});
 var ks=Object.keys(by).sort(function(a,b){return by[b].pnl-by[a].pnl;});
 var mx=1;ks.forEach(function(k){mx=Math.max(mx,Math.abs(by[k].pnl));});
 var rows=ks.map(function(k){var e=by[k],c=e.pnl>=0?'g':'r';
  var w=Math.max(2,Math.abs(e.pnl)/mx*100);
  return '<tr><td class="l" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:170px" title="'+esc(k)+'">'+esc(k.replace(/Engine$/,''))+'</td>'
   +'<td class="l d">'+esc(e.sym)+'</td><td class="num d">'+e.n+'</td>'
   +'<td class="num d">'+Math.round(100*e.w/e.n)+'%</td>'
   +'<td class="num '+c+'">'+fmt$(e.pnl)+'</td>'
   +'<td style="width:90px"><span class="bar" style="display:block"><i style="width:'+w+'%;background:'+(e.pnl>=0?'var(--grn)':'var(--red)')+'"></i></span></td>'
   +'<td class="num '+(e.pnl>=0?'g':'r')+'">'+fmt$(e.pnl/e.n)+'/t</td></tr>';}).join('');
 t.innerHTML='<tr><th class="l">engine</th><th class="l">sym</th><th>n</th><th>WR</th><th>net</th><th></th><th>avg</th></tr>'+rows;
 var net=0;ks.forEach(function(k){net+=by[k].pnl;});
 el('ledgern').textContent=ks.length+' engines · net '+fmt$(net);}

function drawEquity(){var cv=el("eqc"),H=110,ctx=prep(cv,H);
 var W=cv.clientWidth;ctx.clearRect(0,0,W,H);
 var rs=winRows();if(!rs.length){ctx.fillStyle='#6B7785';ctx.font='11px IBM Plex Mono';ctx.fillText('no shadow closes in window',10,20);_tw.eqtot=0;el('eqtot').textContent='$0';el('eqstats').innerHTML='';return;}
 var cum=[],c=0,pk=0,mdd=0,wins=0,gp=0,gl=0;
 rs.forEach(function(r){c+=r.pnl;cum.push(c);pk=Math.max(pk,c);mdd=Math.min(mdd,c-pk);
  if(r.pnl>0){wins++;gp+=r.pnl;}else gl-=r.pnl;});
 var lo=Math.min(0,mdd,Math.min.apply(null,cum)),hi=Math.max.apply(null,cum.concat([1]));
 function X(i){return 4+(W-8)*i/Math.max(1,cum.length-1);}
 function Y(v){return 8+(H-26)*(1-(v-lo)/(hi-lo||1));}
 ctx.strokeStyle='rgba(255,255,255,0.06)';ctx.beginPath();
 [lo,0,hi].forEach(function(g){ctx.moveTo(0,Y(g));ctx.lineTo(W,Y(g));});ctx.stroke();
 ctx.fillStyle='#6B7785';ctx.font='9px IBM Plex Mono';
 ctx.fillText(fmt$(hi),2,Y(hi)+9);ctx.fillText('$0',2,Y(0)-3);
 /* gradient area fill under the curve */
 ctx.beginPath();cum.forEach(function(v,i){i?ctx.lineTo(X(i),Y(v)):ctx.moveTo(X(0),Y(v));});
 ctx.lineTo(X(cum.length-1),Y(0));ctx.lineTo(X(0),Y(0));ctx.closePath();
 var gr=ctx.createLinearGradient(0,Y(hi),0,Y(Math.min(0,lo)));
 gr.addColorStop(0,'rgba(46,189,133,0.22)');gr.addColorStop(1,'rgba(46,189,133,0.02)');
 ctx.fillStyle=gr;ctx.fill();
 /* glowing equity line + live endpoint dot */
 ctx.save();ctx.shadowColor='#2EBD85';ctx.shadowBlur=6;
 ctx.beginPath();cum.forEach(function(v,i){i?ctx.lineTo(X(i),Y(v)):ctx.moveTo(X(0),Y(v));});
 ctx.strokeStyle='#2EBD85';ctx.lineWidth=1.6;ctx.lineJoin='round';ctx.stroke();ctx.restore();
 var ex=X(cum.length-1),ey=Y(cum[cum.length-1]);
 ctx.beginPath();ctx.arc(ex,ey,3,0,6.3);ctx.fillStyle='#2EBD85';ctx.fill();
 ctx.beginPath();ctx.arc(ex,ey,6,0,6.3);ctx.strokeStyle='rgba(46,189,133,0.35)';ctx.lineWidth=1.5;ctx.stroke();
 var p2=0;ctx.beginPath();cum.forEach(function(v,i){p2=Math.max(p2,v);var d=v-p2;i?ctx.lineTo(X(i),Y(d)):ctx.moveTo(X(0),Y(d));});
 ctx.strokeStyle='#E2484D';ctx.setLineDash([4,3]);ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);
 var net=cum[cum.length-1];tweenNum('eqtot',net,fmt$);el('eqtot').style.color=net>=0?'var(--grn)':'var(--red)';
 var pf=gl>0?gp/gl:0,wr=100*wins/rs.length;
 el('eqstats').innerHTML='<span>n <span class="w">'+rs.length+'</span></span><span>PF <span class="w">'+fmt2(pf)+'</span></span>'
  +'<span>WR <span class="w">'+fmt2(wr,1)+'%</span></span><span>maxDD <span class="r">'+fmt$(mdd)+'</span></span>'
  +'<span>avg <span class="w">'+fmt$(net/rs.length)+'</span></span>';}

function classOf(sym){if(/XAU|MGC|GOLD/i.test(sym))return 'GOLD';
 if(/US500|USTEC|NAS|DJ30|GER|UK100|ESTX|US30/i.test(sym))return 'INDEX';
 if(/USD|EUR|GBP|AUD|NZD|JPY/.test(sym)&&sym.length===6)return 'FX';
 if(/XAG|SILVER/i.test(sym))return 'SILVER';
 if(/OIL|BRENT|CL/i.test(sym))return 'OIL';return 'OTHER';}
function drawHeat(){var rs=winRows();var by={};
 rs.forEach(function(r){var k=r.eng||'?';if(!by[k])by[k]={n:0,pnl:0,sym:r.sym};by[k].n++;by[k].pnl+=r.pnl;});
 var ks=Object.keys(by);if(!ks.length){el('heat').innerHTML='<span class="d">no engine activity in window</span>';return;}
 var groups={};ks.forEach(function(k){var g=classOf(by[k].sym);(groups[g]=groups[g]||[]).push(k);});
 var mxAbs=1;ks.forEach(function(k){mxAbs=Math.max(mxAbs,Math.abs(by[k].pnl));});
 var order=['GOLD','INDEX','FX','SILVER','OIL','OTHER'],h='';
 order.forEach(function(g){if(!groups[g])return;
  groups[g].sort(function(a,b){return by[b].pnl-by[a].pnl;});
  h+='<div class="lbl" style="margin:6px 0 3px">'+g+(g==='FX'?' — no proven edge':'')+' <span style="color:var(--t3)">'+groups[g].length+' active</span></div>'
   +'<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(76px,1fr));gap:3px">';
  groups[g].forEach(function(k){var e=by[k],t=e.pnl/mxAbs;
   var bg='#1d2733',fg='#8B97A5';
   if(e.pnl>1){bg=t>0.4?'#0F6E56':'#0a4434';fg='#9FE1CB';}
   else if(e.pnl<-1){bg=t<-0.4?'#A32D2D':'#5c1f1f';fg='#F7C1C1';}
   var nm=k.replace(/Engine$/,'');
   h+='<div class="tile" style="background:'+bg+'" title="'+esc(k)+' n='+e.n+' pnl='+fmt$(e.pnl)+'">'
    +'<b style="color:'+fg+'">'+esc(nm)+'</b><span class="num" style="color:'+fg+'">'+fmt$(e.pnl)+' · '+e.n+'</span></div>';});
  h+='</div>';});
 el('heat').innerHTML=h;}

function fillSymSel(){var by={};ROWS.forEach(function(r){by[r.sym]=(by[r.sym]||0)+1;});
 var syms=Object.keys(by).sort(function(a,b){return by[b]-by[a];}).slice(0,8);
 var s=el('mmsym');var cur=s.value;
 s.innerHTML=syms.map(function(x){return '<option>'+esc(x)+'</option>';}).join('');
 if(syms.indexOf(cur)>=0)s.value=cur;}
function drawMM(){var cv=el('mmc'),H=190,ctx=prep(cv,H);
 var W=cv.clientWidth;ctx.clearRect(0,0,W,H);
 var sym=el('mmsym').value;var rs=winRows().filter(function(r){return r.sym===sym;}).slice(-400);
 if(!rs.length){ctx.fillStyle='#6B7785';ctx.font='11px IBM Plex Mono';ctx.fillText('no trades for '+sym,10,20);return;}
 var xs=rs.map(function(r){return r.mae;}),ys=rs.map(function(r){return r.mfe;});
 function pct(a,p){var b=a.slice().sort(function(x,y){return x-y;});return b[Math.min(b.length-1,Math.floor(p*b.length))];}
 var mx=Math.max(pct(xs,0.97),0.1),my=Math.max(pct(ys,0.97),0.1);
 function X(v){return 26+(W-34)*Math.min(1,v/mx);}function Y(v){return H-18-(H-30)*Math.min(1,v/my);}
 ctx.strokeStyle='rgba(255,255,255,0.07)';ctx.strokeRect(26,12,W-34,H-30);
 ctx.fillStyle='#6B7785';ctx.font='9px IBM Plex Mono';
 ctx.fillText('MAE '+fmt2(mx,1),W-60,H-4);ctx.fillText('MFE',2,14);ctx.fillText(fmt2(my,1),2,24);
 rs.forEach(function(r){ctx.fillStyle=r.pnl>0?'rgba(46,189,133,0.75)':'rgba(226,72,77,0.75)';
  ctx.beginPath();ctx.arc(X(r.mae),Y(r.mfe),2.2,0,6.3);ctx.fill();});}

var DAYS=['Su','Mo','Tu','We','Th','Fr','Sa'];
function drawTOD(){var rs=ROWS;var grid={};
 rs.forEach(function(r){var d=new Date(r.ts*1000);var k=d.getUTCDay()+'_'+d.getUTCHours();
  if(!grid[k])grid[k]={n:0,w:0,pnl:0};grid[k].n++;if(r.pnl>0)grid[k].w++;grid[k].pnl+=r.pnl;});
 var h='<div style="display:grid;grid-template-columns:24px repeat(24,1fr);gap:1px">';
 h+='<span></span>';for(var c=0;c<24;c++)h+='<span class="lbl" style="font-size:8px;text-align:center">'+(c%4===0?c:'')+'</span>';
 [1,2,3,4,5,0].forEach(function(d){h+='<span class="lbl" style="font-size:9px">'+DAYS[d]+'</span>';
  for(var c=0;c<24;c++){var g=grid[d+'_'+c],bg='#141a22',ti='';
   if(g&&g.n>=2){var wr=g.w/g.n;
    bg=wr>0.58?'#0F6E56':wr>0.5?'#155446':wr>0.44?'#1d2733':wr>0.36?'#5c1f1f':'#A32D2D';
    ti=DAYS[d]+' '+c+':00 n='+g.n+' wr='+Math.round(wr*100)+'% pnl='+fmt$(g.pnl);}
   else if(g){bg='#1a212b';ti=DAYS[d]+' '+c+':00 n='+g.n;}
   h+='<span title="'+ti+'" style="height:13px;background:'+bg+';border-radius:1px"></span>';}});
 h+='</div>';el('tod').innerHTML=h;}

function drawPromo(){var by={};
 ROWS.forEach(function(r){var k=r.eng||'?';if(!by[k])by[k]={n:0,pnl:0,w:0};by[k].n++;by[k].pnl+=r.pnl;if(r.pnl>0)by[k].w++;});
 var ks=Object.keys(by).sort(function(a,b){return by[b].n-by[a].n;}).slice(0,14);
 if(!ks.length){el('promo').innerHTML='<span class="d">no shadow history yet</span>';return;}
 var GATE=30,h='';
 ks.forEach(function(k){var e=by[k],avg=e.pnl/e.n,ok=e.n>=GATE;
  var col=e.n<10?'var(--t2)':avg>0?(ok?'var(--grn)':'var(--ambB)'):'var(--red)';
  var tag=e.n<10?'n small':avg>0?(ok?'judgeable +EV':'building'):(ok?'judgeable −EV':'building');
  h+='<div style="display:grid;grid-template-columns:minmax(90px,1.4fr) 2fr 46px 64px 80px;gap:7px;align-items:center;margin-bottom:4px">'
   +'<span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis" title="'+esc(k)+'">'+esc(k.replace(/Engine$/,''))+'</span>'
   +'<span class="bar"><i style="width:'+Math.min(100,e.n/GATE*100)+'%;background:'+col+'"></i></span>'
   +'<span class="num d">'+e.n+'/'+GATE+'</span><span class="num" style="color:'+col+'">'+fmt$(avg)+'/t</span>'
   +'<span class="lbl" style="color:'+col+'">'+tag+'</span></div>';});
 el('promo').innerHTML=h;}

function drawBlot(){fetch('/api/shadow_trades').then(function(r){return r.json();}).then(function(a){
 if(!a||!a.length){return;}
 a=a.filter(function(t){return t.symbol!=='__BOOT__'&&t.engine!=='boot_writetest';});
)OMEGAD2"
R"OMEGAD3( if(!a.length){return;}
 var newest=safe(a[a.length-1].exitTs);
 if(window._lastClose===undefined)window._lastClose=newest;
 else if(newest>window._lastClose){
  var fresh=a.filter(function(t){return safe(t.exitTs)>window._lastClose;});
  var net=fresh.reduce(function(s,t){return s+safe(t.pnl);},0);
  window._lastClose=newest;
  if(net>=0)winBell();else lossBell();}
}).catch(function(){});}
function drawHist(){var h=el('hist');if(!ROWS.length){h.innerHTML='<tr><td class="l d">no closes in ledger</td></tr>';el('histn').textContent='';return;}
 var rows=ROWS.slice().reverse().map(function(r){
  var d=new Date(r.ts*1000);
  var dd=String(d.getUTCDate()).padStart(2,'0')+'.'+String(d.getUTCMonth()+1).padStart(2,'0')+' '
   +String(d.getUTCHours()).padStart(2,'0')+':'+String(d.getUTCMinutes()).padStart(2,'0');
  var hold=r.hold>=3600?Math.floor(r.hold/3600)+'h'+Math.floor(r.hold%3600/60)+'m':Math.floor(r.hold/60)+'m';
  return '<tr><td class="l num d">'+dd+'</td><td class="l">'+esc((r.eng||'').replace(/Engine$/,''))+'</td><td class="l">'+esc(r.sym)+'</td>'
   +'<td class="'+(r.side==='LONG'?'g':'r')+'">'+(r.side==='LONG'?'L':'S')+'</td>'
   +'<td class="num d">'+lots(r.size)+'</td>'
   +'<td class="num">'+fmt2(r.epx,r.epx<10?4:2)+'</td><td class="num">'+fmt2(r.xpx,r.xpx<10?4:2)+'</td>'
   +'<td class="num '+(r.pnl>=0?'g':'r')+'">'+fmt$(r.pnl)+'</td>'
   +'<td class="num d">'+hold+'</td><td class="l d">'+esc(r.reason||'')+'</td></tr>';}).join('');
 h.innerHTML='<tr><th class="l">utc</th><th class="l">engine</th><th class="l">sym</th><th>side</th><th>lots</th><th>entry</th><th>exit</th><th>pnl</th><th>held</th><th class="l">exit</th></tr>'+rows;
 el('histn').textContent=ROWS.length+' trades';}

/* ── predictive ranges ── */
var PRD=null,PRSYM=localStorage.getItem('omega_prsym')||'XAUUSD',PRTF=localStorage.getItem('omega_prtf')||'m15';
var PRSYMS=['XAUUSD','US500','USTEC'],PRTFS=[['m5','5m'],['m15','15m'],['h1','1H']];
function prBtns(){
 el('prsyms').innerHTML=PRSYMS.map(function(x){return '<button class="'+(x===PRSYM?'on':'')+'" data-s="'+x+'">'+x.replace('USD','')+'</button>';}).join('');
 el('prtfs').innerHTML=PRTFS.map(function(t){return '<button class="'+(t[0]===PRTF?'on':'')+'" data-t="'+t[0]+'">'+t[1]+'</button>';}).join('');
 Array.prototype.forEach.call(el('prsyms').children,function(b){b.onclick=function(){PRSYM=b.getAttribute('data-s');localStorage.setItem('omega_prsym',PRSYM);prBtns();drawPR();};});
 Array.prototype.forEach.call(el('prtfs').children,function(b){b.onclick=function(){PRTF=b.getAttribute('data-t');localStorage.setItem('omega_prtf',PRTF);prBtns();drawPR();};});}
prBtns();
var PRMK=[],PRMOUSE=null,PRHOVER=null;
function drawPR(){var cv=el("prc"),H=430,ctx=prep(cv,H);
 window._prDrawT=performance.now();
 var W=cv.clientWidth;ctx.clearRect(0,0,W,H);ctx.font='10px IBM Plex Mono';
 PRMK=[];window._prNewest=0;
 var ds=PRD&&PRD.datasets&&PRD.datasets[PRSYM]&&PRD.datasets[PRSYM][PRTF];
 if(!ds||!ds.bars||ds.bars.length<10){ctx.fillStyle='#6B7785';
  ctx.fillText('no range data yet — waiting for '+PRSYM+' '+PRTF+' bars (written every 60s by the engine)',10,20);
  el('prinfo').textContent='';el('prlast').textContent='';el('prtrend').textContent='';return;}
 var bars=ds.bars.slice(-Math.max(60,Math.min(ds.bars.length,Math.floor((W-70)/5))));
 var n=bars.length,padR=58,padB=18,padT=8,padL=4,pw=W-padL-padR,ph=H-padT-padB;
 var lo=1e18,hi=-1e18;
 // range from candles always; include r2/s2 ONLY when warmed (>0) so an unwarmed
 // 0-level bar can't collapse lo to 0 and squash the whole chart (was hiding bands).
 bars.forEach(function(b){lo=Math.min(lo,b[3]);hi=Math.max(hi,b[2]);
  if(b[9]>0)lo=Math.min(lo,b[9]); if(b[7]>0)hi=Math.max(hi,b[7]);});
 var pad=(hi-lo)*0.06||1;lo-=pad;hi+=pad;
 var dp=hi<100?3:hi<1000?2:1;
 function X(i){return padL+pw*i/Math.max(1,n-1);}
 function Y(v){return padT+ph*(1-(v-lo)/(hi-lo));}
 ctx.fillStyle='#6B7785';
 for(var g=0;g<=5;g++){var gy=padT+ph*g/5,gv=hi-(hi-lo)*g/5;
  ctx.strokeStyle='rgba(255,255,255,0.05)';ctx.beginPath();ctx.moveTo(padL,gy);ctx.lineTo(padL+pw,gy);ctx.stroke();
  ctx.fillText(gv.toFixed(dp),padL+pw+6,gy+3);}
 for(var t=0;t<=4;t++){var ii=Math.round((n-1)*t/4),d=new Date(bars[ii][0]*1000);
  var lb=String(d.getUTCDate()).padStart(2,'0')+'.'+String(d.getUTCMonth()+1).padStart(2,'0')+' '
   +String(d.getUTCHours()).padStart(2,'0')+':'+String(d.getUTCMinutes()).padStart(2,'0');
  ctx.strokeStyle='rgba(255,255,255,0.03)';ctx.beginPath();ctx.moveTo(X(ii),padT);ctx.lineTo(X(ii),padT+ph);ctx.stroke();
  ctx.fillText(lb,Math.min(X(ii),W-padR-62),H-4);}
 /* step points; emit null as a gap when a level is unwarmed (<=0) so the line
    never drops to Y(0)/off-chart (that was hiding resistance). */
 function spts(fi){var p=[];for(var i=0;i<n;i++){var v=bars[i][fi];
  if(v<=0){p.push(null);continue;}
  if(i>0&&bars[i-1][fi]>0&&bars[i-1][fi]!==v)p.push([X(i),Y(bars[i-1][fi])]);
  p.push([X(i),Y(v)]);}return p;}
 function strokeSteps(p,col,wd,dash){ctx.beginPath();var pen=false;p.forEach(function(q){
   if(!q){pen=false;return;}if(pen)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);pen=true;});
  ctx.strokeStyle=col;ctx.lineWidth=wd;ctx.setLineDash(dash||[]);ctx.stroke();ctx.setLineDash([]);}
 function cloud(fa,fb,col){var A=spts(fa).filter(Boolean),B=spts(fb).filter(Boolean);
  if(A.length<2||B.length<2)return;ctx.beginPath();
  A.forEach(function(q,i){i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]);});
  for(var i=B.length-1;i>=0;i--)ctx.lineTo(B[i][0],B[i][1]);
  ctx.closePath();ctx.fillStyle=col;ctx.fill();}
 cloud(7,6,'rgba(226,72,77,0.10)');cloud(8,9,'rgba(46,189,133,0.10)');cloud(6,8,'rgba(133,183,235,0.04)');
 strokeSteps(spts(7),'#FF5A5F',2.0);strokeSteps(spts(9),'#2EBD85',2.0);                 /* R2 / S2 solid, brighter+thicker */
 strokeSteps(spts(6),'rgba(255,90,95,0.85)',1.4,[5,4]);strokeSteps(spts(8),'rgba(46,189,133,0.85)',1.4,[5,4]); /* R1 / S1 dashed */
 var bw=Math.max(1,Math.min(7,pw/n*0.62));
 for(var i=0;i<n;i++){var b=bars[i],up=b[4]>=b[1],c=up?'#2EBD85':'#E2484D',x=X(i);
  ctx.strokeStyle=c;ctx.globalAlpha=0.85;ctx.lineWidth=bw>3?1:0.7;
  ctx.beginPath();ctx.moveTo(x,Y(b[2]));ctx.lineTo(x,Y(b[3]));ctx.stroke();ctx.globalAlpha=1;
  var yt=Math.min(Y(b[1]),Y(b[4])),hh=Math.max(1.2,Math.abs(Y(b[1])-Y(b[4])));
  ctx.globalAlpha=0.92;ctx.fillStyle=c;ctx.fillRect(x-bw/2,yt,bw,hh);ctx.globalAlpha=1;}
 var ap=spts(5);
 ctx.save();ctx.shadowColor='#85B7EB';ctx.shadowBlur=7;strokeSteps(ap,'rgba(133,183,235,0.45)',3.5);ctx.restore();
 strokeSteps(ap,'#85B7EB',1.8);
 /* current-level labels on the right edge (R2/R1/PR/S1/S2) -- clarity */
 (function(){var lb=bars[n-1],defs=[[7,'R2','#FF5A5F'],[6,'R1','#FF8A8E'],[5,'PR','#85B7EB'],[8,'S1','#7FD9B0'],[9,'S2','#2EBD85']];
  ctx.font='9px IBM Plex Mono';ctx.textAlign='left';
  defs.forEach(function(d){var v=lb[d[0]];if(v<=0)return;var y=Y(v);if(y<padT||y>padT+ph)return;
   var tx=padL+pw+2,txt=d[1]+' '+v.toFixed(dp);
   ctx.fillStyle='rgba(11,15,20,0.85)';ctx.fillRect(tx,y-6,54,11);
   ctx.fillStyle=d[2];ctx.fillRect(tx,y-6,2,11);ctx.fillText(txt,tx+5,y+3);});
  ctx.textAlign='start';})();
 for(var i=0;i<n;i++){var sg=bars[i][11];if(!sg)continue;var x=X(i),y;
  ctx.beginPath();
  if(sg>0){y=Y(bars[i][3])+11;ctx.moveTo(x,y-7);ctx.lineTo(x-4.5,y);ctx.lineTo(x+4.5,y);ctx.fillStyle='#2EBD85';}
  else{y=Y(bars[i][2])-11;ctx.moveTo(x,y+7);ctx.lineTo(x-4.5,y);ctx.lineTo(x+4.5,y);ctx.fillStyle='#E2484D';}
  ctx.closePath();ctx.fill();}
 /* ── closed-trade overlay v2: glowing entry triangles, ringed exits,
    gradient connectors, PnL pills, hover hit-zones (PRMK), pulse on the
    newest exit. Trades come from the shadow ledger (ROWS). ── */
 (function(){
  if(typeof ROWS==='undefined'||!ROWS.length)return;
  var t0=bars[0][0],t1=bars[n-1][0]+ (bars[1]?bars[1][0]-bars[0][0]:300);
  function sm(sym){return sym===PRSYM||sym===PRSYM+'.F'||(PRSYM==='US500'&&sym==='US500.F')||(PRSYM==='USTEC'&&sym==='USTEC.F');}
  function bx(ts){var lo=0,hi=n-1;
   while(lo<hi){var mid=(lo+hi)>>1;if(bars[mid][0]<ts)lo=mid+1;else hi=mid;}
   return lo;}
  var vis=ROWS.filter(function(r){return sm(r.sym)&&r.ets&&r.epx&&!(r.ets>t1||r.ts<t0);});
  var nx=0,exVis=0;
  vis.forEach(function(r){if(r.ts<=t1){exVis++;if(r.ts>nx)nx=r.ts;}});
  window._prNewest=nx;
  if(!vis.length){   /* no closes inside the visible bar window -- say when the last one was */
   var lastR=null;
   ROWS.forEach(function(r){if(sm(r.sym)&&(!lastR||r.ts>lastR.ts))lastR=r;});
   if(lastR){var dd2=(Date.now()/1000-lastR.ts)/86400;
    var note='no '+PRSYM.replace('USD','')+' closes in window — last '
     +(dd2>=1?Math.round(dd2)+'d':Math.round(dd2*24)+'h')+' ago '+fmt$(lastR.pnl)
     +' ('+(lastR.eng||'').replace(/Engine$/,'')+')';
    ctx.font='10px IBM Plex Mono';
    var nw=ctx.measureText(note).width;
    ctx.fillStyle='rgba(11,15,20,0.8)';ctx.fillRect(padL+pw-nw-12,padT+2,nw+10,14);
    ctx.fillStyle='#6B7785';ctx.fillText(note,padL+pw-nw-7,padT+12);}
   return;}
  var pills=exVis<=14;   /* suppress $ labels when the window is crowded */
  vis.forEach(function(r,vi){
   var win=r.pnl>=0,c=win?'#2EBD85':'#E2484D';
   var hov=PRHOVER&&PRHOVER.t===r;
   var xe=X(bx(r.ets)),ye=Y(r.epx);
   var xx=X(bx(r.ts)), yx=Y(r.xpx||r.epx);
   if(r.ets>=t0&&r.ts<=t1&&(Math.abs(xx-xe)>1||Math.abs(yx-ye)>1)){
    var gr2=ctx.createLinearGradient(xe,ye,xx,yx);
    gr2.addColorStop(0,win?'rgba(46,189,133,0.18)':'rgba(226,72,77,0.18)');
    gr2.addColorStop(1,win?'rgba(46,189,133,0.8)':'rgba(226,72,77,0.8)');
    ctx.strokeStyle=gr2;ctx.lineWidth=hov?2:1.3;ctx.setLineDash([5,3]);
    ctx.beginPath();ctx.moveTo(xe,ye);ctx.lineTo(xx,yx);ctx.stroke();ctx.setLineDash([]);}
   if(r.ets>=t0){var s=hov?8:6;   /* entry: glow triangle, up=LONG / down=SHORT */
    ctx.save();ctx.shadowColor=c;ctx.shadowBlur=hov?12:7;
    ctx.beginPath();
    if(r.side==='LONG'){ctx.moveTo(xe,ye-s);ctx.lineTo(xe-s*0.85,ye+s*0.6);ctx.lineTo(xe+s*0.85,ye+s*0.6);}
    else{ctx.moveTo(xe,ye+s);ctx.lineTo(xe-s*0.85,ye-s*0.6);ctx.lineTo(xe+s*0.85,ye-s*0.6);}
    ctx.closePath();ctx.fillStyle=c;ctx.fill();ctx.restore();
    ctx.strokeStyle='#0B0F14';ctx.lineWidth=1;ctx.stroke();
    PRMK.push({x:xe,y:ye,t:r});}
   if(r.ts<=t1){   /* exit: glow ring + core dot */
    ctx.save();ctx.shadowColor=c;ctx.shadowBlur=hov?12:7;
    ctx.beginPath();ctx.arc(xx,yx,hov?5:4,0,6.3);
    ctx.fillStyle='#0B0F14';ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=1.8;ctx.stroke();ctx.restore();
    ctx.beginPath();ctx.arc(xx,yx,1.5,0,6.3);ctx.fillStyle=c;ctx.fill();
    if(r.ts===nx&&(Date.now()/1000-nx)<600){   /* pulse halo, anim loop redraws */
     var p=(performance.now()%1400)/1400;
     ctx.beginPath();ctx.arc(xx,yx,5+p*11,0,6.3);
     ctx.strokeStyle=c;ctx.globalAlpha=(1-p)*0.55;ctx.lineWidth=1.6;ctx.stroke();ctx.globalAlpha=1;}
    if(pills||hov){var txt=fmt$(r.pnl);ctx.font='9px IBM Plex Mono';
     var tw2=ctx.measureText(txt).width,bx2=Math.min(xx+7,W-padR-tw2-8),by2=yx+(vi%2?12:-22);
     by2=Math.max(padT+2,Math.min(by2,padT+ph-12));
     ctx.globalAlpha=hov?1:0.92;
     ctx.fillStyle='rgba(11,15,20,0.85)';ctx.beginPath();
     if(ctx.roundRect)ctx.roundRect(bx2-4,by2,tw2+8,11,3);else ctx.rect(bx2-4,by2,tw2+8,11);
     ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=0.8;ctx.stroke();
     ctx.fillStyle=c;ctx.fillText(txt,bx2,by2+8.5);ctx.globalAlpha=1;ctx.font='10px IBM Plex Mono';}
    PRMK.push({x:xx,y:yx,t:r});}
  });
 })();
 /* ── crosshair + OHLC readout ── */
 if(PRMOUSE&&PRMOUSE.x>=padL&&PRMOUSE.x<=padL+pw&&PRMOUSE.y>=padT&&PRMOUSE.y<=padT+ph){
  var mi=Math.max(0,Math.min(n-1,Math.round((PRMOUSE.x-padL)/pw*(n-1))));
  var mb=bars[mi],mx2=X(mi);
  ctx.strokeStyle='rgba(230,237,243,0.22)';ctx.setLineDash([3,3]);ctx.lineWidth=1;
  ctx.beginPath();ctx.moveTo(mx2,padT);ctx.lineTo(mx2,padT+ph);ctx.stroke();
  ctx.beginPath();ctx.moveTo(padL,PRMOUSE.y);ctx.lineTo(padL+pw,PRMOUSE.y);ctx.stroke();ctx.setLineDash([]);
  var pv=hi-(PRMOUSE.y-padT)/ph*(hi-lo);
  ctx.fillStyle='#1F2937';ctx.fillRect(padL+pw+2,PRMOUSE.y-8,padR-6,15);
  ctx.fillStyle='#E6EDF3';ctx.fillText(pv.toFixed(dp),padL+pw+6,PRMOUSE.y+3);
  var md=new Date(mb[0]*1000);
  var ohlc='O '+mb[1].toFixed(dp)+'  H '+mb[2].toFixed(dp)+'  L '+mb[3].toFixed(dp)+'  C '+mb[4].toFixed(dp)
   +'   '+String(md.getUTCDate()).padStart(2,'0')+'.'+String(md.getUTCMonth()+1).padStart(2,'0')+' '
   +String(md.getUTCHours()).padStart(2,'0')+':'+String(md.getUTCMinutes()).padStart(2,'0');
  ctx.fillStyle='rgba(11,15,20,0.8)';ctx.fillRect(padL+4,padT+2,ctx.measureText(ohlc).width+10,14);
  ctx.fillStyle=mb[4]>=mb[1]?'#9FE1CB':'#F7C1C1';ctx.fillText(ohlc,padL+9,padT+12);}
 var lastC=bars[n-1][4],yl=Y(lastC),trend=0;
 for(var i=n-1;i>=0;i--){if(bars[i][10]){trend=bars[i][10];break;}}
 var tc=trend>0?'#2EBD85':trend<0?'#E2484D':'#85B7EB';
 ctx.strokeStyle=tc;ctx.globalAlpha=0.5;ctx.setLineDash([2,4]);
 ctx.beginPath();ctx.moveTo(padL,yl);ctx.lineTo(padL+pw,yl);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;
 ctx.fillStyle=tc;ctx.fillRect(padL+pw+2,yl-8,padR-6,16);
 ctx.fillStyle='#0B0F14';ctx.fillText(lastC.toFixed(dp),padL+pw+6,yl+3.5);
 el('prlast').textContent=lastC.toFixed(dp);
 var pt=el('prtrend');
 pt.textContent=trend>0?'▲ STEP UP':trend<0?'▼ STEP DOWN':'■ RANGING';
 pt.style.color=trend>0?'var(--grnB)':trend<0?'var(--redB)':'var(--t2)';
 pt.style.background=trend>0?'var(--grnD)':trend<0?'var(--redD)':'var(--pan2)';
 var age=PRD.updated?Math.max(0,Math.round(Date.now()/1000-PRD.updated)):-1;
 el('prinfo').textContent='ATR'+ds.len+' ×'+ds.factor+' · rng×'+ds.rmult+' · '+ds.source+(age>=0?' · '+age+'s ago':'');}
function loadPR(){fetch('/api/predictive_ranges').then(function(r){return r.json();}).then(function(j){PRD=j;requestAnimationFrame(drawPR);}).catch(function(){});}
loadPR();setInterval(loadPR,30000);

/* ── PR chart interactivity: marker hover tooltip + crosshair + pulse loop ── */
function prTip(m,cx,cy){var tip=el('prtip');
 if(!m){tip.style.display='none';return;}
)OMEGAD3"
R"OMEGAD4( var r=m.t,c=r.pnl>=0?'var(--grn)':'var(--red)';
 var hold=r.hold>=3600?Math.floor(r.hold/3600)+'h'+Math.floor(r.hold%3600/60)+'m':Math.floor(r.hold/60)+'m';
 var dpp=r.epx<10?4:2;
 var isPart=/^PARTIAL/.test(r.reason||'');
 tip.innerHTML='<span class="w">'+esc((r.eng||'').replace(/Engine$/,''))+'</span> · <span class="'+(r.side==='LONG'?'g':'r')+'">'+esc(r.side)+'</span> '+esc(r.sym)
  +(isPart?' <span class="chip" style="background:var(--ambD);color:var(--ambB)">PARTIAL</span>':'')
  +'<br>in <span class="num w">'+fmt2(r.epx,dpp)+'</span> → out <span class="num w">'+fmt2(r.xpx,dpp)+'</span> · <span class="num w">'+lots(r.size)+'</span> lots'
  +'<br><span class="num" style="color:'+c+';font-weight:600">'+fmt$(r.pnl)+'</span> · '+hold+' · <span class="d">'+esc(r.reason||'')+'</span>'
  +(isPart?'<br><span class="d">partial bank — rest of position closed separately / may still be open</span>':'');
 tip.style.display='block';
 var tw2=tip.offsetWidth,th2=tip.offsetHeight;
 tip.style.left=Math.min(window.innerWidth-tw2-8,cx+14)+'px';
 tip.style.top=(cy-th2-12<0?cy+18:cy-th2-12)+'px';}
(function(){var cvp=el('prc');
 cvp.addEventListener('mousemove',function(e){var rc=cvp.getBoundingClientRect();
  PRMOUSE={x:e.clientX-rc.left,y:e.clientY-rc.top};
  var hit=null,best=160;
  PRMK.forEach(function(m){var dx=m.x-PRMOUSE.x,dy=m.y-PRMOUSE.y,d2=dx*dx+dy*dy;
   if(d2<best){best=d2;hit=m;}});
  PRHOVER=hit;prTip(hit,e.clientX,e.clientY);});
 cvp.addEventListener('mouseleave',function(){PRMOUSE=null;PRHOVER=null;prTip(null);drawPR();});})();
/* ~30fps redraw only while hovering, or while the newest exit (<10 min) pulses;
   paused when the tab is hidden. Static otherwise — zero idle cost. */
(function prAnim(){requestAnimationFrame(prAnim);
 if(document.hidden)return;
 if(performance.now()-(window._prDrawT||0)<33)return;
 if(PRMOUSE||(window._prNewest&&(Date.now()/1000-window._prNewest)<600))drawPR();})();

function redrawAll(){drawEquity();drawHeat();drawMM();drawTOD();drawPromo();updDayPnl();drawPR();drawHist();drawLedger();}
function loadCsv(){fetch('/api/shadow_csv').then(function(r){return r.text();}).then(function(t){
 ROWS=parseShadow(t);el('csvinfo').textContent=ROWS.length+' shadow closes loaded';
 fillSymSel();redrawAll();}).catch(function(){el('csvinfo').textContent='shadow csv unavailable';});}
loadCsv();setInterval(loadCsv,120000);
drawBlot();setInterval(drawBlot,20000);

[['w1',1],['w7',7],['w30',30],['wall',9999]].forEach(function(b){el(b[0]).onclick=function(){WIN=b[1];
 ['w1','w7','w30','wall'].forEach(function(x){el(x).className=x===b[0]?'on':'';});redrawAll();};});
el('mmsym').onchange=drawMM;
window.addEventListener('resize',function(){drawEquity();drawMM();drawPR();});
</script>
</body>
</html>
)OMEGAD4"
;
} // namespace omega_gui
