#pragma once
// AUTO-GENERATED by tools/gui/gen_index_html.py from tools/gui/omega_desk.html
// -- split into chunks to stay under MSVC 16KB string literal limit.
// Edit the .html source and re-run the generator; do not hand-edit this file.
namespace omega_gui {
static const char* INDEX_HTML =
R"OMEGAD0(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Cache-Control" content="no-store,no-cache,must-revalidate">
<title>OMEGA desk</title>
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%230B0F14'/%3E%3Crect x='2' y='2' width='60' height='60' rx='10' fill='none' stroke='%232EBD85' stroke-width='3'/%3E%3Ctext x='32' y='46' font-size='38' text-anchor='middle' fill='%232EBD85' font-family='Georgia,serif' font-weight='bold'%3E%CE%A9%3C/text%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
:root{
  --bg:#0B0F14;--pan:#0E141B;--pan2:#111826;--bd:#1F2937;--bd2:#2b3440;
  --t:#C9D1D9;--t2:#6B7785;--t3:#3d4854;--w:#E6EDF3;
  --grn:#2EBD85;--grnD:#0a4434;--grnB:#9FE1CB;
  --red:#E2484D;--redD:#5c1f1f;--redB:#F7C1C1;
  --amb:#F0B90B;--ambD:#3a2c08;--ambB:#FAC775;
  --blu:#85B7EB;
}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--t);font:12px 'IBM Plex Mono',Menlo,Consolas,monospace;padding:8px}
.num{font-variant-numeric:tabular-nums}
.lbl{font-size:10.5px;color:var(--t2);letter-spacing:.05em}
.pan{background:var(--pan);border:1px solid var(--bd);border-radius:6px;padding:9px 11px;min-width:0}
.grid{display:grid;gap:8px;margin-top:8px}
.chip{display:inline-block;font-size:10.5px;padding:1px 8px;border-radius:3px}
.g{color:var(--grn)}.r{color:var(--red)}.a{color:var(--ambB)}.d{color:var(--t2)}.w{color:var(--w)}
table{width:100%;border-collapse:collapse}
td,th{padding:2px 7px;text-align:right;font-size:11.5px;white-space:nowrap}
td:first-child,th:first-child,td.l,th.l{text-align:left}
th{color:var(--t2);font-weight:400}
tr:nth-child(even) td{background:rgba(255,255,255,0.015)}
canvas{display:block;width:100%}
button{background:var(--pan2);color:var(--t);border:1px solid var(--bd2);border-radius:3px;font:11px 'IBM Plex Mono',monospace;padding:3px 10px;cursor:pointer}
button:hover{background:#16202e}
button.on{border-color:var(--grn);color:var(--grnB)}
select{background:var(--pan2);color:var(--t);border:1px solid var(--bd2);border-radius:3px;font:11px 'IBM Plex Mono',monospace;padding:2px 6px}
a{color:var(--blu);text-decoration:none}
.dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:4px;vertical-align:0}
.tile{border-radius:3px;height:34px;display:flex;flex-direction:column;justify-content:center;padding:2px 6px;overflow:hidden}
.tile b{font-size:9.5px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.tile span{font-size:9px;opacity:.9}
.bar{position:relative;height:8px;background:#1d2733;border-radius:2px;overflow:hidden}
.bar>i{position:absolute;left:0;top:0;bottom:0;border-radius:2px}
@media(max-width:980px){.g2,.g3{grid-template-columns:1fr !important}}
</style>
</head>
<body>

<!-- ═══ RIBBON ═══ -->
<div class="pan" style="display:flex;align-items:center;gap:14px;flex-wrap:wrap;background:var(--pan2);padding:7px 12px">
  <span style="display:inline-flex;align-items:center;gap:8px">
    <span style="width:22px;height:22px;border-radius:5px;background:#0a4434;border:1px solid #0F6E56;color:#9FE1CB;display:inline-flex;align-items:center;justify-content:center;font-size:15px;font-weight:600;font-family:Georgia,serif">&#937;</span>
    <span style="font-size:14px;font-weight:600;color:var(--w)">OMEGA <span style="color:var(--t2);font-weight:400">desk</span></span>
  </span>
  <span id="mode" class="chip" style="background:var(--ambD);color:var(--ambB)">MODE …</span>
  <span class="lbl"><span class="dot" id="fixq" style="background:var(--t3)"></span>FIX-Q</span>
  <span class="lbl"><span class="dot" id="fixt" style="background:var(--t3)"></span>FIX-T</span>
  <span class="lbl"><span class="dot" id="l2d" style="background:var(--t3)"></span>L2</span>
  <span class="lbl"><span class="dot" id="domd" style="background:var(--t3)"></span>GOLD-DOM</span>
  <span class="lbl" id="sessname">session …</span>
  <span class="lbl" id="uptime">up …</span>
  <span class="lbl" id="build"></span>
  <span class="num" id="clk" style="margin-left:auto;color:var(--w)">--:--:-- UTC</span>
  <span class="lbl"><span class="dot" id="conn" style="background:var(--t3)"></span><span id="connlbl">connecting</span></span>
</div>

<!-- ═══ TICKER ═══ -->
<div id="ticker" style="display:flex;border:1px solid var(--bd);border-radius:6px;margin-top:8px;overflow-x:auto;background:var(--pan)"></div>

<!-- ═══ LIVE OPEN TRADES (always visible) ═══ -->
<div class="pan" style="margin-top:8px">
  <div style="display:flex;align-items:baseline;gap:10px">
    <span class="lbl">LIVE OPEN TRADES</span>
    <span id="ltcount" class="lbl"></span>
    <span id="ltpnl" class="num" style="margin-left:auto;font-size:13px"></span>
  </div>
  <table id="lt" style="margin-top:4px"><tr><td class="l d">FLAT — no open positions</td></tr></table>
</div>

<!-- ═══ EQUITY + RISK ═══ -->
<div class="grid g2" style="grid-template-columns:minmax(0,1.7fr) minmax(0,1fr)">
  <div class="pan">
    <div style="display:flex;align-items:baseline;gap:10px;flex-wrap:wrap">
      <span class="lbl">SHADOW EQUITY (paper, all engines)</span>
      <span id="eqtot" class="num" style="font-size:16px;color:var(--grn)">…</span>
      <span style="margin-left:auto;display:flex;gap:5px">
        <button id="w7">7d</button><button id="w30" class="on">30d</button><button id="wall">all</button>
      </span>
    </div>
    <canvas id="eqc" height="170" style="margin-top:6px"></canvas>
    <div id="eqstats" class="lbl num" style="display:flex;gap:14px;flex-wrap:wrap;margin-top:5px"></div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:5px">RISK &amp; GOVERNOR — blocks this session</div>
    <div id="gov" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:2px;font-size:11.5px"></div>
    <div class="lbl" style="margin:8px 0 4px">CLUSTER EXPOSURE $</div>
    <div id="expo" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:2px;font-size:11.5px"></div>
    <div id="cooldowns" style="margin-top:7px"></div>
  </div>
</div>

<!-- ═══ SESSION CLOCK + REGIME ═══ -->
<div class="pan" style="margin-top:8px">
  <div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:6px">
    <span class="lbl">SESSION CLOCK UTC</span>
    <span id="sesstrade" class="chip" style="background:var(--pan2);color:var(--t2)">…</span>
    <span class="lbl" style="margin-left:auto">REGIME</span>
    <span id="macro" class="chip" style="background:var(--pan2);color:var(--t2)">…</span>
    <span class="lbl">VIX <span id="vix" class="num w">…</span></span>
  </div>
  <div id="sessbar" style="position:relative;height:22px;border-radius:3px;overflow:hidden;display:flex"></div>
  <div style="display:flex;justify-content:space-between" class="lbl"><span>00 Asia</span><span>05 pre-Ldn</span><span>07 London</span><span>13:30 NY-KZ</span><span>15 NY</span><span>20 late</span><span>22 Asia</span></div>
  <div id="phases" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:7px"></div>
</div>

<!-- ═══ DOM + MICRO + SIGNALS ═══ -->
<div class="grid g3" style="grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,1.2fr)">
  <div class="pan">
    <div class="lbl" style="margin-bottom:5px">DOM — XAUUSD L2 (cTrader)</div>
    <div id="dom" class="num"></div>
    <div style="margin-top:6px">
      <div class="lbl">OBI top-5 <span id="obiv" class="num w"></span></div>
      <div class="bar" style="margin-top:3px"><i id="obib" style="background:var(--grn);left:50%;width:0"></i></div>
    </div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:5px">MICROSTRUCTURE</div>
    <div id="micro" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:2px;font-size:11.5px"></div>
    <div class="lbl" style="margin:8px 0 3px">BROKER RECON</div>
    <div id="broker" class="num" style="display:grid;grid-template-columns:1fr auto;row-gap:2px;font-size:11.5px"></div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:5px">SIGNAL TAPE — last fires</div>
    <div id="sigs" style="font-size:11px;line-height:1.65;overflow:hidden"></div>
  </div>
</div>

<!-- ═══ ENGINE HEAT ═══ -->
<div class="pan" style="margin-top:8px">
  <div style="display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;margin-bottom:6px">
    <span class="lbl">ENGINE HEAT — shadow paper PnL, window matches equity · tile = engine</span>
    <span class="lbl" style="margin-left:auto">
      <span style="display:inline-block;width:8px;height:8px;background:var(--grnD);border-radius:2px"></span> +
      <span style="display:inline-block;width:8px;height:8px;background:var(--redD);border-radius:2px;margin-left:8px"></span> −
      <span style="display:inline-block;width:8px;height:8px;background:#1d2733;border-radius:2px;margin-left:8px"></span> flat
    </span>
  </div>
  <div id="heat"></div>
</div>

<!-- ═══ MAE/MFE + TOD ═══ -->
<div class="grid g2" style="grid-template-columns:minmax(0,1fr) minmax(0,1fr)">
  <div class="pan">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px">
      <span class="lbl">MAE / MFE — exit audit (pts)</span>
      <select id="mmsym" style="margin-left:auto"></select>
    </div>
    <canvas id="mmc" height="190"></canvas>
    <div class="lbl" style="margin-top:4px">green = win, red = loss · high-MFE losses → trail/BE too tight</div>
  </div>
  <div class="pan">
    <div class="lbl" style="margin-bottom:6px">TIME-OF-DAY EDGE — WR% hour × weekday (all shadow)</div>
    <div id="tod"></div>
    <div class="lbl" style="margin-top:4px">hover cell for n / WR / pnl · dark red = hour-kill candidate</div>
  </div>
</div>

<!-- ═══ PROMOTION + BLOTTER ═══ -->
<div class="grid g2" style="grid-template-columns:minmax(0,1fr) minmax(0,1.3fr)">
  <div class="pan">
    <div class="lbl" style="margin-bottom:6px">PROMOTION TRACKER — shadow n vs gate (30) · expectancy</div>
    <div id="promo" style="font-size:11px"></div>
  </div>
  <div class="pan" style="padding:6px 0 4px">
    <div class="lbl" style="padding:0 11px 4px">SHADOW BLOTTER — last closes (paper)</div>
    <table id="blot"><tr><th class="l">utc</th><th class="l">engine</th><th class="l">sym</th><th>side</th><th>pnl</th><th>mfe</th><th class="l">exit</th></tr></table>
  </div>
</div>

<div style="display:flex;gap:14px;align-items:center;margin-top:8px" class="lbl">
  <a href="/legacy">legacy GUI</a>
  <span id="csvinfo"></span>
  <button style="margin-left:auto" onclick="if(confirm('Clear ledger?'))fetch('/api/clear_ledger',{method:'POST'})">clear ledger</button>
</div>

<script>
'use strict';
function safe(v,d){d=d===undefined?0:d;var n=Number(v);return isNaN(n)?d:n;}
function fmt$(v){var s=v<0?'-':'+';return s+'$'+Math.abs(v).toLocaleString(undefined,{maximumFractionDigits:0});}
function fmt2(v,n){return safe(v).toFixed(n===undefined?2:n);}
function el(id){return document.getElementById(id);}
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}

/* ── clock ── */
function tickClk(){var d=new Date();el('clk').textContent=
 String(d.getUTCHours()).padStart(2,'0')+':'+String(d.getUTCMinutes()).padStart(2,'0')+':'+String(d.getUTCSeconds()).padStart(2,'0')+' UTC';
 var mk=el('sessmk');if(mk)mk.style.left=(((d.getUTCHours()+d.getUTCMinutes()/60)/24)*100)+'%';}
setInterval(tickClk,1000);

/* ── session strip ── */
(function(){var z=[[0,5,'#1d2733'],[5,7,'#143042'],[7,13,'#155446'],[13,13.5,'#0F6E56'],[13.5,15,'#7a5a14'],[15,20,'#155446'],[20,22,'#143042'],[22,24,'#1d2733']];
 var h='';z.forEach(function(s){h+='<span style="flex:'+(s[1]-s[0])+';background:'+s[2]+'"></span>';});
 el('sessbar').innerHTML=h+'<div id="sessmk" style="position:absolute;top:0;bottom:0;width:2px;background:#E6EDF3"></div>';tickClk();})();

/* ── ticker defs ── */
var TKS=[['gold','XAUUSD','xau'],['sp','US500','sp'],['nq','USTEC','nq'],['nas','NAS100','nas'],['dj','DJ30','dj'],
 ['ger30','GER40','ger40'],['uk100','UK100','uk100'],['cl','USOIL','cl'],['xag','XAGUSD','xag'],['vix','VIX',null]];
(function(){var h='';TKS.forEach(function(t){
 h+='<div style="padding:6px 12px;border-right:1px solid var(--bd);min-width:104px">'
  +'<div class="lbl">'+t[1]+'</div><div class="num" id="tk_'+t[0]+'" style="font-size:13px;color:var(--w)">—</div>'
  +'<div class="lbl num" id="tks_'+t[0]+'"></div>'
  +(t[2]?'<div class="bar" style="height:4px;margin-top:3px"><i id="tkr_'+t[0]+'" style="background:var(--blu);width:0"></i></div>':'')
  +'</div>';});
 el('ticker').innerHTML=h;})();

/* ── telemetry render ── */
var lastJ=null;
function render(J){lastJ=J;
 var shadowMode=(J.mode||'').toUpperCase()!=='LIVE';
 var m=el('mode');m.textContent=shadowMode?'SHADOW — 0 live engines':'LIVE';
 m.style.background=shadowMode?'var(--ambD)':'var(--grnD)';m.style.color=shadowMode?'var(--ambB)':'var(--grnB)';
 function dot(id,ok){el(id).style.background=ok?'var(--grn)':'var(--red)';}
 dot('fixq',(J.fix_quote_status||'').indexOf('CONNECT')>=0||(J.fix_quote_status||'').indexOf('UP')>=0||J.quote_msg_rate>0);
 dot('fixt',(J.fix_trade_status||'').indexOf('CONNECT')>=0||(J.fix_trade_status||'').indexOf('UP')>=0);
 dot('l2d',safe(J.ctrader_l2_live)>0);dot('domd',safe(J.gold_l2_real)>0);
 el('sessname').textContent='session '+(J.session_name||'?');
 var up=safe(J.uptime_sec);el('uptime').textContent='up '+Math.floor(up/86400)+'d'+Math.floor(up%86400/3600)+'h'+Math.floor(up%3600/60)+'m';
 el('build').textContent=(J.build_version||'').slice(0,12);
 var st=el('sesstrade');st.textContent=(J.session_name||'?')+(safe(J.session_tradeable)?' · tradeable':' · blocked');
)OMEGAD0"
R"OMEGAD1( st.style.color=safe(J.session_tradeable)?'var(--grnB)':'var(--redB)';
 el('macro').textContent=J.macro_regime||'?';
 el('macro').style.color=(J.macro_regime||'')==='RISK_OFF'?'var(--redB)':'var(--grnB)';
 el('vix').textContent=fmt2(J.vix_level,1);

 TKS.forEach(function(t){var b=safe(J[t[0]+'_bid']),a=safe(J[t[0]+'_ask']);
  if(t[0]==='vix'){b=safe(J.vix_level)||b;}
  el('tk_'+t[0]).textContent=b>0?b.toLocaleString(undefined,{maximumFractionDigits:b>100?1:4}):'—';
  if(b>0&&a>0&&t[0]!=='vix')el('tks_'+t[0]).textContent='s '+fmt2(a-b,a-b<0.01?5:2);
  if(t[2]){var lo=safe(J[t[2]+'_curl']),hi=safe(J[t[2]+'_curh']);
   if(hi>lo&&b>0){var p=Math.max(0,Math.min(1,(b-lo)/(hi-lo)));var r=el('tkr_'+t[0]);r.style.width=(p*100)+'%';
    r.style.background=p>0.85||p<0.15?'var(--amb)':'var(--blu)';}}});

 var govRows=[['Spread gate',J.gov_spread],['Latency gate',J.gov_latency],['PnL governor',J.gov_pnl],
  ['Position cap',J.gov_positions],['Consec-loss',J.gov_consec_loss],
  ['Cost guard blocked',J.cost_guard_blocked],['Cost guard passed',J.cost_guard_passed]];
 el('gov').innerHTML=govRows.map(function(r){var v=safe(r[1]);
  var c=r[0].indexOf('passed')>=0?'g':(v>0?'a':'d');
  return '<span>'+r[0]+'</span><span class="'+c+'">'+v+'</span>';}).join('')
  +(safe(J.multiday_throttle_active)?'<span class="r">Multiday throttle</span><span class="r">×'+fmt2(J.multiday_scale)+'</span>':'');
 var ex=[['US equity',J.exposure_us_equity],['EU equity',J.exposure_eu_equity],['Oil',J.exposure_oil],
  ['Metals',J.exposure_metals],['JPY risk',J.exposure_jpy_risk],['EUR/GBP',J.exposure_eur_gbp],['TOTAL',J.exposure_total]];
 el('expo').innerHTML=ex.map(function(r){var v=safe(r[1]);
  return '<span'+(r[0]==='TOTAL'?' class="w"':'')+'>'+r[0]+'</span><span class="'+(v>0?'w':'d')+'">$'+Math.round(v)+'</span>';}).join('');
 var cd=(J.sl_cooldowns||[]).map(function(c){return '<span class="chip" style="background:var(--redD);color:var(--redB)">'+esc(c.symbol)+' '+c.secs_remaining+'s</span>';}).join(' ');
 el('cooldowns').innerHTML=cd?'<div class="lbl" style="margin-bottom:3px">SL COOLDOWNS</div>'+cd:'';

 var ph=[['XAU','xau'],['SP','sp'],['NQ','nq'],['OIL','cl'],['XAG','xag'],['BRENT','brent']];
 el('phases').innerHTML=ph.map(function(p){var v=safe(J[p[1]+'_phase']);
  var t=v===3?'TRADE':v===2?'BRK':v===1?'COMP':'FLAT';
  var bg=v===3?'var(--grnD)':v===2?'#7a5a14':v===1?'#143042':'var(--pan2)';
  var fg=v===3?'var(--grnB)':v===2?'var(--ambB)':v===1?'var(--blu)':'var(--t2)';
  return '<span class="chip" style="background:'+bg+';color:'+fg+'">'+p[0]+' '+t+'</span>';}).join('');

 var bids=J.gold_bids||[],asks=J.gold_asks||[];
 var mx=1;bids.concat(asks).forEach(function(l){if(l.s>mx)mx=l.s;});
 var dh='<div style="display:grid;grid-template-columns:1fr 70px 1fr;gap:1px;font-size:11px">';
 for(var i=Math.min(4,asks.length-1);i>=0;i--){var l=asks[i];
  dh+='<span></span><span style="text-align:right;color:var(--redB);padding:0 4px">'+fmt2(l.p)+'</span>'
   +'<span style="position:relative"><i style="position:absolute;left:0;top:2px;bottom:2px;width:'+(l.s/mx*100)+'%;background:rgba(226,72,77,.25);border-radius:1px"></i><i style="position:relative;color:var(--redB);padding-left:4px;font-style:normal">'+fmt2(l.s,1)+'</i></span>';}
 var spd=(asks[0]&&bids[0])?(asks[0].p-bids[0].p):0;
 dh+='<span></span><span style="text-align:right;color:var(--t2);border-top:1px solid var(--bd2);border-bottom:1px solid var(--bd2);padding:1px 4px">'+fmt2(spd)+'</span><span style="border-top:1px solid var(--bd2);border-bottom:1px solid var(--bd2)"></span>';
 for(var i=0;i<Math.min(5,bids.length);i++){var l=bids[i];
  dh+='<span style="position:relative"><i style="position:absolute;right:0;top:2px;bottom:2px;width:'+(l.s/mx*100)+'%;background:rgba(46,189,133,.22);border-radius:1px"></i></span>'
   +'<span style="text-align:right;color:var(--grnB);padding:0 4px">'+fmt2(l.p)+'</span><span style="color:var(--grnB);padding-left:4px">'+fmt2(l.s,1)+'</span>';}
 dh+='</div>';el('dom').innerHTML=(bids.length||asks.length)?dh:'<span class="d">no depth (L2 quiet)</span>';
 var imb=safe(J.l2_gold,0.5);el('obiv').textContent=fmt2(imb,3);
 var ob=el('obib'),dev=imb-0.5;ob.style.left=dev>=0?'50%':(50+dev*100)+'%';ob.style.width=Math.abs(dev)*100+'%';
 ob.style.background=dev>=0?'var(--grn)':'var(--red)';

 el('micro').innerHTML=[['Quote msg/s',safe(J.quote_msg_rate),'w'],['Seq gaps',safe(J.sequence_gaps),safe(J.sequence_gaps)>0?'r':'g'],
  ['RTT last ms',fmt2(J.fix_rtt_last,1),'w'],['RTT p50',fmt2(J.fix_rtt_p50,1),'w'],['RTT p95',fmt2(J.fix_rtt_p95,1),safe(J.fix_rtt_p95)>120?'a':'w'],
  ['L2 books live',safe(J.l2_active),'w']].map(function(r){return '<span>'+r[0]+'</span><span class="'+r[2]+'">'+r[1]+'</span>';}).join('');
 var bk=J.broker||{};
 el('broker').innerHTML=[['Engine PnL',fmt$(safe(bk.engine_pnl)),'w'],['Broker realised',fmt$(safe(bk.realised_pnl)),'w'],
  ['Disparity',fmt$(safe(bk.disparity)),Math.abs(safe(bk.disparity))>50?'r':'g'],
  ['Orphans',safe(bk.orphan_count),safe(bk.orphan_count)>0?'r':'d'],['Rejects',safe(bk.reject_count),safe(bk.reject_count)>0?'a':'d'],
  ['Confirmed',safe(bk.confirmed_count),'d']].map(function(r){return '<span>'+r[0]+'</span><span class="'+r[2]+'">'+r[1]+'</span>';}).join('');

 var sh=(J.signal_history||[]).slice(0,9).map(function(s){
  var c=s.side==='LONG'||s.side==='BUY'?'g':'r';
  return '<div><span class="'+c+'">'+esc(s.side||'')+'</span> <span class="w">'+esc(s.symbol||'')+'</span> '
   +'<span class="num">'+fmt2(s.price,2)+'</span> <span class="d">'+esc(s.engine||'')+'</span> <span class="d">'+esc(s.reason||'').slice(0,28)+'</span></div>';}).join('');
 el('sigs').innerHTML=sh||'<span class="d">no signals yet this session</span>';

 var lts=J.live_trades||[];
 el('ltcount').textContent=lts.length?lts.length+' open':'';
 if(!lts.length){el('lt').innerHTML='<tr><td class="l d">FLAT — no open positions</td></tr>';el('ltpnl').textContent='';}
 else{var sum=0;var rows=lts.map(function(t){sum+=safe(t.live_pnl);
  return '<tr><td class="l">'+esc(t.symbol)+'</td><td class="l">'+esc(t.engine)+'</td><td class="'+(t.side==='LONG'?'g':'r')+'">'+esc(t.side)+'</td>'
   +'<td class="num">'+fmt2(t.entry)+'</td><td class="num">'+fmt2(t.current)+'</td>'
   +'<td class="num '+(t.live_pnl>=0?'g':'r')+'">'+fmt$(safe(t.live_pnl))+'</td>'
   +'<td class="num">'+Math.floor(safe(t.held_sec)/60)+'m</td><td class="num">'+fmt2(t.dist_sl,1)+'</td><td class="num">'+fmt2(t.dist_tp,1)+'</td></tr>';}).join('');
  el('lt').innerHTML='<tr><th class="l">sym</th><th class="l">engine</th><th>side</th><th>entry</th><th>now</th><th>pnl</th><th>held</th><th>→SL</th><th>→TP</th></tr>'+rows;
  el('ltpnl').textContent=fmt$(sum)+' unrealised';el('ltpnl').style.color=sum>=0?'var(--grn)':'var(--red)';}
}

/* ── ws + poll ── */
var wsOk=false;
function setConn(ok,via){el('conn').style.background=ok?'var(--grn)':'var(--red)';el('connlbl').textContent=ok?via:'offline';}
(function ws(){try{var s=new WebSocket('ws://'+location.hostname+':7780');
 s.onmessage=function(e){try{render(JSON.parse(e.data));wsOk=true;setConn(true,'ws');}catch(x){}};
 s.onclose=function(){wsOk=false;setConn(false);setTimeout(ws,3000);};
 s.onerror=function(){wsOk=false;};}catch(e){wsOk=false;}})();
function poll(){if(wsOk)return;fetch('/api/telemetry').then(function(r){return r.json();}).then(function(j){render(j);setConn(true,'http');}).catch(function(){setConn(false);});}
setInterval(poll,1000);poll();

/* ── shadow csv analytics ── */
var ROWS=[],WIN=30;
function parseShadow(txt){var out=[];var ls=txt.split('\n');
 for(var i=0;i<ls.length;i++){var L=ls[i];if(!L||L[0]==='t')continue;var f=L.split(',');if(f.length<11)continue;
  var ts=parseInt(f[0],10);if(!ts)continue;
  if(f[1]==='__BOOT__'||f[3]==='boot_writetest')continue;
  out.push({ts:ts+Math.max(0,parseInt(f[9],10)||0),sym:f[1],side:f[2],eng:f[3],pnl:parseFloat(f[6])||0,
   mfe:parseFloat(f[7])||0,mae:parseFloat(f[8])||0,hold:parseInt(f[9],10)||0,reason:(f[10]||'').trim(),
   spread:parseFloat(f[11])||0,lat:parseFloat(f[12])||0});}
 out.sort(function(a,b){return a.ts-b.ts;});return out;}
function winRows(){if(WIN>=9999)return ROWS;var cut=Date.now()/1000-WIN*86400;return ROWS.filter(function(r){return r.ts>=cut;});}

function drawEquity(){var cv=el('eqc'),ctx=cv.getContext('2d');
 cv.width=cv.clientWidth*2;cv.height=340;ctx.scale(2,2);
 var W=cv.clientWidth,H=170;ctx.clearRect(0,0,W,H);
 var rs=winRows();if(!rs.length){ctx.fillStyle='#6B7785';ctx.font='11px IBM Plex Mono';ctx.fillText('no shadow closes in window',10,20);el('eqtot').textContent='$0';el('eqstats').innerHTML='';return;}
 var cum=[],c=0,pk=0,mdd=0,wins=0,gp=0,gl=0;
 rs.forEach(function(r){c+=r.pnl;cum.push(c);pk=Math.max(pk,c);mdd=Math.min(mdd,c-pk);
  if(r.pnl>0){wins++;gp+=r.pnl;}else gl-=r.pnl;});
 var lo=Math.min(0,mdd,Math.min.apply(null,cum)),hi=Math.max.apply(null,cum.concat([1]));
 function X(i){return 4+(W-8)*i/Math.max(1,cum.length-1);}
 function Y(v){return 8+(H-26)*(1-(v-lo)/(hi-lo||1));}
 ctx.strokeStyle='rgba(255,255,255,0.06)';ctx.beginPath();
 [lo,0,hi].forEach(function(g){ctx.moveTo(0,Y(g));ctx.lineTo(W,Y(g));});ctx.stroke();
 ctx.fillStyle='#6B7785';ctx.font='9px IBM Plex Mono';
 ctx.fillText(fmt$(hi),2,Y(hi)+9);ctx.fillText('$0',2,Y(0)-3);
 ctx.beginPath();cum.forEach(function(v,i){i?ctx.lineTo(X(i),Y(v)):ctx.moveTo(X(0),Y(v));});
 ctx.strokeStyle='#2EBD85';ctx.lineWidth=1.4;ctx.stroke();
 ctx.lineTo(X(cum.length-1),Y(0));ctx.lineTo(X(0),Y(0));ctx.closePath();
 ctx.fillStyle='rgba(46,189,133,0.08)';ctx.fill();
 var p2=0;ctx.beginPath();cum.forEach(function(v,i){p2=Math.max(p2,v);var d=v-p2;i?ctx.lineTo(X(i),Y(d)):ctx.moveTo(X(0),Y(d));});
 ctx.strokeStyle='#E2484D';ctx.setLineDash([4,3]);ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);
 var net=cum[cum.length-1];el('eqtot').textContent=fmt$(net);el('eqtot').style.color=net>=0?'var(--grn)':'var(--red)';
 var pf=gl>0?gp/gl:0,wr=100*wins/rs.length;
 el('eqstats').innerHTML='<span>n <span class="w">'+rs.length+'</span></span><span>PF <span class="w">'+fmt2(pf)+'</span></span>'
  +'<span>WR <span class="w">'+fmt2(wr,1)+'%</span></span><span>maxDD <span class="r">'+fmt$(mdd)+'</span></span>'
  +'<span>avg <span class="w">'+fmt$(net/rs.length)+'</span></span>';}

function classOf(sym){if(/XAU|MGC|GOLD/i.test(sym))return 'GOLD';
 if(/US500|USTEC|NAS|DJ30|GER|UK100|ESTX|US30/i.test(sym))return 'INDEX';
 if(/USD|EUR|GBP|AUD|NZD|JPY/.test(sym)&&sym.length===6)return 'FX';
 if(/XAG|SILVER/i.test(sym))return 'SILVER';
 if(/OIL|BRENT|CL/i.test(sym))return 'OIL';return 'OTHER';}
function drawHeat(){var rs=winRows();var by={};
 rs.forEach(function(r){var k=r.eng||'?';if(!by[k])by[k]={n:0,pnl:0,sym:r.sym};by[k].n++;by[k].pnl+=r.pnl;});
 var ks=Object.keys(by);if(!ks.length){el('heat').innerHTML='<span class="d">no engine activity in window</span>';return;}
 var groups={};ks.forEach(function(k){var g=classOf(by[k].sym);(groups[g]=groups[g]||[]).push(k);});
 var mxAbs=1;ks.forEach(function(k){mxAbs=Math.max(mxAbs,Math.abs(by[k].pnl));});
 var order=['GOLD','INDEX','FX','SILVER','OIL','OTHER'],h='';
 order.forEach(function(g){if(!groups[g])return;
  groups[g].sort(function(a,b){return by[b].pnl-by[a].pnl;});
  h+='<div class="lbl" style="margin:6px 0 3px">'+g+(g==='FX'?' — no proven edge':'')+' <span style="color:var(--t3)">'+groups[g].length+' active</span></div>'
   +'<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(76px,1fr));gap:3px">';
  groups[g].forEach(function(k){var e=by[k],t=e.pnl/mxAbs;
   var bg='#1d2733',fg='#8B97A5';
   if(e.pnl>1){bg=t>0.4?'#0F6E56':'#0a4434';fg='#9FE1CB';}
   else if(e.pnl<-1){bg=t<-0.4?'#A32D2D':'#5c1f1f';fg='#F7C1C1';}
   var nm=k.replace(/Engine$/,'');
   h+='<div class="tile" style="background:'+bg+'" title="'+esc(k)+' n='+e.n+' pnl='+fmt$(e.pnl)+'">'
    +'<b style="color:'+fg+'">'+esc(nm)+'</b><span class="num" style="color:'+fg+'">'+fmt$(e.pnl)+' · '+e.n+'</span></div>';});
  h+='</div>';});
 el('heat').innerHTML=h;}

function fillSymSel(){var by={};ROWS.forEach(function(r){by[r.sym]=(by[r.sym]||0)+1;});
 var syms=Object.keys(by).sort(function(a,b){return by[b]-by[a];}).slice(0,8);
 var s=el('mmsym');var cur=s.value;
 s.innerHTML=syms.map(function(x){return '<option>'+esc(x)+'</option>';}).join('');
 if(syms.indexOf(cur)>=0)s.value=cur;}
function drawMM(){var cv=el('mmc'),ctx=cv.getContext('2d');
 cv.width=cv.clientWidth*2;cv.height=380;ctx.scale(2,2);
 var W=cv.clientWidth,H=190;ctx.clearRect(0,0,W,H);
 var sym=el('mmsym').value;var rs=winRows().filter(function(r){return r.sym===sym;}).slice(-400);
 if(!rs.length){ctx.fillStyle='#6B7785';ctx.font='11px IBM Plex Mono';ctx.fillText('no trades for '+sym,10,20);return;}
 var xs=rs.map(function(r){return r.mae;}),ys=rs.map(function(r){return r.mfe;});
 function pct(a,p){var b=a.slice().sort(function(x,y){return x-y;});return b[Math.min(b.length-1,Math.floor(p*b.length))];}
 var mx=Math.max(pct(xs,0.97),0.1),my=Math.max(pct(ys,0.97),0.1);
 function X(v){return 26+(W-34)*Math.min(1,v/mx);}function Y(v){return H-18-(H-30)*Math.min(1,v/my);}
 ctx.strokeStyle='rgba(255,255,255,0.07)';ctx.strokeRect(26,12,W-34,H-30);
 ctx.fillStyle='#6B7785';ctx.font='9px IBM Plex Mono';
 ctx.fillText('MAE '+fmt2(mx,1),W-60,H-4);ctx.fillText('MFE',2,14);ctx.fillText(fmt2(my,1),2,24);
 rs.forEach(function(r){ctx.fillStyle=r.pnl>0?'rgba(46,189,133,0.75)':'rgba(226,72,77,0.75)';
  ctx.beginPath();ctx.arc(X(r.mae),Y(r.mfe),2.2,0,6.3);ctx.fill();});}

var DAYS=['Su','Mo','Tu','We','Th','Fr','Sa'];
function drawTOD(){var rs=ROWS;var grid={};
 rs.forEach(function(r){var d=new Date(r.ts*1000);var k=d.getUTCDay()+'_'+d.getUTCHours();
  if(!grid[k])grid[k]={n:0,w:0,pnl:0};grid[k].n++;if(r.pnl>0)grid[k].w++;grid[k].pnl+=r.pnl;});
 var h='<div style="display:grid;grid-template-columns:24px repeat(24,1fr);gap:1px">';
 h+='<span></span>';for(var c=0;c<24;c++)h+='<span class="lbl" style="font-size:8px;text-align:center">'+(c%4===0?c:'')+'</span>';
)OMEGAD1"
R"OMEGAD2( [1,2,3,4,5,0].forEach(function(d){h+='<span class="lbl" style="font-size:9px">'+DAYS[d]+'</span>';
  for(var c=0;c<24;c++){var g=grid[d+'_'+c],bg='#141a22',ti='';
   if(g&&g.n>=2){var wr=g.w/g.n;
    bg=wr>0.58?'#0F6E56':wr>0.5?'#155446':wr>0.44?'#1d2733':wr>0.36?'#5c1f1f':'#A32D2D';
    ti=DAYS[d]+' '+c+':00 n='+g.n+' wr='+Math.round(wr*100)+'% pnl='+fmt$(g.pnl);}
   else if(g){bg='#1a212b';ti=DAYS[d]+' '+c+':00 n='+g.n;}
   h+='<span title="'+ti+'" style="height:13px;background:'+bg+';border-radius:1px"></span>';}});
 h+='</div>';el('tod').innerHTML=h;}

function drawPromo(){var by={};
 ROWS.forEach(function(r){var k=r.eng||'?';if(!by[k])by[k]={n:0,pnl:0,w:0};by[k].n++;by[k].pnl+=r.pnl;if(r.pnl>0)by[k].w++;});
 var ks=Object.keys(by).sort(function(a,b){return by[b].n-by[a].n;}).slice(0,14);
 if(!ks.length){el('promo').innerHTML='<span class="d">no shadow history yet</span>';return;}
 var GATE=30,h='';
 ks.forEach(function(k){var e=by[k],avg=e.pnl/e.n,ok=e.n>=GATE;
  var col=e.n<10?'var(--t2)':avg>0?(ok?'var(--grn)':'var(--ambB)'):'var(--red)';
  var tag=e.n<10?'n small':avg>0?(ok?'judgeable +EV':'building'):(ok?'judgeable −EV':'building');
  h+='<div style="display:grid;grid-template-columns:minmax(90px,1.4fr) 2fr 46px 64px 80px;gap:7px;align-items:center;margin-bottom:4px">'
   +'<span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis" title="'+esc(k)+'">'+esc(k.replace(/Engine$/,''))+'</span>'
   +'<span class="bar"><i style="width:'+Math.min(100,e.n/GATE*100)+'%;background:'+col+'"></i></span>'
   +'<span class="num d">'+e.n+'/'+GATE+'</span><span class="num" style="color:'+col+'">'+fmt$(avg)+'/t</span>'
   +'<span class="lbl" style="color:'+col+'">'+tag+'</span></div>';});
 el('promo').innerHTML=h;}

function drawBlot(){fetch('/api/shadow_trades').then(function(r){return r.json();}).then(function(a){
 if(!a||!a.length){return;}
 a=a.filter(function(t){return t.symbol!=='__BOOT__'&&t.engine!=='boot_writetest';});
 if(!a.length){return;}
 var rows=a.slice(-14).reverse().map(function(t){
  var d=new Date(safe(t.exitTs)*1000);
  var hh=String(d.getUTCHours()).padStart(2,'0')+':'+String(d.getUTCMinutes()).padStart(2,'0');
  return '<tr><td class="l num d">'+hh+'</td><td class="l">'+esc((t.engine||'').replace(/Engine$/,''))+'</td><td class="l">'+esc(t.symbol||'')+'</td>'
   +'<td class="'+((t.side==='LONG'||t.side==='BUY')?'g':'r')+'">'+((t.side==='LONG'||t.side==='BUY')?'L':'S')+'</td>'
   +'<td class="num '+(t.pnl>=0?'g':'r')+'">'+fmt$(safe(t.pnl))+'</td>'
   +'<td class="num d">'+fmt2(t.mfe,1)+'</td><td class="l d">'+esc(t.exitReason||'')+'</td></tr>';}).join('');
 el('blot').innerHTML='<tr><th class="l">utc</th><th class="l">engine</th><th class="l">sym</th><th>side</th><th>pnl</th><th>mfe</th><th class="l">exit</th></tr>'+rows;
}).catch(function(){});}

function redrawAll(){drawEquity();drawHeat();drawMM();drawTOD();drawPromo();}
function loadCsv(){fetch('/api/shadow_csv').then(function(r){return r.text();}).then(function(t){
 ROWS=parseShadow(t);el('csvinfo').textContent=ROWS.length+' shadow closes loaded';
 fillSymSel();redrawAll();}).catch(function(){el('csvinfo').textContent='shadow csv unavailable';});}
loadCsv();setInterval(loadCsv,120000);
drawBlot();setInterval(drawBlot,20000);

[['w7',7],['w30',30],['wall',9999]].forEach(function(b){el(b[0]).onclick=function(){WIN=b[1];
 ['w7','w30','wall'].forEach(function(x){el(x).className=x===b[0]?'on':'';});redrawAll();};});
el('mmsym').onchange=drawMM;
window.addEventListener('resize',function(){drawEquity();drawMM();});
</script>
</body>
</html>
)OMEGAD2"
;
} // namespace omega_gui
