#pragma once
// =============================================================================
// RiskMonitor.hpp -- per-engine logging-only risk surveillance
// =============================================================================
//
// 2026-05-08 (Claude / Jo S20+): Single component that watches every engine's
//   closed trades and per-hour fire rate, evaluates three "would have tripped"
//   conditions, and emits log lines. v1 is logging-only -- it never touches
//   any engine's shadow_mode flag. After 2 weeks of clean log data confirming
//   the thresholds are sensible, v2 will replace the WOULD-TRIP log lines with
//   actual `engine.shadow_mode = true` writes.
//
// THE THREE CHECKS
//
//   (1) WR break-even floor.
//       Trip if rolling-N-trade win rate falls below a per-engine TRIP_WR
//       threshold (= BE_WR + buffer, calibrated by calibrate_risk_thresholds).
//       For GoldMicroScalper rk12: BE_WR=79.16%, TRIP_WR=82.16%. The math
//       guarantees that below TRIP_WR the engine is bleeding faster than the
//       3pp safety margin allows, regardless of what backtest WR was.
//
//   (2) Fire-rate over/under-firing.
//       Per-UTC-hour bucket. Trip if (a) live count for the closed hour
//       exceeds 2.5x the calibrated expected count for that hour (over-firing
//       = regime mismatch, engine seeing breakouts where backtest saw chop),
//       OR (b) live count falls below 0.4x expected for 3 consecutive active
//       hours (sustained under-firing = data feed degraded or signal model
//       fundamentally not seeing the same tape). Asymmetric thresholds
//       because under-firing is usually benign and slow; over-firing is
//       usually a fast bleed.
//
//   (3) Spread-at-entry drift.
//       The engine's MAX_SPREAD gate ensures live `spread_at_entry` <= 1.0pt
//       on XAUUSD. Backtest filtered median was 0.22 -- the broker's normal
//       spread is essentially deterministic, so any rolling drift is a
//       material signal. Trip if rolling-N-trade median > 1.5x backtest
//       filtered median (= 0.33 for microscalper). Rare wide-but-allowed
//       trades (0.40-0.99) bring the median up only when the underlying
//       broker spread regime has shifted, which is exactly what we want
//       to catch.
//
// CALIBRATION INPUT
//
//   data/risk_monitor_thresholds.csv -- generated by
//   backtest/calibrate_risk_thresholds. Schema is column-by-name; reordered
//   exports work. Add an engine to monitoring by adding a row to ENGINE_TABLE
//   in the calibration tool, recompiling, re-running, and restarting the
//   live process. No live-side code changes required.
//
// LIVE-SIDE INSERTION POINTS (the v1 wiring is FOUR places)
//
//   1. include/globals.hpp -- declare `static omega::RiskMonitor g_risk_monitor;`
//   2. include/engine_init.hpp -- call `g_risk_monitor.load_thresholds(...)`
//      at startup, after the threshold CSV path is known.
//   3. include/trade_lifecycle.hpp -- inside handle_closed_trade(), call
//      `g_risk_monitor.on_trade_close(tr_in)` near the top.
//   4. Each monitored engine's fire path -- call
//      `g_risk_monitor.on_fire("EngineName", now_s)` at the top of the order
//      send. For microscalper this lives in GoldMicroScalperEngine.hpp at the
//      [MICRO-SCALPER-GOLD] FIRE log site.
//
// LOG FORMAT
//
//   logs/risk_monitor_YYYY-MM-DD.log, append mode, day-rotated automatically.
//   One line per evaluation; OK lines emitted every Nth trade to bound noise;
//   WOULD-TRIP lines emitted on every triggering trade.
//
//   [RISK-MON] 2026-05-09 MicroScalperGold WR-EVAL: rolling_n=120 wr=84.200% trip_wr=82.160% margin=+2.04pp OK
//   [RISK-MON] 2026-05-09 MicroScalperGold FIRE-EVAL: hour=14 live=145 expected=81.6 ratio=1.78x OK
//   [RISK-MON] 2026-05-09 MicroScalperGold SPREAD-EVAL: rolling_n=120 median=0.2200 trip=0.3300 baseline_median=0.2200 OK
//   [RISK-MON] 2026-05-09 MicroScalperGold WR-EVAL: rolling_n=200 wr=78.500% trip_wr=82.160% margin=-3.66pp WOULD-TRIP
//   [RISK-MON-DAILY] 2026-05-09 MicroScalperGold fires=1247 wins=1112 losses=135 wr=89.176% pnl=985.20 trips_wr=1 trips_fire=0 trips_spread=0
//
// THREAD-SAFETY
//
//   All public methods take an internal mutex. The live tick path already
//   serialises ledger writes through handle_closed_trade(); the additional
//   per-call lock is on a different mutex but on the same code path, so
//   there is no nested-lock risk. Fire-path on_fire() is also serialised --
//   the engines that call it run on the single-threaded tick loop today,
//   but the lock keeps the contract right if that ever changes.
// =============================================================================

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <deque>
#include <fstream>
#include <map>
#include <mutex>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

#include "OmegaTradeLedger.hpp"  // omega::TradeRecord

namespace omega {

// -----------------------------------------------------------------------------
// Per-engine threshold row loaded from data/risk_monitor_thresholds.csv.
// -----------------------------------------------------------------------------
struct RiskMonitorThresholds {
    std::string engine;
    std::string symbol;
    double      tp_pts                          = 0.0;
    double      sl_pts                          = 0.0;
    double      be_wr                           = 0.0;
    double      trip_wr                         = 0.0;
    double      expected_fires_per_hour         = 0.0;
    int         session_start_utc               = 0;
    int         session_end_utc                 = 0;
    double      backtest_spread_median          = 0.0;  // raw market view (diagnostic)
    double      backtest_spread_p95             = 0.0;  // raw market view (diagnostic)
    double      backtest_spread_median_filt     = 0.0;  // post-MAX_SPREAD (consumed)
    double      backtest_spread_p95_filt        = 0.0;  // post-MAX_SPREAD (diagnostic)
    int         window_n                        = 0;
    int         window_n_minimum                = 0;
    std::array<double, 24> fires_per_hour_table{};

    // Derived trip thresholds (computed at load time).
    double      spread_trip_median              = 0.0;  // rolling median > this => trip
    double      fire_under_ratio                = 0.4;  // rolling/expected < this => under
    double      fire_over_ratio                 = 2.5;  // rolling/expected > this => over
    int         fire_under_consec_hours         = 3;    // need this many in a row to trip
};

// -----------------------------------------------------------------------------
// Per-engine rolling state.
// -----------------------------------------------------------------------------
struct RiskMonitorState {
    std::string engine;
    std::deque<bool>   wins;                     // rolling N: each closed trade win/loss
    std::deque<double> spreads_at_entry;         // rolling N: spread at entry
    int64_t            last_close_ts_s          = 0;

    // Fire-rate tracking. Per-UTC-hour bucket of in-progress count.
    int                cur_hour_bucket          = -1;   // UTC hour we're aggregating
    int                cur_hour_count           = 0;    // fires this hour
    int                consec_under_hours       = 0;    // consecutive under-firing hours

    // Daily aggregates for the daily summary writer.
    int                day_fires                = 0;
    int                day_wins                 = 0;
    int                day_losses               = 0;
    double             day_pnl_sum              = 0.0;
    int                day_trip_wr              = 0;
    int                day_trip_fire            = 0;
    int                day_trip_spread          = 0;
    int                day_utc_idx              = -1;

    // Cumulative counters since process start (diagnostic only).
    int                cumulative_trip_wr       = 0;
    int                cumulative_trip_fire     = 0;
    int                cumulative_trip_spread   = 0;
};

// -----------------------------------------------------------------------------
// RiskMonitor -- owns all per-engine state and writes the log file.
// -----------------------------------------------------------------------------
class RiskMonitor {
public:
    // 2026-05-08 DEEPSTRIKE: flipped to false for the live deploy. On any
    //   trip event the monitor would now actually write back to the
    //   engine's shadow_mode flag instead of just logging WOULD-TRIP.
    //
    //   IMPORTANT: v1 has no re-arm gate. Once an engine is auto-pinned to
    //   shadow by the monitor, it stays shadow until either (a) the operator
    //   manually flips engine.shadow_mode = false in source + redeploy, or
    //   (b) v2 ships a re-arm gate that auto-restores live on engines whose
    //   paper performance recovers to backtest expectancy. For first live
    //   this one-way trip behaviour IS the safety net; do not flip back to
    //   logging_only = true without operator awareness.
    //
    //   Also see _evaluate_wr / _evaluate_fire / _evaluate_spread below --
    //   when this flag is false those methods need to actually mutate
    //   engine state, not just log. v1 implementation logs the WOULD-TRIP
    //   line AND emits a follow-up TRIPPED line announcing the auto-pin;
    //   the actual `engine.shadow_mode = true` write happens via a small
    //   handler block in each evaluator. (See AUTO_PIN_HOOKS below.)
    bool logging_only = false;

    // Load thresholds from CSV. Returns number of rows successfully loaded.
    // Pre-existing state (if any) is preserved; thresholds are upserted.
    int load_thresholds(const std::string& csv_path);

    // Hooks called from the live tick / close paths.
    void on_fire(const std::string& engine, int64_t now_s);
    void on_trade_close(const omega::TradeRecord& tr);

    // Called from a session-end heartbeat (or end-of-day signal). Emits
    // one [RISK-MON-DAILY] line per registered engine and resets day
    // aggregates. Safe to call multiple times -- empty days emit zeros.
    void emit_daily_summary(int64_t now_s);

    // 2026-05-08 DEEPSTRIKE: register an auto-pin callback per engine.
    //   When `logging_only = false` and an evaluator hits a WOULD-TRIP
    //   condition, this callback fires. Convention: the callback should
    //   set the engine's `shadow_mode = true` and print a one-line
    //   notification to stdout. The callback is responsible for its own
    //   idempotency (don't pin if already pinned).
    void register_shadow_pin_cb(const std::string& engine,
                                std::function<void(const std::string& reason)> cb);

    // 2026-05-11 S26 §2.0c: external trip path for monitors that live
    //   outside the WR / FIRE / SPREAD evaluators (currently used by the
    //   broker-disparity hard-stop at the end of handle_closed_trade in
    //   trade_lifecycle.hpp). Same semantics as the internal `_maybe_auto_pin`
    //   except that the wrapper takes the lock since outside callers don't
    //   hold mtx_. If logging_only is false and a callback is registered
    //   for `engine`, the callback fires under the monitor lock so the
    //   engine's shadow_mode flip is serialised against the rest of the
    //   evaluator state. The callback must be idempotent -- the disparity
    //   monitor uses a session-scoped one-shot guard but it is reasonable
    //   for other future callers to invoke this on every offending tick.
    void trip_engine_to_shadow(const std::string& engine,
                               const std::string& reason);

private:
    mutable std::mutex                                            mtx_;
    std::unordered_map<std::string, RiskMonitorThresholds>        thresholds_;
    std::unordered_map<std::string, RiskMonitorState>             states_;
    std::unordered_map<std::string,
                       std::function<void(const std::string&)>>   shadow_pin_cbs_;
    std::ofstream                                                 log_;
    int                                                           current_log_day_idx_ = -1;

    void _ensure_log_open  (int64_t now_s);
    void _evaluate_wr      (RiskMonitorState& s, const RiskMonitorThresholds& t, int64_t now_s);
    void _evaluate_fire    (RiskMonitorState& s, const RiskMonitorThresholds& t, int64_t now_s);
    void _evaluate_spread  (RiskMonitorState& s, const RiskMonitorThresholds& t, int64_t now_s);
    void _maybe_auto_pin   (const std::string& engine, const std::string& reason);
    void _maybe_roll_day   (RiskMonitorState& s, int64_t now_s);

    static int         _utc_hour    (int64_t now_s);
    static int         _utc_day_idx (int64_t now_s);
    static std::string _utc_date_str(int64_t now_s);
};

// -----------------------------------------------------------------------------
// Implementation.
// -----------------------------------------------------------------------------

inline int RiskMonitor::load_thresholds(const std::string& csv_path) {
    std::lock_guard<std::mutex> lk(mtx_);
    std::ifstream in(csv_path);
    if (!in) {
        std::fprintf(stderr, "[RISK-MON] WARN cannot open %s\n", csv_path.c_str());
        return 0;
    }
    std::string header;
    if (!std::getline(in, header)) {
        std::fprintf(stderr, "[RISK-MON] WARN %s: empty file\n", csv_path.c_str());
        return 0;
    }

    // Build column-name -> index map from header line.
    std::unordered_map<std::string, int> col;
    {
        std::stringstream ss(header);
        std::string cell;
        int i = 0;
        while (std::getline(ss, cell, ',')) {
            if (!cell.empty() && cell.back() == '\r') cell.pop_back();
            col[cell] = i++;
        }
    }
    auto col_idx = [&](const std::string& name) -> int {
        auto it = col.find(name);
        return (it == col.end()) ? -1 : it->second;
    };

    int row_count = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;

        std::vector<std::string> cells;
        {
            std::stringstream ss(line);
            std::string cell;
            while (std::getline(ss, cell, ',')) {
                if (!cell.empty() && cell.back() == '\r') cell.pop_back();
                cells.push_back(cell);
            }
        }

        auto get_str = [&](int i) -> std::string {
            return (i < 0 || i >= (int)cells.size()) ? std::string{} : cells[i];
        };
        auto get_dbl = [&](int i) -> double {
            try { return (i < 0 || i >= (int)cells.size()) ? 0.0 : std::stod(cells[i]); }
            catch (...) { return 0.0; }
        };
        auto get_int = [&](int i) -> int {
            try { return (i < 0 || i >= (int)cells.size()) ? 0 : std::stoi(cells[i]); }
            catch (...) { return 0; }
        };

        RiskMonitorThresholds t;
        t.engine                      = get_str(col_idx("engine"));
        if (t.engine.empty()) continue;
        t.symbol                      = get_str(col_idx("symbol"));
        t.tp_pts                      = get_dbl(col_idx("tp_pts"));
        t.sl_pts                      = get_dbl(col_idx("sl_pts"));
        t.be_wr                       = get_dbl(col_idx("be_wr"));
        t.trip_wr                     = get_dbl(col_idx("trip_wr"));
        t.expected_fires_per_hour     = get_dbl(col_idx("expected_fires_per_hour"));
        t.session_start_utc           = get_int(col_idx("session_start_utc"));
        t.session_end_utc             = get_int(col_idx("session_end_utc"));
        t.backtest_spread_median      = get_dbl(col_idx("backtest_spread_median"));
        t.backtest_spread_p95         = get_dbl(col_idx("backtest_spread_p95"));
        t.backtest_spread_median_filt = get_dbl(col_idx("backtest_spread_median_filtered"));
        t.backtest_spread_p95_filt    = get_dbl(col_idx("backtest_spread_p95_filtered"));
        t.window_n                    = get_int(col_idx("window_n"));
        t.window_n_minimum            = get_int(col_idx("window_n_minimum"));
        for (int h = 0; h < 24; ++h) {
            char hname[32];
            std::snprintf(hname, sizeof(hname), "fires_per_hour_%02d", h);
            t.fires_per_hour_table[h] = get_dbl(col_idx(hname));
        }

        // Derive spread trip threshold. 1.5x filtered median, with an
        // absolute floor of (median + 0.05) so engines with very tight
        // backtest baselines (e.g. 0.05pt median) don't trip on +50%
        // relative drift that's still within tick-noise range.
        const double base = t.backtest_spread_median_filt > 0.0
            ? t.backtest_spread_median_filt
            : t.backtest_spread_median;
        t.spread_trip_median = std::max(base * 1.5, base + 0.05);

        thresholds_[t.engine] = t;
        if (states_.find(t.engine) == states_.end()) {
            RiskMonitorState s;
            s.engine = t.engine;
            states_[t.engine] = std::move(s);
        }
        ++row_count;
    }

    std::fprintf(stderr,
        "[RISK-MON] loaded %d engine threshold rows from %s\n"
        "           logging-only mode = %s\n",
        row_count, csv_path.c_str(), logging_only ? "TRUE" : "FALSE");
    for (const auto& [name, t] : thresholds_) {
        std::fprintf(stderr,
            "[RISK-MON]   engine=%s symbol=%s trip_wr=%.4f spread_trip_median=%.4f"
            " expected_fires_per_hour=%.1f window_n=%d\n",
            name.c_str(), t.symbol.c_str(), t.trip_wr, t.spread_trip_median,
            t.expected_fires_per_hour, t.window_n);
    }
    return row_count;
}

inline void RiskMonitor::on_fire(const std::string& engine, int64_t now_s) {
    std::lock_guard<std::mutex> lk(mtx_);
    auto sit = states_.find(engine);
    if (sit == states_.end()) return;  // engine not in calibration table
    RiskMonitorState& s = sit->second;
    _maybe_roll_day(s, now_s);

    const int hour = _utc_hour(now_s);
    if (s.cur_hour_bucket != hour) {
        // Hour bucket rolled: evaluate the closed bucket before resetting.
        if (s.cur_hour_bucket >= 0) {
            auto tit = thresholds_.find(engine);
            if (tit != thresholds_.end()) {
                _evaluate_fire(s, tit->second, now_s);
            }
        }
        s.cur_hour_bucket = hour;
        s.cur_hour_count  = 0;
    }
    ++s.cur_hour_count;
    ++s.day_fires;
}

inline void RiskMonitor::on_trade_close(const omega::TradeRecord& tr) {
    std::lock_guard<std::mutex> lk(mtx_);
    auto tit = thresholds_.find(tr.engine);
    if (tit == thresholds_.end()) return;
    auto sit = states_.find(tr.engine);
    if (sit == states_.end()) return;

    const RiskMonitorThresholds& t = tit->second;
    RiskMonitorState&            s = sit->second;
    const int64_t now_s = tr.exitTs > 0 ? tr.exitTs : tr.entryTs;
    _maybe_roll_day(s, now_s);

    const bool won = tr.pnl > 0.0;
    s.wins.push_back(won);
    while ((int)s.wins.size() > t.window_n) s.wins.pop_front();

    s.spreads_at_entry.push_back(tr.spreadAtEntry);
    while ((int)s.spreads_at_entry.size() > t.window_n) s.spreads_at_entry.pop_front();

    s.last_close_ts_s = now_s;
    s.day_pnl_sum += tr.pnl;
    if (won) ++s.day_wins; else ++s.day_losses;

    _evaluate_wr    (s, t, now_s);
    _evaluate_spread(s, t, now_s);
}

inline void RiskMonitor::_evaluate_wr(RiskMonitorState& s,
                                      const RiskMonitorThresholds& t,
                                      int64_t now_s)
{
    const int n = (int)s.wins.size();
    if (n < t.window_n_minimum) return;

    int n_wins = 0;
    for (bool w : s.wins) if (w) ++n_wins;
    const double wr = static_cast<double>(n_wins) / static_cast<double>(n);
    const double margin_pp = (wr - t.trip_wr) * 100.0;

    _ensure_log_open(now_s);
    if (!log_) return;

    char buf[320];
    if (wr < t.trip_wr) {
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s WR-EVAL: rolling_n=%d wr=%.3f%% trip_wr=%.3f%%"
            " margin=%.2fpp %s\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            n, wr * 100.0, t.trip_wr * 100.0, margin_pp,
            logging_only ? "WOULD-TRIP" : "TRIPPED");
        ++s.day_trip_wr;
        ++s.cumulative_trip_wr;
        log_ << buf;
        log_.flush();
        char reason[160];
        std::snprintf(reason, sizeof(reason),
                      "WR %.3f%% < trip %.3f%% over rolling_n=%d",
                      wr * 100.0, t.trip_wr * 100.0, n);
        _maybe_auto_pin(s.engine, reason);
    } else {
        // Throttle OK lines to keep the log readable -- one in every 50.
        if ((n % 50) != 0) return;
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s WR-EVAL: rolling_n=%d wr=%.3f%% trip_wr=%.3f%%"
            " margin=+%.2fpp OK\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            n, wr * 100.0, t.trip_wr * 100.0, margin_pp);
        log_ << buf;
        log_.flush();
    }
}

inline void RiskMonitor::_evaluate_fire(RiskMonitorState& s,
                                        const RiskMonitorThresholds& t,
                                        int64_t now_s)
{
    const int hour = s.cur_hour_bucket;
    if (hour < 0 || hour >= 24) return;

    const double expected = t.fires_per_hour_table[hour];
    const int    actual   = s.cur_hour_count;

    // Outside session: skip evaluation. The engine isn't expected to fire,
    // so under-fire isn't meaningful here.
    if (expected <= 0.0) {
        s.consec_under_hours = 0;
        return;
    }

    _ensure_log_open(now_s);
    if (!log_) return;

    const double ratio = static_cast<double>(actual) / expected;
    const bool over    = ratio > t.fire_over_ratio;
    const bool under   = ratio < t.fire_under_ratio;

    if (under) ++s.consec_under_hours; else s.consec_under_hours = 0;

    char buf[320];
    if (over) {
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s FIRE-EVAL: hour=%02d live=%d expected=%.1f"
            " ratio=%.2fx %s (over)\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            hour, actual, expected, ratio,
            logging_only ? "WOULD-TRIP" : "TRIPPED");
        ++s.day_trip_fire;
        ++s.cumulative_trip_fire;
        log_ << buf;
        char reason[160];
        std::snprintf(reason, sizeof(reason),
                      "FIRE-RATE OVER hour=%02d live=%d expected=%.1f ratio=%.2fx",
                      hour, actual, expected, ratio);
        _maybe_auto_pin(s.engine, reason);
    } else if (s.consec_under_hours >= t.fire_under_consec_hours) {
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s FIRE-EVAL: hour=%02d live=%d expected=%.1f"
            " ratio=%.2fx consec_under=%d %s (under)\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            hour, actual, expected, ratio, s.consec_under_hours,
            logging_only ? "WOULD-TRIP" : "TRIPPED");
        ++s.day_trip_fire;
        ++s.cumulative_trip_fire;
        log_ << buf;
        char reason[160];
        std::snprintf(reason, sizeof(reason),
                      "FIRE-RATE UNDER consec=%d hour=%02d ratio=%.2fx",
                      s.consec_under_hours, hour, ratio);
        _maybe_auto_pin(s.engine, reason);
    } else {
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s FIRE-EVAL: hour=%02d live=%d expected=%.1f"
            " ratio=%.2fx OK\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            hour, actual, expected, ratio);
        log_ << buf;
    }
    log_.flush();
}

inline void RiskMonitor::_evaluate_spread(RiskMonitorState& s,
                                          const RiskMonitorThresholds& t,
                                          int64_t now_s)
{
    const int n = (int)s.spreads_at_entry.size();
    if (n < t.window_n_minimum) return;

    std::vector<double> v(s.spreads_at_entry.begin(), s.spreads_at_entry.end());
    std::sort(v.begin(), v.end());
    const double median = v[v.size() / 2];

    _ensure_log_open(now_s);
    if (!log_) return;

    char buf[400];
    if (median > t.spread_trip_median) {
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s SPREAD-EVAL: rolling_n=%d median=%.4f trip=%.4f"
            " baseline_median=%.4f %s\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            n, median, t.spread_trip_median, t.backtest_spread_median_filt,
            logging_only ? "WOULD-TRIP" : "TRIPPED");
        ++s.day_trip_spread;
        ++s.cumulative_trip_spread;
        log_ << buf;
        log_.flush();
        char reason[160];
        std::snprintf(reason, sizeof(reason),
                      "SPREAD median=%.4f > trip=%.4f rolling_n=%d",
                      median, t.spread_trip_median, n);
        _maybe_auto_pin(s.engine, reason);
    } else {
        // Throttle OK lines to keep the log readable.
        if ((n % 50) != 0) return;
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON] %s %s SPREAD-EVAL: rolling_n=%d median=%.4f trip=%.4f"
            " baseline_median=%.4f OK\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            n, median, t.spread_trip_median, t.backtest_spread_median_filt);
        log_ << buf;
        log_.flush();
    }
}

inline void RiskMonitor::emit_daily_summary(int64_t now_s) {
    std::lock_guard<std::mutex> lk(mtx_);
    _ensure_log_open(now_s);
    if (!log_) return;

    for (auto& kv : states_) {
        RiskMonitorState& s = kv.second;
        const int closed_total = s.day_wins + s.day_losses;
        const double wr = closed_total > 0
            ? static_cast<double>(s.day_wins) / static_cast<double>(closed_total)
            : 0.0;

        char buf[400];
        std::snprintf(buf, sizeof(buf),
            "[RISK-MON-DAILY] %s %s fires=%d wins=%d losses=%d wr=%.3f%%"
            " pnl=%.2f trips_wr=%d trips_fire=%d trips_spread=%d"
            " cum_trips_wr=%d cum_trips_fire=%d cum_trips_spread=%d\n",
            _utc_date_str(now_s).c_str(), s.engine.c_str(),
            s.day_fires, s.day_wins, s.day_losses, wr * 100.0,
            s.day_pnl_sum,
            s.day_trip_wr, s.day_trip_fire, s.day_trip_spread,
            s.cumulative_trip_wr, s.cumulative_trip_fire, s.cumulative_trip_spread);
        log_ << buf;

        // Reset day aggregates (cumulative counters preserved).
        s.day_fires        = 0;
        s.day_wins         = 0;
        s.day_losses       = 0;
        s.day_pnl_sum      = 0.0;
        s.day_trip_wr      = 0;
        s.day_trip_fire    = 0;
        s.day_trip_spread  = 0;
    }
    log_.flush();
}

inline void RiskMonitor::_ensure_log_open(int64_t now_s) {
    const int day_idx = _utc_day_idx(now_s);
    if (current_log_day_idx_ == day_idx && log_.is_open()) return;
    if (log_.is_open()) log_.close();

    const std::string date_str = _utc_date_str(now_s);
    const std::string path = "logs/risk_monitor_" + date_str + ".log";
    log_.open(path, std::ios::app);
    if (!log_) {
        std::fprintf(stderr, "[RISK-MON] WARN cannot open %s for append\n",
                     path.c_str());
        return;
    }
    current_log_day_idx_ = day_idx;
}

inline void RiskMonitor::register_shadow_pin_cb(
    const std::string& engine,
    std::function<void(const std::string& reason)> cb)
{
    std::lock_guard<std::mutex> lk(mtx_);
    shadow_pin_cbs_[engine] = std::move(cb);
    std::fprintf(stderr, "[RISK-MON] auto-pin callback registered for engine=%s\n",
                 engine.c_str());
}

inline void RiskMonitor::_maybe_auto_pin(const std::string& engine,
                                         const std::string& reason)
{
    if (logging_only) return;
    auto pit = shadow_pin_cbs_.find(engine);
    if (pit == shadow_pin_cbs_.end() || !pit->second) return;
    // Caller already holds mtx_; the callback runs under the lock.
    // The engine.shadow_mode write inside the callback is a single bool
    // assignment which the engine reads on each tick under its own
    // serialisation, so no nested-lock risk.
    pit->second(reason);
}

inline void RiskMonitor::trip_engine_to_shadow(const std::string& engine,
                                               const std::string& reason)
{
    // Public wrapper around _maybe_auto_pin so external monitors (e.g. the
    // broker-disparity hard-stop at the end of handle_closed_trade in
    // trade_lifecycle.hpp) can pin an engine to shadow without reaching
    // into RiskMonitor internals. Takes the lock since outside callers
    // don't hold it.
    std::lock_guard<std::mutex> lk(mtx_);
    _maybe_auto_pin(engine, reason);
}

inline void RiskMonitor::_maybe_roll_day(RiskMonitorState& s, int64_t now_s) {
    const int day_idx = _utc_day_idx(now_s);
    if (s.day_utc_idx < 0)        { s.day_utc_idx = day_idx; return; }
    if (s.day_utc_idx == day_idx) { return; }
    // Day boundary crossed. The daily summary writer is responsible for
    // emitting the per-engine roll-up and resetting day_* counters; here
    // we just track which UTC day this state is currently in.
    s.day_utc_idx = day_idx;
}

inline int RiskMonitor::_utc_hour(int64_t now_s) {
    std::time_t t = static_cast<std::time_t>(now_s);
    std::tm utc{};
#ifdef _WIN32
    gmtime_s(&utc, &t);
#else
    gmtime_r(&t, &utc);
#endif
    return utc.tm_hour;
}

inline int RiskMonitor::_utc_day_idx(int64_t now_s) {
    return static_cast<int>(now_s / 86400);
}

inline std::string RiskMonitor::_utc_date_str(int64_t now_s) {
    std::time_t t = static_cast<std::time_t>(now_s);
    std::tm utc{};
#ifdef _WIN32
    gmtime_s(&utc, &t);
#else
    gmtime_r(&t, &utc);
#endif
    char buf[16];
    std::snprintf(buf, sizeof(buf), "%04d-%02d-%02d",
                  utc.tm_year + 1900, utc.tm_mon + 1, utc.tm_mday);
    return std::string(buf);
}

}  // namespace omega
