// AUTO-GENERATED by cmake/UpdateGitHash.cmake -- do not edit manually.
// Regenerated at every cmake configure. Always matches the compiled binary.
#pragma once
#define OMEGA_GIT_HASH   "2f14ecb"
#define OMEGA_GIT_DATE   "2026-04-04 22:22:22 +0000"
#define OMEGA_BUILD_TIME "2026-04-05 10:27 UTC"
