#!/usr/bin/env python3
# ENGINE REGISTRY (S-2026-06-24) -- the single map the system was missing.
#
# WHY: "what is enabled" (engine_init.hpp), "what is validated + its verdict"
# (backtest/AUDITED_CONFIGS.tsv), and "what counts as the book" (LiveBook.hpp
# allowlist) lived in THREE separate places with nothing joining them -- so an
# engine could be enabled+trading while UNAUDITED and nobody had one view of it.
#
# WHAT: join the three sources into one table. For every enabled entry-engine:
#   verdict (EDGE/MARGINAL/DEAD/SHADOW-CANDIDATE/UNAUDITED) + in-the-book? +
#   bear-gated? (validated engines clear the price-bear gate; the rest are blocked).
# Flags UNAUDITED enabled engines (the real answer to "what's not validated").
# Writes ENGINE_REGISTRY.md. Exit 1 if any enabled engine is UNAUDITED or DEAD.
#
# Usage: python3 tools/engine_registry.py [--repo <dir>]
import os, re, sys

REPO = "."
for i,a in enumerate(sys.argv):
    if a == "--repo" and i+1 < len(sys.argv): REPO = sys.argv[i+1]

def rd(p):
    try: return open(os.path.join(REPO, p), errors="ignore").read()
    except Exception: return ""

# 1. enabled engines: every `g_<name>.enabled = true` in engine_init.hpp + omega_main.hpp
enabled = {}   # global -> source line
for src in ("include/engine_init.hpp", "include/omega_main.hpp"):
    txt = rd(src)
    for m in re.finditer(r'(g_[A-Za-z0-9_]+)\.enabled\s*=\s*true', txt):
        enabled.setdefault(m.group(1), src)

# 2. audit verdicts: AUDITED_CONFIGS.tsv  (engine \t pf \t date \t harness \t verdict \t note)
verdicts = {}  # audit_engine_name -> (verdict, pf)
for ln in rd("backtest/AUDITED_CONFIGS.tsv").splitlines():
    if ln.startswith("#") or not ln.strip(): continue
    c = ln.split("\t")
    if len(c) >= 5: verdicts[c[0].strip()] = (c[4].strip(), c[1].strip())

# non-engines that match the g_<x>.enabled pattern but are infra, not entry engines
DENY = {"g_regime_adaptor", "g_aurora_gate", "g_macro_gold_gate", "g_engine_heartbeat",
        "g_risk_monitor", "g_macro_ctx", "g_adaptive_risk", "g_corr_matrix"}

# 3. livebook allowlist (the validated both-regime book). Each kEdge entry has a
#    trailing comment naming its AUDIT engine (e.g. "NasTurtleD1_US500.F" // SpxTurtleD1).
#    Build the book as the set of AUDIT names so it joins the verdict table cleanly.
lb = rd("include/LiveBook.hpp")
book_audit = set()   # audit-names that are in the validated book
m = re.search(r'kEdge\[\]\s*=\s*\{(.*?)\}', lb, re.S)
if m:
    for line in m.group(1).splitlines():
        tagm = re.search(r'"([A-Za-z0-9_.]+)"', line)
        cmtm = re.search(r'//\s*([A-Za-z0-9_]+)', line)
        if cmtm: book_audit.add(cmtm.group(1))          # the audit-name in the comment

def norm(s): return re.sub(r'[^a-z0-9]', '', s.lower())
audit_norm = {norm(k): k for k in verdicts}

def match_audit(g):
    n = norm(g[2:] if g.startswith("g_") else g)
    if n in audit_norm: return audit_norm[n]
    for an_norm, an in audit_norm.items():
        if an_norm in n or n in an_norm: return an
    return None
def in_book(audit_name):
    return audit_name in book_audit if audit_name else False

rows, unaudited, dead = [], [], []
for g in sorted(enabled):
    if g in DENY: continue                            # infra, not an entry engine
    an = match_audit(g)
    if an: verdict, pf = verdicts[an]
    else:  verdict, pf = "UNAUDITED", "-"
    booked = in_book(an)
    # validated both-regime engines clear the price-bear gate; everything else blocked
    bear_cleared = booked
    rows.append((g, verdict, pf, "YES" if booked else "no", "clears" if bear_cleared else "BLOCKED-in-bear"))
    if verdict == "UNAUDITED": unaudited.append(g)
    if verdict == "DEAD": dead.append(g)

out = ["# ENGINE REGISTRY (auto-generated by tools/engine_registry.py)", "",
       f"enabled entry-engines: {len(enabled)}  |  in-book (validated EDGE): {sum(1 for r in rows if r[3]=='YES')}  |  UNAUDITED: {len(unaudited)}  |  DEAD-but-enabled: {len(dead)}", "",
       "| engine (global) | verdict | faithful_pf | in book? | price-bear |",
       "|---|---|---|---|---|"]
for g, v, pf, b, bg in rows:
    out.append(f"| {g} | {v} | {pf} | {b} | {bg} |")
out += ["", "## UNAUDITED enabled engines (owe a verdict or disable):",
        ("\n".join(f"- {g}" for g in unaudited) if unaudited else "- none")]
md = "\n".join(out) + "\n"
open(os.path.join(REPO, "ENGINE_REGISTRY.md"), "w").write(md)
print(md)
print(f"[engine-registry] enabled={len(enabled)} unaudited={len(unaudited)} dead={len(dead)}")
sys.exit(1 if (unaudited or dead) else 0)
