# UpdateGitHash.cmake -- runs at configure time
# Writes version_generated.hpp AND the cmake variable file.
# Both are always in sync -- version_generated.hpp is never stale.

find_package(Git QUIET)

if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
    # SOURCE_HASH: last commit touching real source files (not log-push commits).
    # Mirrors the logic in DEPLOY_OMEGA.ps1 [3/9] -- skip commits that only
    # touch logs/ so the hash always reflects actual compiled code.
    execute_process(
        COMMAND ${GIT_EXECUTABLE} log --oneline -20 --format=%H
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE RECENT_COMMITS_RAW
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    string(REPLACE "\n" ";" RECENT_COMMITS "${RECENT_COMMITS_RAW}")

    set(GIT_HASH "unknown")
    set(GIT_DATE "unknown")
    foreach(COMMIT_HASH ${RECENT_COMMITS})
        execute_process(
            COMMAND ${GIT_EXECUTABLE} show --name-only --format= ${COMMIT_HASH}
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE CHANGED_FILES_RAW
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        string(REPLACE "\n" ";" CHANGED_FILES "${CHANGED_FILES_RAW}")
        set(HAS_SOURCE_FILE FALSE)
        foreach(F ${CHANGED_FILES})
            if(F MATCHES "^(src/|include/|CMakeLists)")
                set(HAS_SOURCE_FILE TRUE)
                break()
            endif()
        endforeach()
        if(HAS_SOURCE_FILE)
            string(SUBSTRING "${COMMIT_HASH}" 0 7 GIT_HASH)
            execute_process(
                COMMAND ${GIT_EXECUTABLE} log -1 --format=%ci ${COMMIT_HASH}
                WORKING_DIRECTORY "${SOURCE_DIR}"
                OUTPUT_VARIABLE GIT_DATE
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
            )
            break()
        endif()
    endforeach()

    # Override: if caller explicitly passes a hash (DEPLOY_OMEGA.ps1 step [3/9])
    if(DEFINED OMEGA_FORCE_GIT_HASH AND NOT "${OMEGA_FORCE_GIT_HASH}" STREQUAL "")
        set(GIT_HASH "${OMEGA_FORCE_GIT_HASH}")
    endif()
else()
    set(GIT_HASH "unknown")
    set(GIT_DATE "unknown")
endif()

string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%d %H:%M UTC")

# Write cmake variable file (consumed by CMakeLists.txt for /D defines)
file(WRITE "${OUTPUT_FILE}"
"set(OMEGA_GIT_HASH   \"${GIT_HASH}\")
set(OMEGA_GIT_DATE   \"${GIT_DATE}\")
set(OMEGA_BUILD_TIME \"${BUILD_TIMESTAMP}\")
")

# Write version_generated.hpp -- ALWAYS in sync with the cmake /D define.
# This is the single source of truth for the GUI badge.
# Never stale: regenerated at every cmake configure (every DEPLOY_OMEGA.ps1 run).
file(WRITE "${SOURCE_DIR}/include/version_generated.hpp"
"// AUTO-GENERATED by cmake/UpdateGitHash.cmake -- do not edit manually.
// Regenerated at every cmake configure. Always matches the compiled binary.
#pragma once
#define OMEGA_GIT_HASH   \"${GIT_HASH}\"
#define OMEGA_GIT_DATE   \"${GIT_DATE}\"
#define OMEGA_BUILD_TIME \"${BUILD_TIMESTAMP}\"
")

message(STATUS "[Omega] Git hash: ${GIT_HASH} | Built: ${BUILD_TIMESTAMP}")
