# UpdateGitHash.cmake -- runs at configure time
# Gets the hash of the current HEAD commit directly -- no file scanning.
# This is the hash of whatever is checked out on the build machine.

cmake_minimum_required(VERSION 3.10)
find_package(Git QUIET)

if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short=7 HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    execute_process(
        COMMAND ${GIT_EXECUTABLE} log -1 --format=%ci HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_DATE
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if(NOT GIT_HASH)
        set(GIT_HASH "unknown")
        set(GIT_DATE "unknown")
    endif()
else()
    set(GIT_HASH "unknown")
    set(GIT_DATE "unknown")
endif()

# Override: if caller explicitly passes a hash
if(DEFINED OMEGA_FORCE_GIT_HASH AND NOT "${OMEGA_FORCE_GIT_HASH}" STREQUAL "")
    set(GIT_HASH "${OMEGA_FORCE_GIT_HASH}")
endif()

string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%d %H:%M UTC")

file(WRITE "${OUTPUT_FILE}"
"set(OMEGA_GIT_HASH   \"${GIT_HASH}\")
set(OMEGA_GIT_DATE   \"${GIT_DATE}\")
set(OMEGA_BUILD_TIME \"${BUILD_TIMESTAMP}\")
")

file(WRITE "${SOURCE_DIR}/include/version_generated.hpp"
"// AUTO-GENERATED by cmake/UpdateGitHash.cmake -- do not edit manually.
#pragma once
#define OMEGA_GIT_HASH   \"${GIT_HASH}\"
#define OMEGA_GIT_DATE   \"${GIT_DATE}\"
#define OMEGA_BUILD_TIME \"${BUILD_TIMESTAMP}\"
")

message(STATUS "[Omega] Git hash: ${GIT_HASH} | Built: ${BUILD_TIMESTAMP}")
